import BijForm.StringDiagram.FiniteCoding

namespace BijForm
namespace Examples

open DepPoly
open StringDiagram

/-- Node labels for the standard symmetric interaction-net signature. -/
inductive SymmetricInteractionNetNode where
  | dup
  | erase
  | cons
deriving DecidableEq, Repr

/-- All wires in the untyped symmetric interaction-net signature share one type. -/
abbrev SymmetricInteractionNetWire : Type := Unit

/-- Ordered arity of each symmetric interaction-net node. -/
def SymmetricInteractionNetArity : SymmetricInteractionNetNode → Nat
  | .dup => 3
  | .erase => 1
  | .cons => 3

/-- Every port in the untyped signature carries the unique wire type. -/
def SymmetricInteractionNetPort
    (node : SymmetricInteractionNetNode)
    (_slot : Fin (SymmetricInteractionNetArity node)) :
    SymmetricInteractionNetWire :=
  ()

/-- The standard untyped symmetric interaction-net string-diagram signature. -/
def SymmetricInteractionNetSignature : Signature :=
  Unoriented.signature
    SymmetricInteractionNetWire
    SymmetricInteractionNetNode
    SymmetricInteractionNetArity
    SymmetricInteractionNetPort

@[simp] theorem SymmetricInteractionNetSignature_arity_dup :
    SymmetricInteractionNetSignature.arity SymmetricInteractionNetNode.dup = 3 :=
  rfl

@[simp] theorem SymmetricInteractionNetSignature_arity_erase :
    SymmetricInteractionNetSignature.arity SymmetricInteractionNetNode.erase = 1 :=
  rfl

@[simp] theorem SymmetricInteractionNetSignature_arity_cons :
    SymmetricInteractionNetSignature.arity SymmetricInteractionNetNode.cons = 3 :=
  rfl

/-- Finite single-sorted coding data for the SIN signature. -/
def SymmetricInteractionNetCodingData :
    SingleSortedFiniteCodingData SymmetricInteractionNetSignature where
  compatibleAll := by
    intro left right
    cases left
    cases right
    rfl
  nodeCount := 3
  nodeCount_pos := by decide
  entryCount := 7
  entryCount_pos := by decide
  recursiveEntryCount := 6
  recursiveEntryCount_pos := by decide

/-- Ordered-frontier symmetric interaction-net traversal syntax. -/
abbrev SymmetricInteractionNetDiag
    (boundary : List SymmetricInteractionNetSignature.Port) : Type :=
  StringDiagram.Diag SymmetricInteractionNetSignature boundary

/-- Dependent polynomial generated by the symmetric interaction-net signature. -/
abbrev SymmetricInteractionNetPoly :
    DepPoly (List SymmetricInteractionNetSignature.Port) :=
  BijForm.StringDiagram.poly SymmetricInteractionNetSignature

/-- Same-fiber constructor data for the SIN traversal polynomial. -/
abbrev SymmetricInteractionNetInversion :
    OutputIndexInversion SymmetricInteractionNetPoly :=
  BijForm.StringDiagram.inversion SymmetricInteractionNetSignature

/-- Generated coding data for symmetric interaction-net diagrams. -/
abbrev SymmetricInteractionNetGeneratedCode :
    GeneratedCode SymmetricInteractionNetPoly
      (fun boundary => StringDiagram.Diag SymmetricInteractionNetSignature boundary) :=
  BijForm.StringDiagram.generatedCode SymmetricInteractionNetSignature

/-- Generated-code equivalence for symmetric interaction-net diagrams. -/
abbrev SymmetricInteractionNetSyntaxIso
    (boundary : List SymmetricInteractionNetSignature.Port) :
    Mu SymmetricInteractionNetPoly boundary ≃ᵢ
      SymmetricInteractionNetDiag boundary :=
  singleSortedFiniteSyntaxIso
    SymmetricInteractionNetSignature
    SymmetricInteractionNetCodingData
    boundary

/-- Semantic open port-hypergraphs over the symmetric interaction-net signature. -/
abbrev SymmetricInteractionNetOpenGraph
    (boundary : List SymmetricInteractionNetSignature.Port) : Type :=
  OpenPortHypergraph SymmetricInteractionNetSignature boundary

/-- Semantic open port-hypergraphs up to ordered-boundary-preserving isomorphism. -/
abbrev SymmetricInteractionNetOpenGraphQuotient
    (boundary : List SymmetricInteractionNetSignature.Port) : Type :=
  OpenPortHypergraphUpToIso SymmetricInteractionNetSignature boundary

/-- Encoding of symmetric interaction-net diagrams by semantic open graphs. -/
abbrev SymmetricInteractionNetOpenGraphIso
    (boundary : List SymmetricInteractionNetSignature.Port) :
    SymmetricInteractionNetDiag boundary ≃ᵢ
      SymmetricInteractionNetOpenGraphQuotient boundary :=
  diagOpenPortHypergraphIso SymmetricInteractionNetSignature boundary

/-- Generated finite/infinite carrier shape for symmetric interaction-net diagrams. -/
abbrev SymmetricInteractionNetShape :
    List SymmetricInteractionNetSignature.Port → CodeShape :=
  openFrontierShape SymmetricInteractionNetSignature

/-- Generated shape-code data for symmetric interaction-net diagrams. -/
abbrev SymmetricInteractionNetGeneratedShapeCode :
    GeneratedShapeCode SymmetricInteractionNetPoly :=
  singleSortedFiniteGeneratedShapeCode
    SymmetricInteractionNetSignature
    SymmetricInteractionNetCodingData

/-- Empty-frontier SIN traversal syntax is the singleton finite carrier. -/
def SymmetricInteractionNetSyntaxEmptyFinOneIso :
    SymmetricInteractionNetDiag [] ≃ᵢ Fin 1 :=
  singleSortedFiniteSyntaxEmptyFinOneIso
    SymmetricInteractionNetSignature
    SymmetricInteractionNetCodingData

/-- Nonempty-frontier SIN traversal syntax is a natural-number carrier. -/
def SymmetricInteractionNetSyntaxNonemptyNatIso
    (active : SymmetricInteractionNetSignature.Port)
    (frontier : List SymmetricInteractionNetSignature.Port) :
    SymmetricInteractionNetDiag (active :: frontier) ≃ᵢ Nat :=
  singleSortedFiniteSyntaxNonemptyNatIso
    SymmetricInteractionNetSignature
    SymmetricInteractionNetCodingData
    active
    frontier

/-- Empty-frontier SIN open graphs inherit the singleton syntax carrier. -/
def SymmetricInteractionNetOpenGraphEmptyFinOneIso :
    SymmetricInteractionNetOpenGraphQuotient [] ≃ᵢ Fin 1 :=
  singleSortedFiniteOpenGraphEmptyFinOneIso
    SymmetricInteractionNetSignature
    SymmetricInteractionNetCodingData

/-- Nonempty-frontier SIN open graphs inherit the natural-number syntax carrier. -/
def SymmetricInteractionNetOpenGraphNonemptyNatIso
    (active : SymmetricInteractionNetSignature.Port)
    (frontier : List SymmetricInteractionNetSignature.Port) :
    SymmetricInteractionNetOpenGraphQuotient (active :: frontier) ≃ᵢ Nat :=
  singleSortedFiniteOpenGraphNonemptyNatIso
    SymmetricInteractionNetSignature
    SymmetricInteractionNetCodingData
    active
    frontier

end Examples
end BijForm
