import BijForm.DependentPolynomial
import BijForm.CodeAlgebra

namespace BijForm
namespace Examples
namespace TypedBinding

open DepPoly

/-- One recursive argument of a typed binding constructor.  The argument is
checked under the surrounding context extended by `binders`, and must construct
an object of sort `sort`.  A nonbinding recursive argument has `binders = []`. -/
structure Arg (Ty : Type) where
  binders : List Ty
  sort : Ty

/-- A typed binding signature.  The constructor set may be infinite; each
constructor still has a finite list of recursive arguments. -/
structure Signature (Ty : Type) where
  Ctor : Type
  args : Ctor → List (Arg Ty)
  ret : Ctor → Ty

namespace Signature

variable {Ty : Type} (S : Signature Ty)

def ArgPos (c : S.Ctor) : Type :=
  Fin (S.args c).length

def arg (c : S.Ctor) (q : S.ArgPos c) : Arg Ty :=
  (S.args c).get q

end Signature

/-- Typed de Bruijn variables.  A variable of type `t` is available exactly
when the current context contains a `t`. -/
inductive Var {Ty : Type} : List Ty → Ty → Type
  | here {Γ : List Ty} {t : Ty} : Var (t :: Γ) t
  | there {Γ : List Ty} {t u : Ty} : Var Γ t → Var (u :: Γ) t

namespace Var

variable {Ty : Type}

def absurd_nil {t : Ty} : Var ([] : List Ty) t → Empty
  | v => nomatch v

def count [DecidableEq Ty] (t : Ty) : List Ty → Nat
  | [] => 0
  | u :: Γ => if u = t then count t Γ + 1 else count t Γ

def toFin [DecidableEq Ty] : {Γ : List Ty} → {t : Ty} → Var Γ t → Fin (count t Γ)
  | _ :: _, _, here => ⟨0, by simp [count]⟩
  | u :: Γ, t, there v =>
      let i := toFin v
      if h : u = t then
        ⟨i.val + 1, by
          simp [count, h]⟩
      else
        ⟨i.val, by
          simp [count, h]⟩

def ofFin [DecidableEq Ty] (t : Ty) : {Γ : List Ty} → Fin (count t Γ) → Var Γ t
  | [], i => False.elim (Nat.not_lt_zero i.val i.isLt)
  | u :: Γ, i => by
      by_cases h : u = t
      · cases h
        let i' : Fin (count t Γ + 1) := ⟨i.val, by
          simpa [count] using i.isLt⟩
        exact Fin.cases here (fun j => there (ofFin t j)) i'
      · exact there (ofFin t (Γ := Γ) ⟨i.val, by
          simpa [count, h] using i.isLt⟩)

theorem ofFin_toFin [DecidableEq Ty] (t : Ty) :
    ∀ {Γ : List Ty} (i : Fin (count t Γ)), toFin (ofFin t i) = i := by
  intro Γ
  induction Γ with
  | nil =>
      intro i
      exact False.elim (Nat.not_lt_zero i.val i.isLt)
  | cons u Γ ih =>
      intro i
      by_cases h : u = t
      · cases h
        cases i with
        | mk n hn =>
          cases n with
          | zero =>
              apply Fin.ext
              simp [ofFin, toFin, count]
          | succ n =>
              apply Fin.ext
              simp [ofFin, toFin, count]
              exact congrArg Fin.val (ih ⟨n, by
                simp [count] at hn
                omega⟩)
      · apply Fin.ext
        have hi : i.val < count t Γ := by
          simpa [count, h] using i.isLt
        simp [ofFin, toFin, count, h]
        exact congrArg Fin.val (ih ⟨i.val, hi⟩)

theorem toFin_ofFin [DecidableEq Ty] :
    ∀ {Γ : List Ty} {t : Ty} (v : Var Γ t), ofFin t (toFin v) = v
  | _ :: _, _, here => by
      simp [toFin, ofFin, count]
  | u :: _, t, there v => by
      by_cases h : u = t
      · cases h
        simp [toFin, ofFin, count, toFin_ofFin v]
      · simp [toFin, ofFin, count, h, toFin_ofFin v]

def finIso [DecidableEq Ty] (Γ : List Ty) (t : Ty) :
    Var Γ t ≃ᵢ Fin (count t Γ) where
  toFun := toFin
  invFun := ofFin t
  left_inv := toFin_ofFin
  right_inv := ofFin_toFin t

end Var

/-- Readable syntax generated by a typed binding signature. -/
inductive Term {Ty : Type} (S : Signature Ty) : List Ty → Ty → Type
  | var {Γ : List Ty} {t : Ty} (v : Var Γ t) : Term S Γ t
  | op {Γ : List Ty} (c : S.Ctor)
      (child :
        (q : S.ArgPos c) →
          Term S ((S.arg c q).binders ++ Γ) (S.arg c q).sort) :
      Term S Γ (S.ret c)

namespace Term

variable {Ty : Type} {S : Signature Ty}

def finMax : {n : Nat} → (Fin n → Nat) → Nat
  | 0, _ => 0
  | n + 1, f =>
      Nat.max (f ⟨0, Nat.zero_lt_succ n⟩)
        (finMax (fun q : Fin n => f q.succ))

theorem le_finMax {n : Nat} (f : Fin n → Nat) (q : Fin n) :
    f q ≤ finMax f := by
  induction n with
  | zero =>
      exact False.elim (Nat.not_lt_zero q.val q.isLt)
  | succ n ih =>
      cases q using Fin.cases with
      | zero =>
          exact Nat.le_max_left _ _
      | succ q =>
          exact Nat.le_trans (ih (fun r : Fin n => f r.succ) q)
            (Nat.le_max_right _ _)

/-- Structural rank used for the generated syntax coding. -/
def rank : {Γ : List Ty} → {t : Ty} → Term S Γ t → Nat
  | _, _, var _ => 0
  | _, _, op c child =>
      finMax (fun q : S.ArgPos c => rank (child q)) + 1

theorem child_rank_lt {Γ : List Ty} {c : S.Ctor}
    (child :
      (q : S.ArgPos c) →
        Term S ((S.arg c q).binders ++ Γ) (S.arg c q).sort)
    (q : S.ArgPos c) :
    rank (child q) < rank (Term.op (S := S) (Γ := Γ) c child) := by
  exact Nat.lt_succ_of_le (le_finMax (fun q : S.ArgPos c => rank (child q)) q)

end Term

/-- Polynomial constructors generated from a binding signature.  Variables are
not part of the user signature; they are generated from the current context. -/
inductive PolyCtor {Ty : Type} (S : Signature Ty) where
  | var
  | op (c : S.Ctor)

namespace Poly

variable {Ty : Type} (S : Signature Ty)

abbrev Ix (_S : Signature Ty) : Type :=
  List Ty × Ty

def Param : PolyCtor S → Type
  | .var => Σ Γ : List Ty, Σ t : Ty, Var Γ t
  | .op _ => List Ty

def out : (c : PolyCtor S) → Param S c → Ix S
  | .var, p => (p.1, p.2.1)
  | .op c, Γ => (Γ, S.ret c)

def Pos : (c : PolyCtor S) → Param S c → Type
  | .var, _ => Empty
  | .op c, _ => S.ArgPos c

def input : {c : PolyCtor S} → (p : Param S c) → Pos S c p → Ix S
| .var, _, q => nomatch q
| .op c, (Γ : List Ty), q => ((S.arg c q).binders ++ Γ, (S.arg c q).sort)

/-- The dependent polynomial generated by a typed binding signature. -/
def depPoly : DepPoly (Ix S) where
  Ctor := PolyCtor S
  Param := Param S
  out := out S
  Pos := Pos S
  input := input S

end Poly

abbrev PolyOf {Ty : Type} (S : Signature Ty) : DepPoly (Poly.Ix S) :=
  Poly.depPoly S

/-- Same-fiber constructor code generated from the binding signature. -/
inductive FiberCode {Ty : Type} (S : Signature Ty) : Poly.Ix S → Type
  | var {Γ : List Ty} {t : Ty} (v : Var Γ t) : FiberCode S (Γ, t)
  | op {Γ : List Ty} {t : Ty} (c : S.Ctor) (h : S.ret c = t) :
      FiberCode S (Γ, t)

namespace FiberCode

variable {Ty : Type} {S : Signature Ty}

def decode (i : Poly.Ix S) : FiberCode S i → Fiber (PolyOf S) i
  | var (Γ := Γ) (t := t) v =>
      ⟨.var, ⟨Γ, t, v⟩, rfl⟩
  | op (Γ := Γ) c h => by
      cases h
      exact ⟨.op c, Γ, rfl⟩

def encode (i : Poly.Ix S) : Fiber (PolyOf S) i → FiberCode S i
  | ⟨.var, p, h⟩ => by
      cases p with
      | mk Γ rest =>
        cases rest with
        | mk t v =>
          cases h
          exact var v
  | ⟨.op c, Γ, h⟩ => by
      cases h
      exact op c rfl

theorem decode_encode (i : Poly.Ix S) (f : Fiber (PolyOf S) i) :
    decode i (encode i f) = f := by
  cases f with
  | mk ctor param out_eq =>
      cases ctor with
      | var =>
          cases param with
          | mk Γ rest =>
            cases rest with
            | mk t v =>
              cases out_eq
              rfl
      | op c =>
          cases out_eq
          rfl

theorem encode_decode (i : Poly.Ix S) (c : FiberCode S i) :
    encode i (decode i c) = c := by
  cases c with
  | var v => rfl
  | op c h =>
      cases h
      rfl

end FiberCode

/-- Output-index inversion generated from the binding signature. -/
def inversion {Ty : Type} (S : Signature Ty) :
    OutputIndexInversion (PolyOf S) where
  Code := FiberCode S
  decode := FiberCode.decode
  encode := FiberCode.encode
  decode_encode := FiberCode.decode_encode
  encode_decode := FiberCode.encode_decode

namespace SyntaxIso

variable {Ty : Type} {S : Signature Ty}

def layerToTerm (i : Poly.Ix S) :
    CodeLayer (PolyOf S) (inversion S) (fun i => Term S i.1 i.2) i →
      Term S i.1 i.2
  | ⟨.var v, _child⟩ => Term.var v
  | ⟨.op c h, child⟩ => by
      cases i with
      | mk Γ t =>
        cases h
        refine Term.op (S := S) (Γ := Γ) c ?_
        intro q
        exact child q

def termToLayer : {Γ : List Ty} → {t : Ty} →
    Term S Γ t →
      CodeLayer (PolyOf S) (inversion S) (fun i => Term S i.1 i.2) (Γ, t)
  | _, _, Term.var v => ⟨.var v, fun q => nomatch q⟩
  | _, _, Term.op c child => by
      refine ⟨.op c rfl, ?_⟩
      intro q
      exact child q

theorem layer_left_inv (i : Poly.Ix S) :
    Function.LeftInverse
      (fun t : Term S i.1 i.2 => termToLayer t)
      (layerToTerm (S := S) i) := by
  intro layer
  cases i with
  | mk Γ t =>
    cases layer with
    | mk code child =>
      cases code with
      | var v =>
          have hchild : (fun q => nomatch q) = child := by
            funext q
            cases q
          cases hchild
          rfl
      | op c h =>
          cases h
          refine Sigma.ext rfl ?_
          apply heq_of_eq
          funext q
          rfl

theorem layer_right_inv (i : Poly.Ix S) :
    Function.RightInverse
      (fun t : Term S i.1 i.2 => termToLayer t)
      (layerToTerm (S := S) i) := by
  intro t
  cases i with
  | mk Γ ty =>
    cases t with
    | var v => rfl
    | op c child =>
        simp [layerToTerm, termToLayer]

def layerIso (i : Poly.Ix S) :
    CodeLayer (PolyOf S) (inversion S) (fun i => Term S i.1 i.2) i ≃ᵢ
      Term S i.1 i.2 where
  toFun := layerToTerm (S := S) i
  invFun := fun t => termToLayer t
  left_inv := layer_left_inv (S := S) i
  right_inv := layer_right_inv (S := S) i

theorem layer_child_rank_lt :
    ∀ {i : Poly.Ix S} (z : Term S i.1 i.2)
      (q : (PolyOf S).Pos
          ((inversion S).decode i ((layerIso (S := S) i).invFun z).1).ctor
          ((inversion S).decode i ((layerIso (S := S) i).invFun z).1).param),
      Term.rank (((layerIso (S := S) i).invFun z).2 q) < Term.rank z := by
  intro i z q
  cases i with
  | mk Γ t =>
    cases z with
    | var v => cases q
    | op c child =>
        simpa [layerIso, termToLayer] using
          Term.child_rank_lt (S := S) (Γ := Γ) child q

end SyntaxIso

/-- The generated coding of the initial algebra by readable binding syntax. -/
def syntaxGeneratedCode {Ty : Type} (S : Signature Ty) :
    GeneratedCode (PolyOf S) (fun i => Term S i.1 i.2) where
  inversion := inversion S
  layer := SyntaxIso.layerIso
  rank := fun _ t => Term.rank t
  child_rank_lt := SyntaxIso.layer_child_rank_lt

/-- Readable binding syntax is isomorphic to the generated initial algebra. -/
def syntaxIso {Ty : Type} (S : Signature Ty) (Γ : List Ty) (t : Ty) :
    Mu (PolyOf S) (Γ, t) ≃ᵢ Term S Γ t :=
  (syntaxGeneratedCode S).iso (Γ, t)

/-- Coding data for a binding signature with an arbitrary index-dependent
carrier family.  The rank proof is stated on the decoded one-step layer; the
generic dependent-polynomial framework turns it into the encoded-parent
well-foundedness proof. -/
structure CodeCodingData {Ty : Type} (S : Signature Ty) where
  Code : Poly.Ix S → Type
  layer : ∀ i, CodeLayer (PolyOf S) (inversion S) Code i ≃ᵢ Code i
  rank : ∀ i, Code i → Nat
  layer_child_rank_lt :
    ∀ {i : Poly.Ix S} (x : CodeLayer (PolyOf S) (inversion S) Code i)
      (q : (PolyOf S).Pos
          ((inversion S).decode i x.1).ctor
          ((inversion S).decode i x.1).param),
      rank ((PolyOf S).input ((inversion S).decode i x.1).param q) (x.2 q) <
        rank i ((layer i).toFun x)

namespace CodeCodingData

variable {Ty : Type} {S : Signature Ty}

def toGeneratedCode (D : CodeCodingData S) :
    GeneratedCode (PolyOf S) D.Code :=
  GeneratedCode.ofLayerChildRank (inversion S) D.layer D.rank
    (by
      intro i x q
      exact D.layer_child_rank_lt x q)

def iso (D : CodeCodingData S) (Γ : List Ty) (t : Ty) :
    Mu (PolyOf S) (Γ, t) ≃ᵢ D.Code (Γ, t) :=
  D.toGeneratedCode.iso (Γ, t)

def syntaxCodeIso (D : CodeCodingData S) (Γ : List Ty) (t : Ty) :
    Term S Γ t ≃ᵢ D.Code (Γ, t) :=
  Iso.trans (Iso.symm (syntaxIso S Γ t)) (D.iso Γ t)

end CodeCodingData

/-- Shape-coding data for a binding signature.  The generic binding module
generates the polynomial and syntax route; a concrete signature supplies this
one-step shape coding and rank proof when it wants an actual code carrier. -/
structure ShapeCodingData {Ty : Type} (S : Signature Ty) where
  shape : Poly.Ix S → CodeShape
  layer : ∀ i,
    CodeLayer (PolyOf S) (inversion S) (fun j => (shape j).Carrier) i ≃ᵢ
      (shape i).Carrier
  rank : ∀ i, (shape i).Carrier → Nat
  layer_child_rank_lt :
    ∀ {i : Poly.Ix S}
      (x : CodeLayer (PolyOf S) (inversion S) (fun j => (shape j).Carrier) i)
      (q : (PolyOf S).Pos
          ((inversion S).decode i x.1).ctor
          ((inversion S).decode i x.1).param),
      rank ((PolyOf S).input ((inversion S).decode i x.1).param q) (x.2 q) <
        rank i ((layer i).toFun x)

namespace ShapeCodingData

variable {Ty : Type} {S : Signature Ty}

def toCodeCodingData (D : ShapeCodingData S) :
    CodeCodingData S where
  Code := fun i => (D.shape i).Carrier
  layer := D.layer
  rank := D.rank
  layer_child_rank_lt := by
    intro i x q
    exact D.layer_child_rank_lt x q

def toGeneratedShapeCode (D : ShapeCodingData S) :
    GeneratedShapeCode (PolyOf S) where
  shape := D.shape
  inversion := inversion S
  layer := D.layer
  rank := D.rank
  child_rank_lt := by
    intro i z q
    simpa using
      D.layer_child_rank_lt ((D.layer i).invFun z) q

def iso (D : ShapeCodingData S) (Γ : List Ty) (t : Ty) :
    Mu (PolyOf S) (Γ, t) ≃ᵢ (D.shape (Γ, t)).Carrier :=
  D.toCodeCodingData.iso Γ t

def syntaxCarrierIso (D : ShapeCodingData S) (Γ : List Ty) (t : Ty) :
    Term S Γ t ≃ᵢ (D.shape (Γ, t)).Carrier :=
  D.toCodeCodingData.syntaxCodeIso Γ t

end ShapeCodingData

/-!
## Normal-form lambda expressions

The blog-post normal-form syntax has two mutually recursive sorts.  Variables
belong to the application-term sort.  The lambda constructor binds one
application-term variable in its body, while the other recursive arguments use empty
binder lists.
-/

inductive NFSort where
  | normalExp
  | appTerm
deriving DecidableEq, Repr

namespace NFSort

def isAppTerm : NFSort → Bool
  | .normalExp => false
  | .appTerm => true

end NFSort

inductive NFCtor where
  | dum
  | lam
  | app
deriving DecidableEq, Repr

def NFArgs : NFCtor → List (Arg NFSort)
  | .dum => [{ binders := [], sort := .appTerm }]
  | .lam => [{ binders := [.appTerm], sort := .normalExp }]
  | .app =>
      [{ binders := [], sort := .appTerm },
       { binders := [], sort := .normalExp }]

def NFRet : NFCtor → NFSort
  | .dum => .normalExp
  | .lam => .normalExp
  | .app => .appTerm

def NFSignature : Signature NFSort where
  Ctor := NFCtor
  args := NFArgs
  ret := NFRet

abbrev NFTerm (Γ : List NFSort) (t : NFSort) : Type :=
  Term NFSignature Γ t

abbrev NFPoly : DepPoly (Poly.Ix NFSignature) :=
  PolyOf NFSignature

def NormalExp (Γ : List NFSort) : Type :=
  NFTerm Γ .normalExp

def AppTerm (Γ : List NFSort) : Type :=
  NFTerm Γ .appTerm

def NFClosed : Type :=
  NormalExp []

def NFVar {Γ : List NFSort} (v : Var Γ .appTerm) : AppTerm Γ :=
  Term.var v

def NFDum {Γ : List NFSort} (e : AppTerm Γ) : NormalExp Γ :=
  Term.op (S := NFSignature) NFCtor.dum (fun
    | ⟨0, _⟩ => e
    | ⟨n + 1, h⟩ => by
        simp [NFSignature, NFArgs] at h)

def NFLam {Γ : List NFSort} (body : NormalExp (.appTerm :: Γ)) :
    NormalExp Γ :=
  Term.op (S := NFSignature) NFCtor.lam (fun
    | ⟨0, _⟩ => body
    | ⟨n + 1, h⟩ => by
        simp [NFSignature, NFArgs] at h)

def NFApp {Γ : List NFSort} (fn : AppTerm Γ) (arg : NormalExp Γ) :
    AppTerm Γ :=
  Term.op (S := NFSignature) NFCtor.app (fun
    | ⟨0, _⟩ => fn
    | ⟨1, _⟩ => arg
    | ⟨n + 2, h⟩ => by
        simp [NFSignature, NFArgs] at h
        omega)

def NFInversion : OutputIndexInversion NFPoly :=
  inversion NFSignature

def NFSyntaxIso (Γ : List NFSort) (t : NFSort) :
    Mu NFPoly (Γ, t) ≃ᵢ NFTerm Γ t :=
  syntaxIso NFSignature Γ t

abbrev appTermCount (Γ : List NFSort) : Nat :=
  Var.count NFSort.appTerm Γ

abbrev normalExpCount (Γ : List NFSort) : Nat :=
  Var.count NFSort.normalExp Γ

abbrev appTermVarToFin {Γ : List NFSort} :
    Var Γ .appTerm → Fin (appTermCount Γ) :=
  Var.toFin

abbrev appTermFinToVar {Γ : List NFSort} :
    Fin (appTermCount Γ) → Var Γ .appTerm :=
  Var.ofFin NFSort.appTerm

theorem appTermFinToVar_toFin {Γ : List NFSort} (i : Fin (appTermCount Γ)) :
    appTermVarToFin (appTermFinToVar i) = i :=
  Var.ofFin_toFin NFSort.appTerm i

theorem appTermVarToFin_toVar {Γ : List NFSort} (v : Var Γ .appTerm) :
    appTermFinToVar (appTermVarToFin v) = v :=
  Var.toFin_ofFin v

abbrev normalExpVarToFin {Γ : List NFSort} :
    Var Γ .normalExp → Fin (normalExpCount Γ) :=
  Var.toFin

abbrev normalExpFinToVar {Γ : List NFSort} :
    Fin (normalExpCount Γ) → Var Γ .normalExp :=
  Var.ofFin NFSort.normalExp

theorem normalExpFinToVar_toFin {Γ : List NFSort} (i : Fin (normalExpCount Γ)) :
    normalExpVarToFin (normalExpFinToVar i) = i :=
  Var.ofFin_toFin NFSort.normalExp i

theorem normalExpVarToFin_toVar {Γ : List NFSort} (v : Var Γ .normalExp) :
    normalExpFinToVar (normalExpVarToFin v) = v :=
  Var.toFin_ofFin v

def NFCode : Poly.Ix NFSignature → Type
  | (_, .normalExp) => Nat
  | (Γ, .appTerm) => Fin (appTermCount Γ) × Nat

abbrev NFNormalLayerShape (Γ : List NFSort) : Type :=
  Fin (normalExpCount Γ) ⊕ (NFCode (Γ, .appTerm) ⊕ Nat)

abbrev NFAppTermLayerShape (Γ : List NFSort) : Type :=
  Fin (appTermCount Γ) ⊕ (NFCode (Γ, .appTerm) × Nat)

def NFCodeRank : ∀ i, NFCode i → Nat
  | (Γ, .normalExp), n => by
      change Nat at n
      exact if appTermCount Γ = 0 then 2 * n + 2 else 2 * n + 1
  | (_, .appTerm), p => 2 * p.2

def NFNormalLayerToShape (Γ : List NFSort) :
    CodeLayer NFPoly NFInversion NFCode (Γ, .normalExp) → NFNormalLayerShape Γ
  | ⟨.var v, _child⟩ => Sum.inl (normalExpVarToFin v)
  | ⟨.op .dum h, child⟩ => by
      cases h
      exact Sum.inr (Sum.inl (child ⟨0, by decide⟩))
  | ⟨.op .lam h, child⟩ => by
      cases h
      exact Sum.inr (Sum.inr (child ⟨0, by decide⟩))
  | ⟨.op .app h, _child⟩ => by
      cases h

def NFNormalLayerOfShape (Γ : List NFSort) :
    NFNormalLayerShape Γ → CodeLayer NFPoly NFInversion NFCode (Γ, .normalExp)
  | Sum.inl v => ⟨.var (normalExpFinToVar v), fun q => nomatch q⟩
  | Sum.inr (Sum.inl e) =>
      ⟨.op NFCtor.dum rfl, fun
        | ⟨0, _⟩ => e
        | ⟨n + 1, h⟩ => by
            simp [NFSignature, NFArgs] at h⟩
  | Sum.inr (Sum.inr body) =>
      ⟨.op NFCtor.lam rfl, fun
        | ⟨0, _⟩ => body
        | ⟨n + 1, h⟩ => by
            simp [NFSignature, NFArgs] at h⟩

theorem NFNormalLayerShape_left_inv (Γ : List NFSort) :
    Function.LeftInverse (NFNormalLayerOfShape Γ) (NFNormalLayerToShape Γ) := by
  intro layer
  cases layer with
  | mk code child =>
      cases code with
      | var v =>
          have hchild : (fun q => nomatch q) = child := by
            funext q
            cases q
          cases hchild
          change NFNormalLayerOfShape Γ (Sum.inl (normalExpVarToFin v)) =
            ⟨FiberCode.var v, (fun q => nomatch q)⟩
          dsimp [NFNormalLayerOfShape]
          rw [normalExpVarToFin_toVar v]
          refine Sigma.ext rfl ?_
          apply heq_of_eq
          funext q
          cases q
      | op c h =>
          cases c with
          | dum =>
              cases h
              refine Sigma.ext rfl ?_
              apply heq_of_eq
              funext q
              cases q using Fin.cases with
              | zero => rfl
              | succ q => exact False.elim (Nat.not_lt_zero q.val q.isLt)
          | lam =>
              cases h
              refine Sigma.ext rfl ?_
              apply heq_of_eq
              funext q
              cases q using Fin.cases with
              | zero => rfl
              | succ q => exact False.elim (Nat.not_lt_zero q.val q.isLt)
          | app =>
              cases h

theorem NFNormalLayerShape_right_inv (Γ : List NFSort) :
    Function.RightInverse (NFNormalLayerOfShape Γ) (NFNormalLayerToShape Γ) := by
  intro shape
  cases shape with
  | inl v =>
      simp [NFNormalLayerToShape, NFNormalLayerOfShape, normalExpFinToVar_toFin]
  | inr rest =>
      cases rest with
      | inl e => rfl
      | inr body => rfl

def NFNormalLayerShapeIso (Γ : List NFSort) :
    CodeLayer NFPoly NFInversion NFCode (Γ, .normalExp) ≃ᵢ NFNormalLayerShape Γ where
  toFun := NFNormalLayerToShape Γ
  invFun := NFNormalLayerOfShape Γ
  left_inv := NFNormalLayerShape_left_inv Γ
  right_inv := NFNormalLayerShape_right_inv Γ

def NFAppTermLayerToShape (Γ : List NFSort) :
    CodeLayer NFPoly NFInversion NFCode (Γ, .appTerm) → NFAppTermLayerShape Γ
  | ⟨.var v, _child⟩ => Sum.inl (appTermVarToFin v)
  | ⟨.op .app h, child⟩ => by
      cases h
      exact Sum.inr (child ⟨0, by decide⟩, child ⟨1, by decide⟩)
  | ⟨.op .dum h, _child⟩ => by
      cases h
  | ⟨.op .lam h, _child⟩ => by
      cases h

def NFAppTermLayerOfShape (Γ : List NFSort) :
    NFAppTermLayerShape Γ → CodeLayer NFPoly NFInversion NFCode (Γ, .appTerm)
  | Sum.inl v => ⟨.var (appTermFinToVar v), fun q => nomatch q⟩
  | Sum.inr pair =>
      ⟨.op NFCtor.app rfl, fun
        | ⟨0, _⟩ => pair.1
        | ⟨1, _⟩ => pair.2
        | ⟨n + 2, h⟩ => by
            simp [NFSignature, NFArgs] at h
            omega⟩

theorem NFAppTermLayerShape_left_inv (Γ : List NFSort) :
    Function.LeftInverse (NFAppTermLayerOfShape Γ) (NFAppTermLayerToShape Γ) := by
  intro layer
  cases layer with
  | mk code child =>
      cases code with
      | var v =>
          have hchild : (fun q => nomatch q) = child := by
            funext q
            cases q
          cases hchild
          change NFAppTermLayerOfShape Γ (Sum.inl (appTermVarToFin v)) =
            ⟨FiberCode.var v, (fun q => nomatch q)⟩
          dsimp [NFAppTermLayerOfShape]
          rw [appTermVarToFin_toVar v]
          refine Sigma.ext rfl ?_
          apply heq_of_eq
          funext q
          cases q
      | op c h =>
          cases c with
          | dum =>
              cases h
          | lam =>
              cases h
          | app =>
              cases h
              refine Sigma.ext rfl ?_
              apply heq_of_eq
              funext q
              cases q using Fin.cases with
              | zero => rfl
              | succ q =>
                  cases q using Fin.cases with
                  | zero => rfl
                  | succ q => exact False.elim (Nat.not_lt_zero q.val q.isLt)

theorem NFAppTermLayerShape_right_inv (Γ : List NFSort) :
    Function.RightInverse (NFAppTermLayerOfShape Γ) (NFAppTermLayerToShape Γ) := by
  intro shape
  cases shape with
  | inl v =>
      simp [NFAppTermLayerToShape, NFAppTermLayerOfShape, appTermFinToVar_toFin]
  | inr pair =>
      cases pair
      rfl

def NFAppTermLayerShapeIso (Γ : List NFSort) :
    CodeLayer NFPoly NFInversion NFCode (Γ, .appTerm) ≃ᵢ NFAppTermLayerShape Γ where
  toFun := NFAppTermLayerToShape Γ
  invFun := NFAppTermLayerOfShape Γ
  left_inv := NFAppTermLayerShape_left_inv Γ
  right_inv := NFAppTermLayerShape_right_inv Γ

def NFNormalTailToNat (Γ : List NFSort) :
    NFCode (Γ, .appTerm) ⊕ Nat → Nat
  | Sum.inl app =>
      if h : 0 < appTermCount Γ then
        2 * (CodeAlgebra.finProdNat (appTermCount Γ) h).toFun app
      else
        False.elim (Nat.not_lt_zero app.1.val (by
          have hzero : appTermCount Γ = 0 := Nat.eq_zero_of_not_pos h
          simpa [hzero] using app.1.isLt))
  | Sum.inr body =>
      if appTermCount Γ = 0 then body else 2 * body + 1

def NFNormalTailOfNat (Γ : List NFSort) (n : Nat) :
    NFCode (Γ, .appTerm) ⊕ Nat :=
  if h : 0 < appTermCount Γ then
    if _hp : n % 2 = 0 then
      Sum.inl ((CodeAlgebra.finProdNat (appTermCount Γ) h).invFun (n / 2))
    else
      Sum.inr (n / 2)
  else
    Sum.inr n

theorem NFNormalTail_left_inv (Γ : List NFSort) :
    Function.LeftInverse (NFNormalTailOfNat Γ) (NFNormalTailToNat Γ) := by
  intro x
  cases x with
  | inl app =>
      dsimp [NFNormalTailToNat, NFNormalTailOfNat]
      by_cases h : 0 < appTermCount Γ
      · let code := (CodeAlgebra.finProdNat (appTermCount Γ) h).toFun app
        have hmod : (2 * code) % 2 = 0 := Nat.mul_mod_right 2 code
        have hdiv : (2 * code) / 2 = code :=
          Nat.mul_div_right code (by decide : 0 < 2)
        simp [h, hmod, hdiv, code]
      · exact False.elim (Nat.not_lt_zero app.1.val (by
          have hzero : appTermCount Γ = 0 := Nat.eq_zero_of_not_pos h
          simpa [hzero] using app.1.isLt))
  | inr body =>
      dsimp [NFNormalTailToNat, NFNormalTailOfNat]
      by_cases h : appTermCount Γ = 0
      · simp [h, Nat.lt_irrefl]
      · have hpos : 0 < appTermCount Γ := Nat.pos_of_ne_zero h
        have hmod : (2 * body + 1) % 2 ≠ 0 := by
          have hcalc : (2 * body + 1) % 2 = 1 := by
            calc
              (2 * body + 1) % 2 = (1 + 2 * body) % 2 := by rw [Nat.add_comm]
              _ = 1 % 2 := Nat.add_mul_mod_self_left 1 2 body
              _ = 1 := Nat.mod_eq_of_lt (by decide : 1 < 2)
          omega
        have hdiv : (2 * body + 1) / 2 = body := by
          calc
            (2 * body + 1) / 2 = (1 + body * 2) / 2 := by
              rw [Nat.add_comm, Nat.mul_comm 2 body]
            _ = 1 / 2 + body := Nat.add_mul_div_right 1 body (by decide : 0 < 2)
            _ = body := by
              rw [Nat.div_eq_of_lt (by decide : 1 < 2)]
              exact Nat.zero_add body
        simp [hpos, h, hdiv]

theorem NFNormalTail_right_inv (Γ : List NFSort) :
    Function.RightInverse (NFNormalTailOfNat Γ) (NFNormalTailToNat Γ) := by
  intro n
  dsimp [NFNormalTailToNat, NFNormalTailOfNat]
  by_cases h : 0 < appTermCount Γ
  · by_cases hp : n % 2 = 0
    · simp [h, hp]
      have hsplit := Nat.div_add_mod n 2
      omega
    · simp [h, hp]
      have hne : ¬appTermCount Γ = 0 := Nat.ne_of_gt h
      have hsplit := Nat.div_add_mod n 2
      rcases Nat.mod_two_eq_zero_or_one n with h0 | h1
      · exact False.elim (hp h0)
      · simp [hne]
        omega
  · have hzero : appTermCount Γ = 0 := Nat.eq_zero_of_not_pos h
    simp [hzero]

def NFNormalTailIso (Γ : List NFSort) :
    (NFCode (Γ, .appTerm) ⊕ Nat) ≃ᵢ Nat where
  toFun := NFNormalTailToNat Γ
  invFun := NFNormalTailOfNat Γ
  left_inv := NFNormalTail_left_inv Γ
  right_inv := NFNormalTail_right_inv Γ

def NFNormalLayerIso (Γ : List NFSort) :
    CodeLayer NFPoly NFInversion NFCode (Γ, .normalExp) ≃ᵢ Nat :=
  Iso.trans (NFNormalLayerShapeIso Γ)
    (Iso.trans (Iso.sum (Iso.refl (Fin (normalExpCount Γ))) (NFNormalTailIso Γ))
      (CodeAlgebra.finPlusNat (normalExpCount Γ)))

def NFAppTermShapeToCode (Γ : List NFSort) :
    NFAppTermLayerShape Γ → NFCode (Γ, .appTerm)
  | Sum.inl v => (v, 0)
  | Sum.inr pair =>
      (pair.1.1, CodeAlgebra.prodNat.toFun (pair.1.2, pair.2) + 1)

def NFAppTermCodeToShape (Γ : List NFSort) :
    NFCode (Γ, .appTerm) → NFAppTermLayerShape Γ
  | (tag, 0) => Sum.inl tag
  | (tag, n + 1) =>
      let p := CodeAlgebra.prodNat.invFun n
      Sum.inr ((tag, p.1), p.2)

theorem NFAppTermShape_left_inv (Γ : List NFSort) :
    Function.LeftInverse (NFAppTermCodeToShape Γ) (NFAppTermShapeToCode Γ) := by
  intro x
  cases x with
  | inl v => rfl
  | inr pair =>
      cases pair with
      | mk fn arg =>
        cases fn with
        | mk tag payload =>
          dsimp [NFAppTermShapeToCode, NFAppTermCodeToShape]
          rw [CodeAlgebra.prodNat.left_inv (payload, arg)]

theorem NFAppTermShape_right_inv (Γ : List NFSort) :
    Function.RightInverse (NFAppTermCodeToShape Γ) (NFAppTermShapeToCode Γ) := by
  intro code
  cases code with
  | mk tag n =>
    cases n with
    | zero => rfl
    | succ n =>
        dsimp [NFAppTermShapeToCode, NFAppTermCodeToShape]
        rw [CodeAlgebra.prodNat.right_inv n]

def NFAppTermShapeIso (Γ : List NFSort) :
    NFAppTermLayerShape Γ ≃ᵢ NFCode (Γ, .appTerm) where
  toFun := NFAppTermShapeToCode Γ
  invFun := NFAppTermCodeToShape Γ
  left_inv := NFAppTermShape_left_inv Γ
  right_inv := NFAppTermShape_right_inv Γ

def NFAppTermLayerIso (Γ : List NFSort) :
    CodeLayer NFPoly NFInversion NFCode (Γ, .appTerm) ≃ᵢ NFCode (Γ, .appTerm) :=
  Iso.trans (NFAppTermLayerShapeIso Γ) (NFAppTermShapeIso Γ)

def NFCodeLayerIso :
    ∀ i, CodeLayer NFPoly NFInversion NFCode i ≃ᵢ NFCode i
  | (Γ, .normalExp) => NFNormalLayerIso Γ
  | (Γ, .appTerm) => NFAppTermLayerIso Γ

theorem NFCode_layer_child_rank_lt :
    ∀ {i : Poly.Ix NFSignature}
      (layer : CodeLayer NFPoly NFInversion NFCode i)
      (q : NFPoly.Pos
          (NFInversion.decode i layer.1).ctor
          (NFInversion.decode i layer.1).param),
      NFCodeRank
          (NFPoly.input (NFInversion.decode i layer.1).param q)
          (layer.2 q) < NFCodeRank i ((NFCodeLayerIso i).toFun layer) := by
  intro i layer
  cases i with
  | mk Γ t =>
    cases t with
    | normalExp =>
        cases layer with
        | mk code child =>
          cases code with
          | var v =>
              intro q
              cases q
          | op c h =>
              cases c with
              | dum =>
                  cases h
                  intro q
                  cases q using Fin.cases with
                  | zero =>
                      let app : Fin (appTermCount Γ) × Nat := child ⟨0, by decide⟩
                      have hcount : 0 < appTermCount Γ :=
                        Nat.lt_of_le_of_lt (Nat.zero_le app.1.val) app.1.isLt
                      have hcne : ¬appTermCount Γ = 0 := Nat.ne_of_gt hcount
                      let payload :=
                        (CodeAlgebra.finProdNat (appTermCount Γ) hcount).toFun app
                      have hparent :
                          (NFCodeLayerIso (Γ, NFSort.normalExp)).toFun
                              ⟨FiberCode.op NFCtor.dum rfl, child⟩ =
                            normalExpCount Γ + 2 * payload := by
                        simp [app, payload, hcount, NFCodeLayerIso, NFNormalLayerIso,
                          NFNormalLayerShapeIso, NFNormalLayerToShape,
                          NFNormalTailIso, NFNormalTailToNat, Iso.trans, Iso.sum,
                          CodeAlgebra.finPlusNat]
                      change NFCodeRank (Γ, NFSort.appTerm) app <
                        NFCodeRank (Γ, NFSort.normalExp)
                          ((NFCodeLayerIso (Γ, NFSort.normalExp)).toFun
                            ⟨FiberCode.op NFCtor.dum rfl, child⟩)
                      rw [hparent]
                      simp [NFCodeRank, hcne]
                      have happ_le : app.2 ≤ payload := by
                        simpa [payload] using
                          CodeAlgebra.finProdNat_toFun_snd_le
                            (appTermCount Γ) hcount app
                      omega
                  | succ q => exact False.elim (Nat.not_lt_zero q.val q.isLt)
              | lam =>
                  cases h
                  intro q
                  cases q using Fin.cases with
                  | zero =>
                      let body : Nat := child ⟨0, by decide⟩
                      by_cases hc : appTermCount Γ = 0
                      · have hparent :
                            (NFCodeLayerIso (Γ, NFSort.normalExp)).toFun
                                ⟨FiberCode.op NFCtor.lam rfl, child⟩ =
                              normalExpCount Γ + body := by
                          simp [body, hc, NFCodeLayerIso, NFNormalLayerIso,
                            NFNormalLayerShapeIso, NFNormalLayerToShape,
                            NFNormalTailIso, NFNormalTailToNat, Iso.trans, Iso.sum,
                            CodeAlgebra.finPlusNat]
                        change NFCodeRank (NFSort.appTerm :: Γ, NFSort.normalExp) body <
                          NFCodeRank (Γ, NFSort.normalExp)
                            ((NFCodeLayerIso (Γ, NFSort.normalExp)).toFun
                              ⟨FiberCode.op NFCtor.lam rfl, child⟩)
                        rw [hparent]
                        simp [NFCodeRank, appTermCount, Var.count, hc]
                        omega
                      · have hpos : 0 < appTermCount Γ := Nat.pos_of_ne_zero hc
                        have hparent :
                            (NFCodeLayerIso (Γ, NFSort.normalExp)).toFun
                                ⟨FiberCode.op NFCtor.lam rfl, child⟩ =
                              normalExpCount Γ + (2 * body + 1) := by
                          simp [body, hpos, hc, NFCodeLayerIso, NFNormalLayerIso,
                            NFNormalLayerShapeIso, NFNormalLayerToShape,
                            NFNormalTailIso, NFNormalTailToNat, Iso.trans, Iso.sum,
                            CodeAlgebra.finPlusNat]
                        change NFCodeRank (NFSort.appTerm :: Γ, NFSort.normalExp) body <
                          NFCodeRank (Γ, NFSort.normalExp)
                            ((NFCodeLayerIso (Γ, NFSort.normalExp)).toFun
                              ⟨FiberCode.op NFCtor.lam rfl, child⟩)
                        rw [hparent]
                        simp [NFCodeRank, appTermCount, Var.count, hc]
                        omega
                  | succ q => exact False.elim (Nat.not_lt_zero q.val q.isLt)
              | app =>
                  cases h
    | appTerm =>
        cases layer with
        | mk code child =>
          cases code with
          | var v =>
              intro q
              cases q
          | op c h =>
              cases c with
              | dum =>
                  cases h
              | lam =>
                  cases h
              | app =>
                  cases h
                  intro q
                  let fn : Fin (appTermCount Γ) × Nat := child ⟨0, by decide⟩
                  let arg : Nat := child ⟨1, by decide⟩
                  have hcount : 0 < appTermCount Γ :=
                    Nat.lt_of_le_of_lt (Nat.zero_le fn.1.val) fn.1.isLt
                  have hcne : ¬appTermCount Γ = 0 := Nat.ne_of_gt hcount
                  let pairCode := CodeAlgebra.prodNat.toFun (fn.2, arg)
                  have hparent :
                      (NFCodeLayerIso (Γ, NFSort.appTerm)).toFun
                          ⟨FiberCode.op NFCtor.app rfl, child⟩ =
                        (fn.1, pairCode + 1) := by
                    simp [fn, arg, pairCode, NFCodeLayerIso, NFAppTermLayerIso,
                      NFAppTermLayerShapeIso, NFAppTermLayerToShape, NFAppTermShapeIso,
                      NFAppTermShapeToCode, Iso.trans]
                  cases q using Fin.cases with
                  | zero =>
                      change NFCodeRank (Γ, NFSort.appTerm) fn <
                        NFCodeRank (Γ, NFSort.appTerm)
                          ((NFCodeLayerIso (Γ, NFSort.appTerm)).toFun
                            ⟨FiberCode.op NFCtor.app rfl, child⟩)
                      rw [hparent]
                      simp [NFCodeRank]
                      have hfn_le : fn.2 ≤ pairCode := by
                        simpa [pairCode, CodeAlgebra.prodNat] using
                          CodeAlgebra.prodNat_fst_le
                            (CodeAlgebra.prodNat.toFun (fn.2, arg))
                      omega
                  | succ q =>
                      cases q using Fin.cases with
                      | zero =>
                          change NFCodeRank (Γ, NFSort.normalExp) arg <
                            NFCodeRank (Γ, NFSort.appTerm)
                              ((NFCodeLayerIso (Γ, NFSort.appTerm)).toFun
                                ⟨FiberCode.op NFCtor.app rfl, child⟩)
                          rw [hparent]
                          simp [NFCodeRank, hcne]
                          have harg_le : arg ≤ pairCode := by
                            simpa [pairCode, CodeAlgebra.prodNat] using
                              CodeAlgebra.prodNat_snd_le
                                (CodeAlgebra.prodNat.toFun (fn.2, arg))
                          omega
                      | succ q => exact False.elim (Nat.not_lt_zero q.val q.isLt)

def NFCodeCodingData : CodeCodingData NFSignature where
  Code := NFCode
  layer := NFCodeLayerIso
  rank := NFCodeRank
  layer_child_rank_lt := by
    intro i layer q
    exact NFCode_layer_child_rank_lt layer q

def NFSyntaxCodeIso (Γ : List NFSort) (t : NFSort) :
    NFTerm Γ t ≃ᵢ NFCode (Γ, t) :=
  NFCodeCodingData.syntaxCodeIso Γ t

def NormalExpNatIso (Γ : List NFSort) : NormalExp Γ ≃ᵢ Nat :=
  NFSyntaxCodeIso Γ .normalExp

def AppTermCodeIso (Γ : List NFSort) :
    AppTerm Γ ≃ᵢ (Fin (appTermCount Γ) × Nat) :=
  NFSyntaxCodeIso Γ .appTerm

def NFClosedNatIso : NFClosed ≃ᵢ Nat :=
  NormalExpNatIso []

end TypedBinding
end Examples
end BijForm
