import BijForm.StringDiagram.Polynomial
import BijForm.StringDiagram.Bridge

namespace BijForm
namespace StringDiagram
namespace SymmetricInteractionNet

open DepPoly

/-- Node labels for the standard symmetric interaction-net signature. -/
inductive Node where
  | dup
  | erase
  | cons
deriving DecidableEq, Repr

/-- All wires in the untyped symmetric interaction-net signature share one type. -/
abbrev Wire : Type := Unit

/-- Ordered arity of each symmetric interaction-net node. -/
def arity : Node → Nat
  | .dup => 3
  | .erase => 1
  | .cons => 3

/-- Every port in the untyped signature carries the unique wire type. -/
def port (_node : Node) (_slot : Fin (arity _node)) : Wire :=
  ()

/-- The standard untyped symmetric interaction-net string-diagram signature. -/
def signature : Signature :=
  Unoriented.signature Wire Node arity port

/-- Ordered-frontier symmetric interaction-net traversal syntax. -/
abbrev Diag (boundary : List signature.Port) : Type :=
  StringDiagram.Diag signature boundary

/-- Dependent polynomial generated by the symmetric interaction-net signature. -/
abbrev poly : DepPoly (List signature.Port) :=
  BijForm.StringDiagram.poly signature

/-- Generated coding data for symmetric interaction-net diagrams. -/
abbrev generatedCode : GeneratedCode poly
    (fun boundary => StringDiagram.Diag signature boundary) :=
  BijForm.StringDiagram.generatedCode signature

/-- Generated-code equivalence for symmetric interaction-net diagrams. -/
abbrev syntaxIso (boundary : List signature.Port) :
    Mu poly boundary ≃ᵢ Diag boundary :=
  BijForm.StringDiagram.syntaxIso signature boundary

/-- Canonical traversal-code representation of symmetric interaction nets. -/
abbrev CanonicalCode (boundary : List signature.Port) : Type :=
  Diag boundary

/-- Semantic open port-hypergraphs over the symmetric interaction-net signature. -/
abbrev OpenGraph (boundary : List signature.Port) : Type :=
  OpenPortHypergraph signature boundary

/-- Semantic open port-hypergraphs up to ordered-boundary-preserving isomorphism. -/
abbrev OpenGraphCode (boundary : List signature.Port) : Type :=
  OpenPortHypergraphUpToIso signature boundary

/-- Encoding of symmetric interaction-net diagrams by semantic open graphs. -/
abbrev openGraphIso (boundary : List signature.Port) :
    Diag boundary ≃ᵢ OpenGraphCode boundary :=
  diagOpenPortHypergraphIso signature boundary

/-- Canonical encoding of symmetric interaction nets up to isomorphism. -/
abbrev encoding (boundary : List signature.Port) :
    OpenGraphCode boundary ≃ᵢ CanonicalCode boundary :=
  Iso.symm (openGraphIso boundary)

/-- Encode a semantic symmetric interaction net as its canonical traversal code. -/
abbrev encode {boundary : List signature.Port}
    (G : OpenGraphCode boundary) : CanonicalCode boundary :=
  (encoding boundary).toFun G

/-- Decode a canonical traversal code to its semantic graph quotient. -/
abbrev decode {boundary : List signature.Port}
    (c : CanonicalCode boundary) : OpenGraphCode boundary :=
  (encoding boundary).invFun c

end SymmetricInteractionNet
end StringDiagram
end BijForm
