import BijForm.Coding

namespace BijForm

/-
This file starts the general formalization for the dependent Gödel-encoding
post.  The key design choice is to make the useful condition explicit rather
than hide the hard part behind an opaque constructor isomorphism:

* constructors are presented as dependent polynomial containers over an index
  type `ι`;
* a constructor may compute its output index by a map `out`;
* `OutputIndexInversion` supplies, for each target index, a fiberwise inverse
  description of the parameters whose `out` lands there.

This is the formal counterpart of the "Trees of Bounded Height" refactoring:
move an invertible output-index change into an explicit same-fiber precondition.
-/

universe u

/-- A dependent polynomial signature whose recursive positions may point at
indices computed from the constructor parameter. -/
structure DepPoly (ι : Type u) where
  Ctor : Type u
  Param : Ctor → Type u
  out : (c : Ctor) → Param c → ι
  Pos : (c : Ctor) → Param c → Type u
  input : {c : Ctor} → (p : Param c) → Pos c p → ι

namespace DepPoly

variable {ι : Type u}

/-- One layer of constructor data over a family `X`. -/
structure Obj (P : DepPoly ι) (X : ι → Type u) (i : ι) where
  ctor : P.Ctor
  param : P.Param ctor
  out_eq : P.out ctor param = i
  child : (q : P.Pos ctor param) → X (P.input param q)

/-- A same-fiber polynomial presentation: constructors for index `i` already
include the evidence that their output is `i`. -/
structure Fiber (P : DepPoly ι) (i : ι) where
  ctor : P.Ctor
  param : P.Param ctor
  out_eq : P.out ctor param = i

def FiberObj (P : DepPoly ι) (X : ι → Type u) (i : ι) : Type u :=
  Σ f : Fiber P i, (q : P.Pos f.ctor f.param) → X (P.input f.param q)

def objFiberIso (P : DepPoly ι) (X : ι → Type u) (i : ι) :
    Obj P X i ≃ᵢ FiberObj P X i where
  toFun x :=
    ⟨⟨x.ctor, x.param, x.out_eq⟩, x.child⟩
  invFun x :=
    ⟨x.1.ctor, x.1.param, x.1.out_eq, x.2⟩
  left_inv := by
    intro x
    cases x
    rfl
  right_inv := by
    intro x
    cases x with
    | mk f rec =>
      cases f
      rfl

/--
The useful condition missing from a bare "assume constructors are isomorphic"
answer.  For every target index, the constructor parameters landing in that
index can be described by an index-local code.  This is exactly where examples
like bounded-height trees invert `n + 1` into the same-fiber premise
`∃ m, n = m + 1`.
-/
structure OutputIndexInversion (P : DepPoly ι) where
  Code : ι → Type u
  decode : (i : ι) → Code i → Fiber P i
  encode : (i : ι) → Fiber P i → Code i
  decode_encode : ∀ i f, decode i (encode i f) = f
  encode_decode : ∀ i c, encode i (decode i c) = c

namespace OutputIndexInversion

def fiberIso {P : DepPoly ι} (H : OutputIndexInversion P) (i : ι) :
    H.Code i ≃ᵢ Fiber P i where
  toFun := H.decode i
  invFun := H.encode i
  left_inv := H.encode_decode i
  right_inv := H.decode_encode i

end OutputIndexInversion

/-- The initial algebra generated by a dependent polynomial. -/
inductive Mu (P : DepPoly ι) : ι → Type u
  | sup {i : ι}
      (c : P.Ctor)
      (p : P.Param c)
      (h : P.out c p = i)
      (child : (q : P.Pos c p) → Mu P (P.input p q)) : Mu P i

def Mu.out {P : DepPoly ι} {i : ι} : Mu P i → Obj P (Mu P) i
  | Mu.sup c p h child => ⟨c, p, h, child⟩

def Mu.inn {P : DepPoly ι} {i : ι} (x : Obj P (Mu P) i) : Mu P i :=
  Mu.sup x.ctor x.param x.out_eq x.child

theorem Mu_out_inn {P : DepPoly ι} {i : ι} (x : Obj P (Mu P) i) :
    Mu.out (Mu.inn x) = x := by
  cases x
  rfl

theorem Mu_inn_out {P : DepPoly ι} {i : ι} (x : Mu P i) :
    Mu.inn (P := P) (Mu.out x) = x := by
  cases x
  rfl

/--
The general coding theorem in its honest boundary form.  Given an output-index
inversion and a family of one-step codings for the index-local constructor
codes paired with recursively coded children, the initial algebra inherits a
fiberwise coding.

This theorem is the reusable hylomorphism result targeted by the Gödel-encoding
post.  The remaining proof work is to implement the recursion principle with
the chosen `CodeNat` family and prove the catamorphism/anamorphism equations in
Lean.
-/
def initialAlgebraCoding
    (P : DepPoly ι)
    (H : OutputIndexInversion P)
    (CodeNat : ι → Type u)
    (step : ∀ i,
      (Σ c : H.Code i,
        (q : P.Pos (H.decode i c).ctor (H.decode i c).param) →
          CodeNat (P.input (H.decode i c).param q)) ≃ᵢ CodeNat i)
    : (∀ i, Mu P i ≃ᵢ CodeNat i) := by
  -- Pending proof work, tracked by BF-POLY-001: define the mutually inverse
  -- fold/unfold generated by `step` and prove the equations by structural
  -- recursion on `Mu`.
  sorry

end DepPoly

end BijForm
