import BijForm.Coding

namespace BijForm

/-
This file develops the dependent-polynomial layer used by the coding
framework. The key design requirement is to make constructor-fiber data
explicit rather than hide the hard part behind an opaque constructor
isomorphism:

* constructors are presented as dependent polynomial containers over an index
  type `ι`;
* a constructor may compute its output index by a map `out`;
* `OutputIndexInversion` supplies, for each target index, a fiberwise inverse
  description of the parameters whose `out` lands there.

Output-index inversion is represented as same-fiber constructor data; examples
must still show how this data is generated from their concrete constructors.
-/

universe u v w

/-- A dependent polynomial signature whose recursive positions may point at
indices computed from the constructor parameter. -/
structure DepPoly (ι : Type u) where
  Ctor : Type u
  Param : Ctor → Type u
  out : (c : Ctor) → Param c → ι
  Pos : (c : Ctor) → Param c → Type u
  input : {c : Ctor} → (p : Param c) → Pos c p → ι

namespace DepPoly

variable {ι : Type u}

/-- One layer of constructor data over a family `X`. -/
structure Obj (P : DepPoly ι) (X : ι → Type v) (i : ι) where
  ctor : P.Ctor
  param : P.Param ctor
  out_eq : P.out ctor param = i
  child : (q : P.Pos ctor param) → X (P.input param q)

/-- A same-fiber polynomial presentation: constructors for index `i` already
include the evidence that their output is `i`. -/
structure Fiber (P : DepPoly ι) (i : ι) where
  ctor : P.Ctor
  param : P.Param ctor
  out_eq : P.out ctor param = i

def FiberObj (P : DepPoly ι) (X : ι → Type v) (i : ι) : Type (max u v) :=
  Σ f : Fiber P i, (q : P.Pos f.ctor f.param) → X (P.input f.param q)

def objFiberIso (P : DepPoly ι) (X : ι → Type v) (i : ι) :
    Obj P X i ≃ᵢ FiberObj P X i where
  toFun x :=
    ⟨⟨x.ctor, x.param, x.out_eq⟩, x.child⟩
  invFun x :=
    ⟨x.1.ctor, x.1.param, x.1.out_eq, x.2⟩
  left_inv := by
    intro x
    cases x
    rfl
  right_inv := by
    intro x
    cases x with
    | mk f rec =>
      cases f
      rfl

/--
Index-local constructor data for each output fiber. This structure records the
same-fiber representation used by later layer-coding definitions; by itself it
is not a completed solution to constructor-code generation.
-/
structure OutputIndexInversion (P : DepPoly ι) where
  Code : ι → Type u
  decode : (i : ι) → Code i → Fiber P i
  encode : (i : ι) → Fiber P i → Code i
  decode_encode : ∀ i f, decode i (encode i f) = f
  encode_decode : ∀ i c, encode i (decode i c) = c

namespace OutputIndexInversion

/-- The canonical same-fiber inversion: the code for each output index is the
fiber itself.  This is the generated default when no smaller constructor-code
presentation is needed. -/
def canonical (P : DepPoly ι) : OutputIndexInversion P where
  Code := Fiber P
  decode := fun _ f => f
  encode := fun _ f => f
  decode_encode := by
    intro _ _
    rfl
  encode_decode := by
    intro _ _
    rfl

/-- Build an output-index inversion from an explicit isomorphism between a
chosen code family and the same-fiber constructor data. -/
def ofIso {P : DepPoly ι} (Code : ι → Type u)
    (e : ∀ i, Code i ≃ᵢ Fiber P i) : OutputIndexInversion P where
  Code := Code
  decode := fun i c => (e i).toFun c
  encode := fun i f => (e i).invFun f
  decode_encode := by
    intro i f
    exact (e i).right_inv f
  encode_decode := by
    intro i c
    exact (e i).left_inv c

def fiberIso {P : DepPoly ι} (H : OutputIndexInversion P) (i : ι) :
    H.Code i ≃ᵢ Fiber P i where
  toFun := H.decode i
  invFun := H.encode i
  left_inv := H.encode_decode i
  right_inv := H.decode_encode i

end OutputIndexInversion

/-- The initial algebra generated by a dependent polynomial. -/
inductive Mu (P : DepPoly ι) : ι → Type u
  | sup {i : ι}
      (c : P.Ctor)
      (p : P.Param c)
      (h : P.out c p = i)
      (child : (q : P.Pos c p) → Mu P (P.input p q)) : Mu P i

def Mu.out {P : DepPoly ι} {i : ι} : Mu P i → Obj P (Mu P) i
  | Mu.sup c p h child => ⟨c, p, h, child⟩

def Mu.inn {P : DepPoly ι} {i : ι} (x : Obj P (Mu P) i) : Mu P i :=
  Mu.sup x.ctor x.param x.out_eq x.child

theorem Mu_out_inn {P : DepPoly ι} {i : ι} (x : Obj P (Mu P) i) :
    Mu.out (Mu.inn x) = x := by
  cases x
  rfl

theorem Mu_inn_out {P : DepPoly ι} {i : ι} (x : Mu P i) :
    Mu.inn (P := P) (Mu.out x) = x := by
  cases x
  rfl

def Layer (P : DepPoly ι) (Code : ι → Type v) (i : ι) : Type (max u v) :=
  Σ f : Fiber P i, (q : P.Pos f.ctor f.param) → Code (P.input f.param q)

def CodeLayer (P : DepPoly ι) (H : OutputIndexInversion P)
    (Code : ι → Type v) (i : ι) : Type (max u v) :=
  Σ c : H.Code i,
    (q : P.Pos (H.decode i c).ctor (H.decode i c).param) →
      Code (P.input (H.decode i c).param q)

/-- Prove child-function eta facts for constructors with no recursive positions. -/
syntax "child_eta_empty" : tactic
macro_rules
  | `(tactic| child_eta_empty) =>
      `(tactic| first | (funext q; cases q) | (symm; funext q; cases q))

/-- Prove child-function eta facts for constructors with one recursive position. -/
syntax "child_eta_unit" : tactic
macro_rules
  | `(tactic| child_eta_unit) =>
      `(tactic| first | (funext q; cases q; rfl) | (symm; funext q; cases q; rfl))

/-- Prove child-function eta facts for constructors with boolean recursive positions. -/
syntax "child_eta_bool" : tactic
macro_rules
  | `(tactic| child_eta_bool) =>
      `(tactic| first | (funext q; cases q <;> rfl) | (symm; funext q; cases q <;> rfl))

def castFiberChild {P : DepPoly ι} {Code : ι → Type v} {i : ι}
    {f g : Fiber P i} (h : f = g)
    (child : (q : P.Pos f.ctor f.param) → Code (P.input f.param q)) :
    (q : P.Pos g.ctor g.param) → Code (P.input g.param q) := by
  cases h
  exact child

theorem castFiberChild_heq {P : DepPoly ι} {Code : ι → Type v} {i : ι}
    {f g : Fiber P i} (h : f = g)
    (child : (q : P.Pos f.ctor f.param) → Code (P.input f.param q)) :
    castFiberChild h child ≍ child := by
  cases h
  rfl

def fiberObjCodeLayerTo {P : DepPoly ι} {Code : ι → Type v} {i : ι}
    (H : OutputIndexInversion P) (x : FiberObj P Code i) :
    CodeLayer P H Code i := by
  cases x with
  | mk f child =>
      exact ⟨H.encode i f, castFiberChild (H.decode_encode i f).symm child⟩

def fiberObjCodeLayerInv {P : DepPoly ι} {Code : ι → Type v} {i : ι}
    (H : OutputIndexInversion P) (x : CodeLayer P H Code i) :
    FiberObj P Code i :=
  ⟨H.decode i x.1, x.2⟩

def fiberObjCodeLayerIso {P : DepPoly ι} (H : OutputIndexInversion P)
    (Code : ι → Type v) (i : ι) :
    FiberObj P Code i ≃ᵢ CodeLayer P H Code i where
  toFun := fiberObjCodeLayerTo H
  invFun := fiberObjCodeLayerInv H
  left_inv := by
    intro x
    cases x with
    | mk f child =>
        dsimp [fiberObjCodeLayerTo, fiberObjCodeLayerInv]
        refine Sigma.ext (H.decode_encode i f) ?_
        exact castFiberChild_heq (H.decode_encode i f).symm child
  right_inv := by
    intro x
    cases x with
    | mk c child =>
        dsimp [fiberObjCodeLayerTo, fiberObjCodeLayerInv]
        refine Sigma.ext (H.encode_decode i c) ?_
        exact castFiberChild_heq (H.decode_encode i (H.decode i c)).symm child

def objCodeLayerIso {P : DepPoly ι} (H : OutputIndexInversion P)
    (Code : ι → Type v) (i : ι) :
    Obj P Code i ≃ᵢ CodeLayer P H Code i :=
  Iso.trans (objFiberIso P Code i) (fiberObjCodeLayerIso H Code i)

/--
The corrected condition for automatic codings.  Besides the one-step
isomorphism, decoding must be well-founded: every recursive child code produced
by one-step decoding has smaller rank than the code being decoded.
-/
structure WellFoundedCode
    (P : DepPoly ι)
    (Code : ι → Type v) where
  step : ∀ i, Obj P Code i ≃ᵢ Code i
  rank : ∀ i, Code i → Nat
  child_rank_lt :
    ∀ {i : ι} (z : Code i)
      (q : P.Pos ((step i).invFun z).ctor ((step i).invFun z).param),
      rank (P.input ((step i).invFun z).param q)
          (((step i).invFun z).child q) < rank i z

namespace WellFoundedCode

variable {P : DepPoly ι} {Code : ι → Type v}

def encode (C : WellFoundedCode P Code) : ∀ i, Mu P i → Code i
  | i, Mu.sup c p h child =>
      (C.step i).toFun
        ⟨c, p, h, fun q => encode C (P.input p q) (child q)⟩

def decode (C : WellFoundedCode P Code) : ∀ i, Code i → Mu P i
  | i, z =>
      let layer := (C.step i).invFun z
      Mu.sup layer.ctor layer.param layer.out_eq
        (fun q => decode C (P.input layer.param q) (layer.child q))
termination_by i z => C.rank i z
decreasing_by
  exact C.child_rank_lt z q

theorem decode_encode (C : WellFoundedCode P Code) :
    ∀ i (x : Mu P i), decode C i (encode C i x) = x
  | i, Mu.sup c p h child => by
      let layer : Obj P Code i :=
        ⟨c, p, h, fun q => encode C (P.input p q) (child q)⟩
      have hleft : (C.step i).invFun ((C.step i).toFun layer) = layer :=
        (C.step i).left_inv layer
      have ih :
          (fun q => decode C (P.input p q) (encode C (P.input p q) (child q)))
            = child := by
        funext q
        exact decode_encode C (P.input p q) (child q)
      change decode C i ((C.step i).toFun layer) = Mu.sup c p h child
      rw [decode]
      rw [hleft]
      simp [layer, ih]

theorem encode_decode (C : WellFoundedCode P Code) :
    ∀ i (z : Code i), encode C i (decode C i z) = z
  | i, z => by
      let layer := (C.step i).invFun z
      have ih :
          (fun q => encode C (P.input layer.param q)
            (decode C (P.input layer.param q) (layer.child q)))
            = layer.child := by
        funext q
        exact encode_decode C (P.input layer.param q) (layer.child q)
      have hstep : (C.step i).toFun layer = z := (C.step i).right_inv z
      rw [decode]
      rw [encode]
      change (C.step i).toFun
          ⟨layer.ctor, layer.param, layer.out_eq, fun q =>
            encode C (P.input layer.param q)
              (decode C (P.input layer.param q) (layer.child q))⟩ = z
      rw [ih]
      exact hstep
termination_by i z => C.rank i z
decreasing_by
  exact C.child_rank_lt z q

def iso (C : WellFoundedCode P Code) (i : ι) : Mu P i ≃ᵢ Code i where
  toFun := encode C i
  invFun := decode C i
  left_inv := decode_encode C i
  right_inv := encode_decode C i

end WellFoundedCode

/--
Generated coding data. The caller supplies an output-index inversion, a coding
of the resulting local layer into a carrier family, and a well-founded rank on
that carrier family. The full `Obj P Code i ≃ᵢ Code i` step is generated by
composing with `objCodeLayerIso`.
-/
structure GeneratedCode
    (P : DepPoly ι)
    (Code : ι → Type v) where
  inversion : OutputIndexInversion P
  layer : ∀ i, CodeLayer P inversion Code i ≃ᵢ Code i
  rank : ∀ i, Code i → Nat
  child_rank_lt :
    ∀ {i : ι} (z : Code i)
      (q : P.Pos (inversion.decode i ((layer i).invFun z).1).ctor
          (inversion.decode i ((layer i).invFun z).1).param),
      rank (P.input (inversion.decode i ((layer i).invFun z).1).param q)
          (((layer i).invFun z).2 q) < rank i z

namespace GeneratedCode

variable {P : DepPoly ι} {Code : ι → Type v}

/-- Build generated coding data from the natural layer-local descent proof.
Callers prove that every child in a decoded one-step layer has smaller rank
than the layer after re-encoding; this constructor supplies the equivalent
encoded-parent proof required by `GeneratedCode`. -/
def ofLayerChildRank
    (inversion : OutputIndexInversion P)
    (layer : ∀ i, CodeLayer P inversion Code i ≃ᵢ Code i)
    (rank : ∀ i, Code i → Nat)
    (layer_child_rank_lt :
      ∀ {i : ι} (x : CodeLayer P inversion Code i)
        (q : P.Pos (inversion.decode i x.1).ctor
            (inversion.decode i x.1).param),
        rank (P.input (inversion.decode i x.1).param q) (x.2 q) <
          rank i ((layer i).toFun x)) :
    GeneratedCode P Code where
  inversion := inversion
  layer := layer
  rank := rank
  child_rank_lt := by
    intro i z q
    simpa using layer_child_rank_lt ((layer i).invFun z) q

def step (C : GeneratedCode P Code) (i : ι) :
    Obj P Code i ≃ᵢ Code i :=
  Iso.trans (objCodeLayerIso C.inversion Code i) (C.layer i)

def toWellFoundedCode (C : GeneratedCode P Code) :
    WellFoundedCode P Code where
  step := C.step
  rank := C.rank
  child_rank_lt := by
    intro i z q
    simpa [step, objCodeLayerIso, Iso.trans, fiberObjCodeLayerIso,
      fiberObjCodeLayerInv, objFiberIso] using C.child_rank_lt z q

def iso (C : GeneratedCode P Code) (i : ι) : Mu P i ≃ᵢ Code i :=
  C.toWellFoundedCode.iso i

end GeneratedCode

inductive CodeShape where
  | finite (k : Nat)
  | infinite

namespace CodeShape

def Carrier : CodeShape → Type
  | finite k => Fin k
  | infinite => Nat

def rank : (s : CodeShape) → Carrier s → Nat
  | finite _, _ => 0
  | infinite, n => n

/-- If a code shape is infinite, its carrier is canonically `Nat`. -/
def infiniteIso {s : CodeShape} (h : s = infinite) : Carrier s ≃ᵢ Nat := by
  cases h
  exact Iso.refl Nat

/-- If a code shape is finite of size `k`, its carrier is canonically
`Fin k`. -/
def finiteIso {s : CodeShape} {k : Nat} (h : s = finite k) :
    Carrier s ≃ᵢ Fin k := by
  cases h
  exact Iso.refl (Fin k)

end CodeShape

/--
Generated coding data for index-dependent finite/infinite carrier families.
This is a thin specialization of `GeneratedCode` that makes the intended
carrier shape explicit: each index may be coded either by `Fin k` or by `Nat`.
-/
structure GeneratedShapeCode (P : DepPoly ι) where
  shape : ι → CodeShape
  inversion : OutputIndexInversion P
  layer : ∀ i,
    CodeLayer P inversion (fun j => (shape j).Carrier) i ≃ᵢ (shape i).Carrier
  rank : ∀ i, (shape i).Carrier → Nat
  child_rank_lt :
    ∀ {i : ι} (z : (shape i).Carrier)
      (q : P.Pos (inversion.decode i ((layer i).invFun z).1).ctor
          (inversion.decode i ((layer i).invFun z).1).param),
      rank (P.input (inversion.decode i ((layer i).invFun z).1).param q)
          (((layer i).invFun z).2 q) < rank i z

namespace GeneratedShapeCode

variable {P : DepPoly ι}

/-- Layer-local constructor for shape-coded generated data. -/
def ofLayerChildRank
    (shape : ι → CodeShape)
    (inversion : OutputIndexInversion P)
    (layer : ∀ i,
      CodeLayer P inversion (fun j => (shape j).Carrier) i ≃ᵢ
        (shape i).Carrier)
    (rank : ∀ i, (shape i).Carrier → Nat)
    (layer_child_rank_lt :
      ∀ {i : ι} (x : CodeLayer P inversion (fun j => (shape j).Carrier) i)
        (q : P.Pos (inversion.decode i x.1).ctor
            (inversion.decode i x.1).param),
        rank (P.input (inversion.decode i x.1).param q) (x.2 q) <
          rank i ((layer i).toFun x)) :
    GeneratedShapeCode P where
  shape := shape
  inversion := inversion
  layer := layer
  rank := rank
  child_rank_lt := by
    intro i z q
    simpa using layer_child_rank_lt ((layer i).invFun z) q

def toGeneratedCode (C : GeneratedShapeCode P) :
    GeneratedCode P (fun i => (C.shape i).Carrier) where
  inversion := C.inversion
  layer := C.layer
  rank := C.rank
  child_rank_lt := by
    intro i z q
    exact C.child_rank_lt z q

def toWellFoundedCode (C : GeneratedShapeCode P) :
    WellFoundedCode P (fun i => (C.shape i).Carrier) :=
  C.toGeneratedCode.toWellFoundedCode

def iso (C : GeneratedShapeCode P) (i : ι) :
    Mu P i ≃ᵢ (C.shape i).Carrier :=
  C.toGeneratedCode.iso i

def natIso (C : GeneratedShapeCode P) (i : ι)
    (h : C.shape i = .infinite) : Mu P i ≃ᵢ Nat :=
  Iso.trans (C.iso i) (CodeShape.infiniteIso h)

def finIso (C : GeneratedShapeCode P) (i : ι) {k : Nat}
    (h : C.shape i = .finite k) : Mu P i ≃ᵢ Fin k :=
  Iso.trans (C.iso i) (CodeShape.finiteIso h)

end GeneratedShapeCode

/--
Generated Nat coding data with a caller-supplied well-founded rank. This covers
Nat-carrier examples whose decoder decreases because the index changes, even
when a recursive child has the same numeric code as its parent.
-/
structure GeneratedRankedNatCode (P : DepPoly ι) where
  inversion : OutputIndexInversion P
  layer : ∀ i, CodeLayer P inversion (fun _ => Nat) i ≃ᵢ Nat
  rank : ι → Nat → Nat
  child_rank_lt :
    ∀ {i : ι} (n : Nat)
      (q : P.Pos (inversion.decode i ((layer i).invFun n).1).ctor
          (inversion.decode i ((layer i).invFun n).1).param),
      rank (P.input (inversion.decode i ((layer i).invFun n).1).param q)
          (((layer i).invFun n).2 q) < rank i n

namespace GeneratedRankedNatCode

variable {P : DepPoly ι}

/-- Layer-local constructor for ranked Nat generated data. -/
def ofLayerChildRank
    (inversion : OutputIndexInversion P)
    (layer : ∀ i, CodeLayer P inversion (fun _ => Nat) i ≃ᵢ Nat)
    (rank : ι → Nat → Nat)
    (layer_child_rank_lt :
      ∀ {i : ι} (x : CodeLayer P inversion (fun _ => Nat) i)
        (q : P.Pos (inversion.decode i x.1).ctor
            (inversion.decode i x.1).param),
        rank (P.input (inversion.decode i x.1).param q) (x.2 q) <
          rank i ((layer i).toFun x)) :
    GeneratedRankedNatCode P where
  inversion := inversion
  layer := layer
  rank := rank
  child_rank_lt := by
    intro i n q
    simpa using layer_child_rank_lt ((layer i).invFun n) q

def toGeneratedCode (C : GeneratedRankedNatCode P) :
    GeneratedCode P (fun _ => Nat) where
  inversion := C.inversion
  layer := C.layer
  rank := C.rank
  child_rank_lt := by
    intro i n q
    exact C.child_rank_lt n q

def toWellFoundedCode (C : GeneratedRankedNatCode P) :
    WellFoundedCode P (fun _ => Nat) :=
  C.toGeneratedCode.toWellFoundedCode

def iso (C : GeneratedRankedNatCode P) (i : ι) : Mu P i ≃ᵢ Nat :=
  C.toGeneratedCode.iso i

end GeneratedRankedNatCode

/--
Generated Nat coding data.  A local Nat layer decoder must produce recursive
child codes that are strictly smaller than the parent code, so the generic
decoder is well-founded with the identity rank on `Nat`.
-/
structure GeneratedNatCode (P : DepPoly ι) where
  inversion : OutputIndexInversion P
  layer : ∀ i, CodeLayer P inversion (fun _ => Nat) i ≃ᵢ Nat
  child_lt :
    ∀ {i : ι} (n : Nat)
      (q : P.Pos (inversion.decode i ((layer i).invFun n).1).ctor
          (inversion.decode i ((layer i).invFun n).1).param),
      (((layer i).invFun n).2 q) < n

namespace GeneratedNatCode

variable {P : DepPoly ι}

/-- Layer-local constructor for Nat generated data with identity rank. -/
def ofLayerChildLt
    (inversion : OutputIndexInversion P)
    (layer : ∀ i, CodeLayer P inversion (fun _ => Nat) i ≃ᵢ Nat)
    (layer_child_lt :
      ∀ {i : ι} (x : CodeLayer P inversion (fun _ => Nat) i)
        (q : P.Pos (inversion.decode i x.1).ctor
            (inversion.decode i x.1).param),
        x.2 q < (layer i).toFun x) :
    GeneratedNatCode P where
  inversion := inversion
  layer := layer
  child_lt := by
    intro i n q
    simpa using layer_child_lt ((layer i).invFun n) q

def toGeneratedCode (C : GeneratedNatCode P) :
    GeneratedCode P (fun _ => Nat) where
  inversion := C.inversion
  layer := C.layer
  rank := fun _ n => n
  child_rank_lt := by
    intro i n q
    exact C.child_lt n q

def toWellFoundedCode (C : GeneratedNatCode P) :
    WellFoundedCode P (fun _ => Nat) :=
  C.toGeneratedCode.toWellFoundedCode

def iso (C : GeneratedNatCode P) (i : ι) : Mu P i ≃ᵢ Nat :=
  C.toGeneratedCode.iso i

theorem noSubsingletonFiber (C : GeneratedNatCode P) (i : ι)
    [Subsingleton (Mu P i)] : False := by
  exact Iso.noNatIsoOfSubsingleton (C.iso i)

end GeneratedNatCode

namespace GeneratedCode

variable {P : DepPoly ι}

/-- Compose two generated codings of the same dependent polynomial through the
shared initial algebra.  This is the generic route from readable syntax to a
generated carrier code. -/
def codeIso {Source : ι → Type v} {Target : ι → Type w}
    (source : GeneratedCode P Source) (target : GeneratedCode P Target) (i : ι) :
    Source i ≃ᵢ Target i :=
  Iso.trans (Iso.symm (source.iso i)) (target.iso i)

/-- Compose a generated source coding with a generated Nat coding. -/
def natCodeIso {Source : ι → Type v}
    (source : GeneratedCode P Source) (target : GeneratedNatCode P) (i : ι) :
    Source i ≃ᵢ Nat :=
  codeIso source target.toGeneratedCode i

/-- Compose a generated source coding with a generated ranked-Nat coding. -/
def rankedNatCodeIso {Source : ι → Type v}
    (source : GeneratedCode P Source) (target : GeneratedRankedNatCode P) (i : ι) :
    Source i ≃ᵢ Nat :=
  codeIso source target.toGeneratedCode i

/-- Compose a generated source coding with a generated shape-coded carrier. -/
def shapeCodeIso {Source : ι → Type v}
    (source : GeneratedCode P Source) (target : GeneratedShapeCode P) (i : ι) :
    Source i ≃ᵢ (target.shape i).Carrier :=
  codeIso source target.toGeneratedCode i

/-- Compose a generated source coding with an infinite generated shape case. -/
def shapeNatIso {Source : ι → Type v}
    (source : GeneratedCode P Source) (target : GeneratedShapeCode P) (i : ι)
    (h : target.shape i = .infinite) : Source i ≃ᵢ Nat :=
  Iso.trans (shapeCodeIso source target i) (CodeShape.infiniteIso h)

/-- Compose a generated source coding with a finite generated shape case. -/
def shapeFinIso {Source : ι → Type v}
    (source : GeneratedCode P Source) (target : GeneratedShapeCode P) (i : ι)
    {k : Nat} (h : target.shape i = .finite k) : Source i ≃ᵢ Fin k :=
  Iso.trans (shapeCodeIso source target i) (CodeShape.finiteIso h)

end GeneratedCode

/-- Declarative presentation of a one-step `CodeLayer` as a carrier family.
This owns the generic construction of the layer isomorphism; examples supply
only the two directions and inverse proofs for their domain-specific shape. -/
structure CodeLayerPresentation
    (P : DepPoly ι)
    (H : OutputIndexInversion P)
    (Code : ι → Type v)
    (Carrier : ι → Type w) where
  toCarrier : ∀ i, CodeLayer P H Code i → Carrier i
  fromCarrier : ∀ i, Carrier i → CodeLayer P H Code i
  left_inv : ∀ i, Function.LeftInverse (fromCarrier i) (toCarrier i)
  right_inv : ∀ i, Function.RightInverse (fromCarrier i) (toCarrier i)

namespace CodeLayerPresentation

variable {P : DepPoly ι} {H : OutputIndexInversion P}
variable {Code : ι → Type v} {Carrier : ι → Type w}

def iso (D : CodeLayerPresentation P H Code Carrier) (i : ι) :
    CodeLayer P H Code i ≃ᵢ Carrier i where
  toFun := D.toCarrier i
  invFun := D.fromCarrier i
  left_inv := D.left_inv i
  right_inv := D.right_inv i

def ofIso (layer : ∀ i, CodeLayer P H Code i ≃ᵢ Carrier i) :
    CodeLayerPresentation P H Code Carrier where
  toCarrier := fun i => (layer i).toFun
  fromCarrier := fun i => (layer i).invFun
  left_inv := fun i => (layer i).left_inv
  right_inv := fun i => (layer i).right_inv

end CodeLayerPresentation

/-- Presentation of readable syntax as a generated code family.  The library
compiles the one-step layer presentation into `GeneratedCode`. -/
structure SyntaxPresentation
    (P : DepPoly ι)
    (H : OutputIndexInversion P)
    (Syntax : ι → Type v) where
  layer : CodeLayerPresentation P H Syntax Syntax
  rank : ∀ i, Syntax i → Nat
  child_rank_lt :
    ∀ {i : ι} (z : Syntax i)
      (q : P.Pos (H.decode i (((layer.iso i).invFun z).1)).ctor
          (H.decode i (((layer.iso i).invFun z).1)).param),
      rank (P.input (H.decode i (((layer.iso i).invFun z).1)).param q)
          (((layer.iso i).invFun z).2 q) < rank i z

namespace SyntaxPresentation

variable {P : DepPoly ι} {H : OutputIndexInversion P} {Syntax : ι → Type v}

def generatedCode (D : SyntaxPresentation P H Syntax) :
    GeneratedCode P Syntax where
  inversion := H
  layer := D.layer.iso
  rank := D.rank
  child_rank_lt := by
    intro i z q
    exact D.child_rank_lt z q

def iso (D : SyntaxPresentation P H Syntax) (i : ι) : Mu P i ≃ᵢ Syntax i :=
  D.generatedCode.iso i

end SyntaxPresentation

/-- Presentation of a Nat carrier layer. -/
structure NatLayerPresentation
    (P : DepPoly ι)
    (H : OutputIndexInversion P) where
  layer : CodeLayerPresentation P H (fun _ => Nat) (fun _ => Nat)
  child_lt :
    ∀ {i : ι} (n : Nat)
      (q : P.Pos (H.decode i (((layer.iso i).invFun n).1)).ctor
          (H.decode i (((layer.iso i).invFun n).1)).param),
      (((layer.iso i).invFun n).2 q) < n

namespace NatLayerPresentation

variable {P : DepPoly ι} {H : OutputIndexInversion P}

def generatedCode (D : NatLayerPresentation P H) : GeneratedNatCode P where
  inversion := H
  layer := D.layer.iso
  child_lt := by
    intro i n q
    exact D.child_lt n q

def iso (D : NatLayerPresentation P H) (i : ι) : Mu P i ≃ᵢ Nat :=
  D.generatedCode.iso i

end NatLayerPresentation

/-- Presentation of a ranked Nat carrier layer. -/
structure RankedNatLayerPresentation
    (P : DepPoly ι)
    (H : OutputIndexInversion P) where
  layer : CodeLayerPresentation P H (fun _ => Nat) (fun _ => Nat)
  rank : ι → Nat → Nat
  child_rank_lt :
    ∀ {i : ι} (n : Nat)
      (q : P.Pos (H.decode i (((layer.iso i).invFun n).1)).ctor
          (H.decode i (((layer.iso i).invFun n).1)).param),
      rank (P.input (H.decode i (((layer.iso i).invFun n).1)).param q)
          (((layer.iso i).invFun n).2 q) < rank i n

namespace RankedNatLayerPresentation

variable {P : DepPoly ι} {H : OutputIndexInversion P}

def generatedCode (D : RankedNatLayerPresentation P H) :
    GeneratedRankedNatCode P where
  inversion := H
  layer := D.layer.iso
  rank := D.rank
  child_rank_lt := by
    intro i n q
    exact D.child_rank_lt n q

def iso (D : RankedNatLayerPresentation P H) (i : ι) : Mu P i ≃ᵢ Nat :=
  D.generatedCode.iso i

end RankedNatLayerPresentation

/-- Presentation of a finite/infinite shape-coded carrier layer. -/
structure ShapeLayerPresentation
    (P : DepPoly ι)
    (H : OutputIndexInversion P) where
  shape : ι → CodeShape
  layer : CodeLayerPresentation P H (fun i => (shape i).Carrier)
    (fun i => (shape i).Carrier)
  rank : ∀ i, (shape i).Carrier → Nat
  child_rank_lt :
    ∀ {i : ι} (z : (shape i).Carrier)
      (q : P.Pos (H.decode i (((layer.iso i).invFun z).1)).ctor
          (H.decode i (((layer.iso i).invFun z).1)).param),
      rank (P.input (H.decode i (((layer.iso i).invFun z).1)).param q)
          (((layer.iso i).invFun z).2 q) < rank i z

namespace ShapeLayerPresentation

variable {P : DepPoly ι} {H : OutputIndexInversion P}

def generatedCode (D : ShapeLayerPresentation P H) : GeneratedShapeCode P where
  shape := D.shape
  inversion := H
  layer := D.layer.iso
  rank := D.rank
  child_rank_lt := by
    intro i z q
    exact D.child_rank_lt z q

def iso (D : ShapeLayerPresentation P H) (i : ι) :
    Mu P i ≃ᵢ (D.shape i).Carrier :=
  D.generatedCode.iso i

end ShapeLayerPresentation

/-- A well-founded one-step coding of each same-fiber polynomial layer induces
a bijective coding of the dependent initial algebra. -/
def initialAlgebraCoding
    (P : DepPoly ι)
    (Code : ι → Type v)
    (C : WellFoundedCode P Code)
    : ∀ i, Mu P i ≃ᵢ Code i :=
  C.iso

end DepPoly

end BijForm
