import BijForm.DependentPolynomial

namespace BijForm

/-
Initial algebra and generated-coding constructions for dependent polynomial
containers. The container and output-fiber definitions live in
`BijForm.DependentPolynomial`; this module owns the reusable constructions over
those containers.
-/

universe u v w x

namespace DepPoly

variable {ι : Type u}

/-- The initial algebra generated by a dependent polynomial. -/
inductive Mu (P : DepPoly ι) : ι → Type u
  | sup {i : ι}
      (c : P.Ctor)
      (p : P.Param c)
      (h : P.out c p = i)
      (child : (q : P.Pos c p) → Mu P (P.input p q)) : Mu P i

def Mu.out {P : DepPoly ι} {i : ι} : Mu P i → Obj P (Mu P) i
  | Mu.sup c p h child => ⟨c, p, h, child⟩

def Mu.inn {P : DepPoly ι} {i : ι} (x : Obj P (Mu P) i) : Mu P i :=
  Mu.sup x.ctor x.param x.out_eq x.child

theorem Mu_out_inn {P : DepPoly ι} {i : ι} (x : Obj P (Mu P) i) :
    Mu.out (Mu.inn x) = x := by
  cases x
  rfl

theorem Mu_inn_out {P : DepPoly ι} {i : ι} (x : Mu P i) :
    Mu.inn (P := P) (Mu.out x) = x := by
  cases x
  rfl

namespace Mu

/-- Fold out of the polynomial initial algebra into any indexed algebra. -/
def fold {P : DepPoly ι} {A : ι → Type v}
    (alg : ∀ i, Obj P A i → A i) : ∀ i, Mu P i → A i
  | i, Mu.sup c p h child =>
      alg i
        { ctor := c
          param := p
          out_eq := h
          child := fun q => fold alg (P.input p q) (child q) }

@[simp]
theorem fold_sup {P : DepPoly ι} {A : ι → Type v}
    (alg : ∀ i, Obj P A i → A i)
    {i : ι} (c : P.Ctor) (p : P.Param c) (h : P.out c p = i)
    (child : (q : P.Pos c p) → Mu P (P.input p q)) :
    fold alg i (Mu.sup c p h child) =
      alg i
        { ctor := c
          param := p
          out_eq := h
          child := fun q => fold alg (P.input p q) (child q) } :=
  rfl

end Mu

def Layer (P : DepPoly ι) (Code : ι → Type v) (i : ι) : Type (max u v) :=
  Σ f : Fiber P i, (q : P.Pos f.ctor f.param) → Code (P.input f.param q)

def CodeLayer (P : DepPoly ι) (H : OutputIndexInversion P)
    (Code : ι → Type v) (i : ι) : Type (max u v) :=
  Σ c : H.Code i,
    (q : P.Pos (H.decode i c).ctor (H.decode i c).param) →
      Code (P.input (H.decode i c).param q)

namespace CodeLayer

/--
Extensionality for code layers over the canonical output-index inversion.
This is useful for generated branch-table decoders: constructor parameter
records may agree while carrying definitionally different output proofs.
-/
theorem canonical_ext {P : DepPoly ι} {Code : ι → Type v} {i : ι}
    {f g : Fiber P i}
    {childf : (q : P.Pos f.ctor f.param) → Code (P.input f.param q)}
    {childg : (q : P.Pos g.ctor g.param) → Code (P.input g.param q)}
    (hf : f = g) (hchild : childf ≍ childg) :
    (⟨f, childf⟩ :
      CodeLayer P (OutputIndexInversion.canonical P) Code i) =
      ⟨g, childg⟩ := by
  cases hf
  cases hchild
  rfl

theorem canonical_ext_param {P : DepPoly ι} {Code : ι → Type v} {i : ι}
    {ctor : P.Ctor} {param param' : P.Param ctor}
    {out_eq : P.out ctor param = i} {out_eq' : P.out ctor param' = i}
    {childf : (q : P.Pos ctor param) → Code (P.input param q)}
    {childg : (q : P.Pos ctor param') → Code (P.input param' q)}
    (hparam : param = param') (hchild : childf ≍ childg) :
    (⟨{ ctor := ctor, param := param, out_eq := out_eq }, childf⟩ :
      CodeLayer P (OutputIndexInversion.canonical P) Code i) =
      ⟨{ ctor := ctor, param := param', out_eq := out_eq' }, childg⟩ := by
  apply canonical_ext
  · exact Fiber.eq_mk_of_param_eq hparam
  · exact hchild

theorem ext {P : DepPoly ι} {H : OutputIndexInversion P}
    {Code : ι → Type v} {i : ι}
    {c c' : H.Code i}
    {child : (q : P.Pos (H.decode i c).ctor (H.decode i c).param) →
      Code (P.input (H.decode i c).param q)}
    {child' : (q : P.Pos (H.decode i c').ctor (H.decode i c').param) →
      Code (P.input (H.decode i c').param q)}
    (hc : c = c') (hchild : child ≍ child') :
    (⟨c, child⟩ : CodeLayer P H Code i) = ⟨c', child'⟩ := by
  cases hc
  cases hchild
  rfl

theorem ext_rfl {P : DepPoly ι} {H : OutputIndexInversion P}
    {Code : ι → Type v} {i : ι} {c : H.Code i}
    {child child' :
      (q : P.Pos (H.decode i c).ctor (H.decode i c).param) →
        Code (P.input (H.decode i c).param q)}
    (hchild : child = child') :
    (⟨c, child⟩ : CodeLayer P H Code i) = ⟨c, child'⟩ :=
  ext rfl (heq_of_eq hchild)

theorem ext_layer {P : DepPoly ι} {H : OutputIndexInversion P}
    {Code : ι → Type v} {i : ι} {x y : CodeLayer P H Code i}
    (hcode : x.1 = y.1) (hchild : x.2 ≍ y.2) : x = y := by
  cases x with
  | mk c child =>
    cases y with
    | mk c' child' =>
      exact ext hcode hchild

/--
Prove a fixed canonical same-fiber layer left inverse by constructor/fiber
cases. Callers supply only the domain-specific constructor clauses; this helper
owns the generic `CodeLayer` and `Fiber` unpacking.
-/
theorem canonical_left_inv_at_by_fiber {P : DepPoly ι} {Code : ι → Type v}
    {i : ι} {Carrier : Type w}
    {toCarrier : CodeLayer P (OutputIndexInversion.canonical P) Code i → Carrier}
    {fromCarrier : Carrier → CodeLayer P (OutputIndexInversion.canonical P) Code i}
    (h : ∀ (ctor : P.Ctor) (param : P.Param ctor)
      (out_eq : P.out ctor param = i)
      (child : (q : P.Pos ctor param) → Code (P.input param q)),
      fromCarrier (toCarrier ⟨⟨ctor, param, out_eq⟩, child⟩) =
        ⟨⟨ctor, param, out_eq⟩, child⟩) :
    Function.LeftInverse fromCarrier toCarrier := by
  intro layer
  cases layer with
  | mk code child =>
    cases code with
    | mk ctor param out_eq =>
      exact h ctor param out_eq child

/--
Prove an indexed canonical same-fiber layer left inverse by constructor/fiber
cases.
-/
theorem canonical_left_inv_by_fiber {P : DepPoly ι} {Code : ι → Type v}
    {Carrier : ι → Type w}
    {toCarrier :
      ∀ i, CodeLayer P (OutputIndexInversion.canonical P) Code i → Carrier i}
    {fromCarrier :
      ∀ i, Carrier i → CodeLayer P (OutputIndexInversion.canonical P) Code i}
    (h : ∀ {i : ι} (ctor : P.Ctor) (param : P.Param ctor)
      (out_eq : P.out ctor param = i)
      (child : (q : P.Pos ctor param) → Code (P.input param q)),
      fromCarrier i (toCarrier i ⟨⟨ctor, param, out_eq⟩, child⟩) =
        ⟨⟨ctor, param, out_eq⟩, child⟩) :
    ∀ i, Function.LeftInverse (fromCarrier i) (toCarrier i) := by
  intro i
  exact canonical_left_inv_at_by_fiber (i := i) (h := h)

end CodeLayer

/-- Prove child-function eta facts by splitting the child-position type. -/
syntax "child_eta_cases" : tactic
macro_rules
  | `(tactic| child_eta_cases) =>
      `(tactic|
        first
        | (funext q; cases q <;> rfl)
        | (symm; funext q; cases q <;> rfl))

/-- Close goals that become `rfl` after eta-expanding a child function. -/
syntax "child_eta_rfl " ident : tactic
macro_rules
  | `(tactic| child_eta_rfl $child:ident) =>
      `(tactic|
        first
        | (have hchild_eta : (fun q => nomatch q) = $child := by child_eta_cases;
           cases hchild_eta;
           rfl)
        | (have hchild_eta : (fun _ => $child ()) = $child := by child_eta_cases;
           cases hchild_eta;
           rfl)
        | (have hchild_eta : $child = (fun
              | false => $child false
              | true => $child true) := by child_eta_cases;
           rw [hchild_eta];
           rfl))

/--
Close a canonical constructor-layer inverse branch after constructor-specific
parameter decomposition.
-/
syntax "finish_code_layer_left_inv " ident ident : tactic
macro_rules
  | `(tactic| finish_code_layer_left_inv $outEq:ident $child:ident) =>
      `(tactic|
        first
        | (simp at $outEq:ident;
           cases ($outEq:ident).symm;
           cases $outEq:ident;
           child_eta_rfl $child)
        | (cases ($outEq:ident).symm;
           cases $outEq:ident;
           child_eta_rfl $child)
        | (cases $outEq:ident;
           child_eta_rfl $child)
        | child_eta_rfl $child)

def castFiberChild {P : DepPoly ι} {Code : ι → Type v} {i : ι}
    {f g : Fiber P i} (h : f = g)
    (child : (q : P.Pos f.ctor f.param) → Code (P.input f.param q)) :
    (q : P.Pos g.ctor g.param) → Code (P.input g.param q) := by
  cases h
  exact child

theorem castFiberChild_heq {P : DepPoly ι} {Code : ι → Type v} {i : ι}
    {f g : Fiber P i} (h : f = g)
    (child : (q : P.Pos f.ctor f.param) → Code (P.input f.param q)) :
    castFiberChild h child ≍ child := by
  cases h
  rfl

theorem obj_eq_of_fiber_eq {P : DepPoly ι} {Code : ι → Type v} {i : ι}
    {f g : Fiber P i} (h : g = f)
    (child : (q : P.Pos f.ctor f.param) → Code (P.input f.param q)) :
    ({ ctor := g.ctor
       param := g.param
       out_eq := g.out_eq
       child := castFiberChild h.symm child } : Obj P Code i) =
      { ctor := f.ctor, param := f.param, out_eq := f.out_eq, child := child } := by
  cases h
  rfl

theorem CodeLayer.canonical_ext_cast {P : DepPoly ι} {Code : ι → Type v} {i : ι}
    {f g : Fiber P i} (hf : f = g)
    (child : (q : P.Pos f.ctor f.param) → Code (P.input f.param q)) :
    (⟨f, child⟩ :
      CodeLayer P (OutputIndexInversion.canonical P) Code i) =
      ⟨g, castFiberChild hf child⟩ := by
  cases hf
  rfl

def objCodeLayerTo {P : DepPoly ι} {Code : ι → Type v} {i : ι}
    (H : OutputIndexInversion P) (x : Obj P Code i) :
    CodeLayer P H Code i := by
  exact
    ⟨H.encode i ⟨x.ctor, x.param, x.out_eq⟩,
      castFiberChild
        (H.decode_encode i ⟨x.ctor, x.param, x.out_eq⟩).symm
        x.child⟩

def objCodeLayerInv {P : DepPoly ι} {Code : ι → Type v} {i : ι}
    (H : OutputIndexInversion P) (x : CodeLayer P H Code i) :
    Obj P Code i :=
  let f := H.decode i x.1
  ⟨f.ctor, f.param, f.out_eq, x.2⟩

def objCodeLayerIso {P : DepPoly ι} (H : OutputIndexInversion P)
    (Code : ι → Type v) (i : ι) :
    Obj P Code i ≃ᵢ CodeLayer P H Code i where
  toFun := objCodeLayerTo H
  invFun := objCodeLayerInv H
  left_inv := by
    intro x
    cases x with
    | mk ctor param out_eq child =>
        dsimp [objCodeLayerTo, objCodeLayerInv]
        let f : Fiber P i := { ctor := ctor, param := param, out_eq := out_eq }
        exact obj_eq_of_fiber_eq (H.decode_encode i f) child
  right_inv := by
    intro x
    cases x with
    | mk c child =>
        dsimp [objCodeLayerTo, objCodeLayerInv]
        refine Sigma.ext (H.encode_decode i c) ?_
        exact castFiberChild_heq (H.decode_encode i (H.decode i c)).symm child

/--
The corrected condition for automatic codings.  Besides the one-step
isomorphism, decoding must be well-founded: every recursive child code produced
by one-step decoding has smaller rank than the code being decoded.
-/
structure WellFoundedCode
    (P : DepPoly ι)
    (Code : ι → Type v) where
  step : ∀ i, Obj P Code i ≃ᵢ Code i
  rank : ∀ i, Code i → Nat
  child_rank_lt :
    ∀ {i : ι} (z : Code i)
      (q : P.Pos ((step i).invFun z).ctor ((step i).invFun z).param),
      rank (P.input ((step i).invFun z).param q)
          (((step i).invFun z).child q) < rank i z

namespace WellFoundedCode

variable {P : DepPoly ι} {Code : ι → Type v}

def encode (C : WellFoundedCode P Code) : ∀ i, Mu P i → Code i
  | i, Mu.sup c p h child =>
      (C.step i).toFun
        ⟨c, p, h, fun q => encode C (P.input p q) (child q)⟩

def decode (C : WellFoundedCode P Code) : ∀ i, Code i → Mu P i
  | i, z =>
      let layer := (C.step i).invFun z
      Mu.sup layer.ctor layer.param layer.out_eq
        (fun q => decode C (P.input layer.param q) (layer.child q))
termination_by i z => C.rank i z
decreasing_by
  exact C.child_rank_lt z q

theorem decode_encode (C : WellFoundedCode P Code) :
    ∀ i (x : Mu P i), decode C i (encode C i x) = x
  | i, Mu.sup c p h child => by
      let layer : Obj P Code i :=
        ⟨c, p, h, fun q => encode C (P.input p q) (child q)⟩
      have hleft : (C.step i).invFun ((C.step i).toFun layer) = layer :=
        (C.step i).left_inv layer
      have ih :
          (fun q => decode C (P.input p q) (encode C (P.input p q) (child q)))
            = child := by
        funext q
        exact decode_encode C (P.input p q) (child q)
      change decode C i ((C.step i).toFun layer) = Mu.sup c p h child
      rw [decode]
      rw [hleft]
      simp [layer, ih]

theorem encode_decode (C : WellFoundedCode P Code) :
    ∀ i (z : Code i), encode C i (decode C i z) = z
  | i, z => by
      let layer := (C.step i).invFun z
      have ih :
          (fun q => encode C (P.input layer.param q)
            (decode C (P.input layer.param q) (layer.child q)))
            = layer.child := by
        funext q
        exact encode_decode C (P.input layer.param q) (layer.child q)
      have hstep : (C.step i).toFun layer = z := (C.step i).right_inv z
      rw [decode]
      rw [encode]
      change (C.step i).toFun
          ⟨layer.ctor, layer.param, layer.out_eq, fun q =>
            encode C (P.input layer.param q)
              (decode C (P.input layer.param q) (layer.child q))⟩ = z
      rw [ih]
      exact hstep
termination_by i z => C.rank i z
decreasing_by
  exact C.child_rank_lt z q

def iso (C : WellFoundedCode P Code) (i : ι) : Mu P i ≃ᵢ Code i where
  toFun := encode C i
  invFun := decode C i
  left_inv := decode_encode C i
  right_inv := encode_decode C i

end WellFoundedCode

/--
Generated coding data. The caller supplies an output-index inversion, a coding
of the resulting local layer into a carrier family, and a well-founded rank on
that carrier family. The full `Obj P Code i ≃ᵢ Code i` step is generated by
composing with `objCodeLayerIso`.
-/
structure GeneratedCode
    (P : DepPoly ι)
    (Code : ι → Type v) where
  inversion : OutputIndexInversion P
  layer : ∀ i, CodeLayer P inversion Code i ≃ᵢ Code i
  rank : ∀ i, Code i → Nat
  child_rank_lt :
    ∀ {i : ι} (z : Code i)
      (q : P.Pos (inversion.decode i ((layer i).invFun z).1).ctor
          (inversion.decode i ((layer i).invFun z).1).param),
      rank (P.input (inversion.decode i ((layer i).invFun z).1).param q)
          (((layer i).invFun z).2 q) < rank i z

namespace GeneratedCode

variable {P : DepPoly ι} {Code : ι → Type v}

/-- Build generated coding data from the natural layer-local descent proof.
Callers prove that every child in a decoded one-step layer has smaller rank
than the layer after re-encoding; this constructor supplies the equivalent
encoded-parent proof required by `GeneratedCode`. -/
def ofLayerChildRank
    (inversion : OutputIndexInversion P)
    (layer : ∀ i, CodeLayer P inversion Code i ≃ᵢ Code i)
    (rank : ∀ i, Code i → Nat)
    (layer_child_rank_lt :
      ∀ {i : ι} (x : CodeLayer P inversion Code i)
        (q : P.Pos (inversion.decode i x.1).ctor
            (inversion.decode i x.1).param),
        rank (P.input (inversion.decode i x.1).param q) (x.2 q) <
          rank i ((layer i).toFun x)) :
    GeneratedCode P Code where
  inversion := inversion
  layer := layer
  rank := rank
  child_rank_lt := by
    intro i z q
    simpa using layer_child_rank_lt ((layer i).invFun z) q

def step (C : GeneratedCode P Code) (i : ι) :
    Obj P Code i ≃ᵢ Code i :=
  Iso.trans (objCodeLayerIso C.inversion Code i) (C.layer i)

def toWellFoundedCode (C : GeneratedCode P Code) :
    WellFoundedCode P Code where
  step := C.step
  rank := C.rank
  child_rank_lt := by
    intro i z q
    simpa [step, objCodeLayerIso, objCodeLayerInv] using C.child_rank_lt z q

def iso (C : GeneratedCode P Code) (i : ι) : Mu P i ≃ᵢ Code i :=
  C.toWellFoundedCode.iso i

def encode (C : GeneratedCode P Code) (i : ι) (x : Mu P i) : Code i :=
  C.toWellFoundedCode.encode i x

def decode (C : GeneratedCode P Code) (i : ι) (z : Code i) : Mu P i :=
  C.toWellFoundedCode.decode i z

theorem decode_encode (C : GeneratedCode P Code) (i : ι) (x : Mu P i) :
    C.decode i (C.encode i x) = x :=
  C.toWellFoundedCode.decode_encode i x

theorem encode_decode (C : GeneratedCode P Code) (i : ι) (z : Code i) :
    C.encode i (C.decode i z) = z :=
  C.toWellFoundedCode.encode_decode i z

end GeneratedCode

inductive CodeShape where
  | finite (k : Nat)
  | infinite

namespace CodeShape

def Carrier : CodeShape → Type
  | finite k => Fin k
  | infinite => Nat

def rank : (s : CodeShape) → Carrier s → Nat
  | finite _, _ => 0
  | infinite, n => n

/-- If a code shape is infinite, its carrier is canonically `Nat`. -/
def infiniteIso {s : CodeShape} (h : s = infinite) : Carrier s ≃ᵢ Nat := by
  cases h
  exact Iso.refl Nat

/-- If a code shape is finite of size `k`, its carrier is canonically
`Fin k`. -/
def finiteIso {s : CodeShape} {k : Nat} (h : s = finite k) :
    Carrier s ≃ᵢ Fin k := by
  cases h
  exact Iso.refl (Fin k)

/-- Indexed-family form of `infiniteIso`. -/
def carrierNatIso {ι : Type u} (shape : ι → CodeShape) (i : ι)
    (h : shape i = infinite) : Carrier (shape i) ≃ᵢ Nat :=
  infiniteIso h

/-- Indexed-family form of `finiteIso`. -/
def carrierFinIso {ι : Type u} (shape : ι → CodeShape) (i : ι)
    {k : Nat} (h : shape i = finite k) : Carrier (shape i) ≃ᵢ Fin k :=
  finiteIso h

/-- Postcompose any source-to-shape-carrier isomorphism with an infinite case. -/
def sourceNatIso {α : Type u} {s : CodeShape}
    (source : α ≃ᵢ Carrier s) (h : s = infinite) :
    α ≃ᵢ Nat :=
  Iso.trans source (infiniteIso h)

/-- Postcompose any source-to-shape-carrier isomorphism with a finite case. -/
def sourceFinIso {α : Type u} {s : CodeShape} {k : Nat}
    (source : α ≃ᵢ Carrier s) (h : s = finite k) :
    α ≃ᵢ Fin k :=
  Iso.trans source (finiteIso h)

end CodeShape

/--
Generated coding data for index-dependent finite/infinite carrier families.
This keeps the intended carrier shape explicit while storing generated-code
evidence only in the canonical `GeneratedCode` record.
-/
structure GeneratedShapeCode (P : DepPoly ι) where
  shape : ι → CodeShape
  code : GeneratedCode P (fun i => (shape i).Carrier)

namespace GeneratedShapeCode

variable {P : DepPoly ι}

/-- Layer-local constructor for shape-coded generated data. -/
def ofLayerChildRank
    (shape : ι → CodeShape)
    (inversion : OutputIndexInversion P)
    (layer : ∀ i,
      CodeLayer P inversion (fun j => (shape j).Carrier) i ≃ᵢ
        (shape i).Carrier)
    (rank : ∀ i, (shape i).Carrier → Nat)
    (layer_child_rank_lt :
      ∀ {i : ι} (x : CodeLayer P inversion (fun j => (shape j).Carrier) i)
        (q : P.Pos (inversion.decode i x.1).ctor
            (inversion.decode i x.1).param),
        rank (P.input (inversion.decode i x.1).param q) (x.2 q) <
          rank i ((layer i).toFun x)) :
    GeneratedShapeCode P where
  shape := shape
  code := GeneratedCode.ofLayerChildRank inversion layer rank layer_child_rank_lt

def iso (C : GeneratedShapeCode P) (i : ι) :
    Mu P i ≃ᵢ (C.shape i).Carrier :=
  C.code.iso i

def natIso (C : GeneratedShapeCode P) (i : ι)
    (h : C.shape i = .infinite) : Mu P i ≃ᵢ Nat :=
  Iso.trans (C.iso i) (CodeShape.infiniteIso h)

def finIso (C : GeneratedShapeCode P) (i : ι) {k : Nat}
    (h : C.shape i = .finite k) : Mu P i ≃ᵢ Fin k :=
  Iso.trans (C.iso i) (CodeShape.finiteIso h)

end GeneratedShapeCode

/--
Generated Nat coding data.  A local Nat layer decoder must produce recursive
child codes that are strictly smaller than the parent code, so the generic
decoder is well-founded with the identity rank on `Nat`.
-/
abbrev GeneratedNatCode (P : DepPoly ι) :=
  GeneratedCode P (fun _ => Nat)

namespace GeneratedCode

variable {P : DepPoly ι}

/-- Compose two generated codings of the same dependent polynomial through the
shared initial algebra.  This is the generic route from readable syntax to a
generated carrier code. -/
def codeIso {Source : ι → Type v} {Target : ι → Type w}
    (source : GeneratedCode P Source) (target : GeneratedCode P Target) (i : ι) :
    Source i ≃ᵢ Target i :=
  Iso.trans (Iso.symm (source.iso i)) (target.iso i)

/-- Compose a generated source coding with a generated shape-coded carrier. -/
def shapeCodeIso {Source : ι → Type v}
    (source : GeneratedCode P Source) (target : GeneratedShapeCode P) (i : ι) :
    Source i ≃ᵢ (target.shape i).Carrier :=
  codeIso source target.code i

/-- Compose a generated source coding with an infinite generated shape case. -/
def shapeNatIso {Source : ι → Type v}
    (source : GeneratedCode P Source) (target : GeneratedShapeCode P) (i : ι)
    (h : target.shape i = .infinite) : Source i ≃ᵢ Nat :=
  CodeShape.sourceNatIso (shapeCodeIso source target i) h

/-- Compose a generated source coding with a finite generated shape case. -/
def shapeFinIso {Source : ι → Type v}
    (source : GeneratedCode P Source) (target : GeneratedShapeCode P) (i : ι)
    {k : Nat} (h : target.shape i = .finite k) : Source i ≃ᵢ Fin k :=
  CodeShape.sourceFinIso (shapeCodeIso source target i) h

end GeneratedCode

/-- Declarative presentation of a one-step `CodeLayer` as a carrier family.
This owns the generic construction of the layer isomorphism; examples supply
only the two directions and inverse proofs for their domain-specific shape. -/
structure CodeLayerPresentation
    (P : DepPoly ι)
    (H : OutputIndexInversion P)
    (Code : ι → Type v)
    (Carrier : ι → Type w) where
  toCarrier : ∀ i, CodeLayer P H Code i → Carrier i
  fromCarrier : ∀ i, Carrier i → CodeLayer P H Code i
  left_inv : ∀ i, Function.LeftInverse (fromCarrier i) (toCarrier i)
  right_inv : ∀ i, Function.RightInverse (fromCarrier i) (toCarrier i)

namespace CodeLayerPresentation

variable {P : DepPoly ι} {H : OutputIndexInversion P}
variable {Code : ι → Type v} {Carrier : ι → Type w}
variable {Shape : ι → Type x}

def iso (D : CodeLayerPresentation P H Code Carrier) (i : ι) :
    CodeLayer P H Code i ≃ᵢ Carrier i where
  toFun := D.toCarrier i
  invFun := D.fromCarrier i
  left_inv := D.left_inv i
  right_inv := D.right_inv i

def ofMaps
    (toCarrier : ∀ i, CodeLayer P H Code i → Carrier i)
    (fromCarrier : ∀ i, Carrier i → CodeLayer P H Code i)
    (left_inv : ∀ i, Function.LeftInverse (fromCarrier i) (toCarrier i))
    (right_inv : ∀ i, Function.RightInverse (fromCarrier i) (toCarrier i)) :
    CodeLayerPresentation P H Code Carrier where
  toCarrier := toCarrier
  fromCarrier := fromCarrier
  left_inv := left_inv
  right_inv := right_inv

def ofIso (layer : ∀ i, CodeLayer P H Code i ≃ᵢ Carrier i) :
    CodeLayerPresentation P H Code Carrier where
  toCarrier := fun i => (layer i).toFun
  fromCarrier := fun i => (layer i).invFun
  left_inv := fun i => (layer i).left_inv
  right_inv := fun i => (layer i).right_inv

def transCarrier (D : CodeLayerPresentation P H Code Shape)
    (carrier : ∀ i, Shape i ≃ᵢ Carrier i) :
    CodeLayerPresentation P H Code Carrier where
  toCarrier := fun i layer => (carrier i).toFun (D.toCarrier i layer)
  fromCarrier := fun i z => D.fromCarrier i ((carrier i).invFun z)
  left_inv := by
    intro i layer
    dsimp
    rw [(carrier i).left_inv (D.toCarrier i layer)]
    exact D.left_inv i layer
  right_inv := by
    intro i z
    dsimp
    rw [D.right_inv i ((carrier i).invFun z)]
    exact (carrier i).right_inv z

end CodeLayerPresentation

/-- Canonical layer presentation for generated coding.  This is the only record
that owns the one-step layer isomorphism, rank, and recursive descent proof. -/
structure LayerPresentation
    (P : DepPoly ι)
    (H : OutputIndexInversion P)
    (Code : ι → Type v) where
  layer : CodeLayerPresentation P H Code Code
  rank : ∀ i, Code i → Nat
  child_rank_lt :
    ∀ {i : ι} (z : Code i)
      (q : P.Pos (H.decode i (((layer.iso i).invFun z).1)).ctor
          (H.decode i (((layer.iso i).invFun z).1)).param),
      rank (P.input (H.decode i (((layer.iso i).invFun z).1)).param q)
          (((layer.iso i).invFun z).2 q) < rank i z

namespace LayerPresentation

variable {P : DepPoly ι} {H : OutputIndexInversion P}
variable {Code : ι → Type v} {Shape : ι → Type w}

def ofLayer
    (layer : CodeLayerPresentation P H Code Code)
    (rank : ∀ i, Code i → Nat)
    (child_rank_lt :
      ∀ {i : ι} (z : Code i)
        (q : P.Pos (H.decode i (((layer.iso i).invFun z).1)).ctor
            (H.decode i (((layer.iso i).invFun z).1)).param),
        rank (P.input (H.decode i (((layer.iso i).invFun z).1)).param q)
            (((layer.iso i).invFun z).2 q) < rank i z) :
    LayerPresentation P H Code where
  layer := layer
  rank := rank
  child_rank_lt := by
    intro i z q
    exact child_rank_lt z q

def ofLayerMaps
    (toCarrier : ∀ i, CodeLayer P H Code i → Code i)
    (fromCarrier : ∀ i, Code i → CodeLayer P H Code i)
    (left_inv : ∀ i, Function.LeftInverse (fromCarrier i) (toCarrier i))
    (right_inv : ∀ i, Function.RightInverse (fromCarrier i) (toCarrier i))
    (rank : ∀ i, Code i → Nat)
    (child_rank_lt :
      ∀ {i : ι} (z : Code i)
        (q : P.Pos (H.decode i ((fromCarrier i z).1)).ctor
            (H.decode i ((fromCarrier i z).1)).param),
        rank (P.input (H.decode i ((fromCarrier i z).1)).param q)
            ((fromCarrier i z).2 q) < rank i z) :
    LayerPresentation P H Code where
  layer := CodeLayerPresentation.ofMaps toCarrier fromCarrier left_inv right_inv
  rank := rank
  child_rank_lt := by
    intro i z q
    exact child_rank_lt z q

def ofLayerChildRank
    (layer : CodeLayerPresentation P H Code Code)
    (rank : ∀ i, Code i → Nat)
    (layer_child_rank_lt :
      ∀ {i : ι} (x : CodeLayer P H Code i)
        (q : P.Pos (H.decode i x.1).ctor (H.decode i x.1).param),
        rank (P.input (H.decode i x.1).param q) (x.2 q) <
          rank i ((layer.iso i).toFun x)) :
    LayerPresentation P H Code where
  layer := layer
  rank := rank
  child_rank_lt := by
    intro i z q
    simpa using layer_child_rank_lt ((layer.iso i).invFun z) q

/--
Build a canonical layer presentation from a layer-local descent proof after
factoring the one-step layer through an intermediate domain-specific shape.
-/
def ofLayerShapeChildRank
    (layerShape : CodeLayerPresentation P H Code Shape)
    (carrier : ∀ i, Shape i ≃ᵢ Code i)
    (rank : ∀ i, Code i → Nat)
    (layer_child_rank_lt :
      ∀ {i : ι} (x : CodeLayer P H Code i)
        (q : P.Pos (H.decode i x.1).ctor (H.decode i x.1).param),
        rank (P.input (H.decode i x.1).param q) (x.2 q) <
          rank i (((layerShape.transCarrier carrier).iso i).toFun x)) :
    LayerPresentation P H Code :=
  ofLayerChildRank (layerShape.transCarrier carrier) rank layer_child_rank_lt

/--
Build a canonical layer presentation from a descent proof over an intermediate
domain-specific shape.
-/
def ofShapeChildRank
    (layerShape : CodeLayerPresentation P H Code Shape)
    (carrier : ∀ i, Shape i ≃ᵢ Code i)
    (rank : ∀ i, Code i → Nat)
    (shape_child_rank_lt :
      ∀ {i : ι} (shape : Shape i)
        (q : P.Pos (H.decode i ((layerShape.fromCarrier i shape).1)).ctor
            (H.decode i ((layerShape.fromCarrier i shape).1)).param),
        rank (P.input (H.decode i ((layerShape.fromCarrier i shape).1)).param q)
            ((layerShape.fromCarrier i shape).2 q) <
          rank i ((carrier i).toFun shape)) :
    LayerPresentation P H Code where
  layer := layerShape.transCarrier carrier
  rank := rank
  child_rank_lt := by
    intro i z q
    simpa [CodeLayerPresentation.iso, CodeLayerPresentation.transCarrier] using
      shape_child_rank_lt ((carrier i).invFun z) q

def ofCarrierLayerIso
    (layer : ∀ i, CodeLayer P H Code i ≃ᵢ Code i)
    (rank : ∀ i, Code i → Nat)
    (child_rank_lt :
      ∀ {i : ι} (z : Code i)
        (q : P.Pos (H.decode i (((layer i).invFun z).1)).ctor
            (H.decode i (((layer i).invFun z).1)).param),
        rank (P.input (H.decode i (((layer i).invFun z).1)).param q)
            (((layer i).invFun z).2 q) < rank i z) :
    LayerPresentation P H Code :=
  ofLayer (CodeLayerPresentation.ofIso layer) rank child_rank_lt

def generatedCode (D : LayerPresentation P H Code) :
    GeneratedCode P Code :=
  GeneratedCode.ofLayerChildRank H D.layer.iso D.rank (by
    intro i x
    rw [← (D.layer.iso i).left_inv x]
    intro q
    simpa using D.child_rank_lt ((D.layer.iso i).toFun x) q)

def iso (D : LayerPresentation P H Code) (i : ι) : Mu P i ≃ᵢ Code i :=
  D.generatedCode.iso i

end LayerPresentation

/-- Readable syntax presentation as a view of canonical layer presentations. -/
abbrev SyntaxPresentation
    (P : DepPoly ι)
    (H : OutputIndexInversion P)
    (Syntax : ι → Type v) :=
  LayerPresentation P H Syntax

namespace SyntaxPresentation

variable {P : DepPoly ι} {H : OutputIndexInversion P} {Syntax : ι → Type v}

def ofLayer
    (layer : CodeLayerPresentation P H Syntax Syntax)
    (rank : ∀ i, Syntax i → Nat)
    (child_rank_lt :
      ∀ {i : ι} (z : Syntax i)
        (q : P.Pos (H.decode i (((layer.iso i).invFun z).1)).ctor
            (H.decode i (((layer.iso i).invFun z).1)).param),
        rank (P.input (H.decode i (((layer.iso i).invFun z).1)).param q)
            (((layer.iso i).invFun z).2 q) < rank i z) :
    SyntaxPresentation P H Syntax :=
  LayerPresentation.ofLayer layer rank child_rank_lt

def ofLayerIso
    (layer : ∀ i, CodeLayer P H Syntax i ≃ᵢ Syntax i)
    (rank : ∀ i, Syntax i → Nat)
    (child_rank_lt :
      ∀ {i : ι} (z : Syntax i)
        (q : P.Pos (H.decode i (((layer i).invFun z).1)).ctor
            (H.decode i (((layer i).invFun z).1)).param),
        rank (P.input (H.decode i (((layer i).invFun z).1)).param q)
            (((layer i).invFun z).2 q) < rank i z) :
    SyntaxPresentation P H Syntax :=
  LayerPresentation.ofCarrierLayerIso layer rank child_rank_lt

def ofLayerMaps
    (toSyntax : ∀ i, CodeLayer P H Syntax i → Syntax i)
    (fromSyntax : ∀ i, Syntax i → CodeLayer P H Syntax i)
    (left_inv : ∀ i, Function.LeftInverse (fromSyntax i) (toSyntax i))
    (right_inv : ∀ i, Function.RightInverse (fromSyntax i) (toSyntax i))
    (rank : ∀ i, Syntax i → Nat)
    (child_rank_lt :
      ∀ {i : ι} (z : Syntax i)
        (q : P.Pos (H.decode i ((fromSyntax i z).1)).ctor
            (H.decode i ((fromSyntax i z).1)).param),
        rank (P.input (H.decode i ((fromSyntax i z).1)).param q)
            ((fromSyntax i z).2 q) < rank i z) :
    SyntaxPresentation P H Syntax :=
  LayerPresentation.ofLayerMaps toSyntax fromSyntax left_inv right_inv rank
    child_rank_lt

def generatedCode (D : SyntaxPresentation P H Syntax) :
    GeneratedCode P Syntax :=
  LayerPresentation.generatedCode D

def iso (D : SyntaxPresentation P H Syntax) (i : ι) : Mu P i ≃ᵢ Syntax i :=
  D.generatedCode.iso i

end SyntaxPresentation

/-- Nat-carrier presentation as a view of canonical layer presentations. -/
abbrev NatLayerPresentation
    (P : DepPoly ι)
    (H : OutputIndexInversion P) :=
  LayerPresentation P H (fun _ => Nat)

namespace NatLayerPresentation

variable {P : DepPoly ι} {H : OutputIndexInversion P}

def ofLayerChildLt
    (layer : CodeLayerPresentation P H (fun _ => Nat) (fun _ => Nat))
    (child_lt :
      ∀ {i : ι} (x : CodeLayer P H (fun _ => Nat) i)
        (q : P.Pos (H.decode i x.1).ctor (H.decode i x.1).param),
        x.2 q < (layer.iso i).toFun x) :
    NatLayerPresentation P H :=
  LayerPresentation.ofLayerChildRank layer (fun _ n => n) (by
    intro i x q
    exact child_lt x q)

end NatLayerPresentation

/-- Ranked Nat-carrier presentation as a view of canonical layer presentations. -/
abbrev RankedNatLayerPresentation
    (P : DepPoly ι)
    (H : OutputIndexInversion P) :=
  LayerPresentation P H (fun _ => Nat)

namespace RankedNatLayerPresentation

variable {P : DepPoly ι} {H : OutputIndexInversion P}

def ofLayerChildRank
    (layer : CodeLayerPresentation P H (fun _ => Nat) (fun _ => Nat))
    (rank : ι → Nat → Nat)
    (layer_child_rank_lt :
      ∀ {i : ι} (x : CodeLayer P H (fun _ => Nat) i)
        (q : P.Pos (H.decode i x.1).ctor (H.decode i x.1).param),
        rank (P.input (H.decode i x.1).param q) (x.2 q) <
          rank i ((layer.iso i).toFun x)) :
    RankedNatLayerPresentation P H :=
  LayerPresentation.ofLayerChildRank layer rank layer_child_rank_lt

end RankedNatLayerPresentation

/-- Shape-coded presentation stores shape metadata and one canonical layer
presentation for that carrier family. -/
structure ShapeLayerPresentation
    (P : DepPoly ι)
    (H : OutputIndexInversion P) where
  shape : ι → CodeShape
  presentation : LayerPresentation P H (fun i => (shape i).Carrier)

namespace ShapeLayerPresentation

variable {P : DepPoly ι} {H : OutputIndexInversion P}

def generatedCode (D : ShapeLayerPresentation P H) : GeneratedShapeCode P where
  shape := D.shape
  code := D.presentation.generatedCode

end ShapeLayerPresentation

/-- A well-founded one-step coding of each same-fiber polynomial layer induces
a bijective coding of the dependent initial algebra. -/
def initialAlgebraCoding
    (P : DepPoly ι)
    (Code : ι → Type v)
    (C : WellFoundedCode P Code)
    : ∀ i, Mu P i ≃ᵢ Code i :=
  C.iso

end DepPoly

end BijForm
