import BijForm.DependentPolynomial

namespace BijForm
namespace DepPoly

universe u v w

variable {ι : Type u}

namespace Obj

/-- Functorial action on one dependent-polynomial layer. -/
def map {P : DepPoly ι} {X Y : ι → Type v}
    (f : ∀ i, X i → Y i) {i : ι} (x : Obj P X i) : Obj P Y i where
  ctor := x.ctor
  param := x.param
  out_eq := x.out_eq
  child := fun q => f (P.input x.param q) (x.child q)

@[simp]
theorem map_ctor {P : DepPoly ι} {X Y : ι → Type v}
    (f : ∀ i, X i → Y i) {i : ι} (x : Obj P X i) :
    (map f x).ctor = x.ctor :=
  rfl

@[simp]
theorem map_param {P : DepPoly ι} {X Y : ι → Type v}
    (f : ∀ i, X i → Y i) {i : ι} (x : Obj P X i) :
    (map f x).param = x.param :=
  rfl

@[simp]
theorem map_child {P : DepPoly ι} {X Y : ι → Type v}
    (f : ∀ i, X i → Y i) {i : ι} (x : Obj P X i)
    (q : P.Pos x.ctor x.param) :
    (map f x).child q = f (P.input x.param q) (x.child q) :=
  rfl

end Obj

/--
A project-native quotient presentation for a dependent-polynomial initial
algebra.

`LayerRel i x y` is the constructor-layer abstraction relation at index `i`.
The generated relation on `Mu P i` closes it under recursive congruence,
symmetry, and transitivity.  This is the concrete indexed analogue of the
QPF `abs` equality rule used by Avigad-Carneiro-Hudon.
-/
structure QuotientPresentation (P : DepPoly ι) where
  LayerRel : ∀ i, Obj P (Mu P) i → Obj P (Mu P) i → Prop

namespace QuotientPresentation

variable {P : DepPoly ι}

/-- The equivalence relation on the polynomial initial algebra generated by a
constructor-layer quotient presentation. -/
inductive Rel (Q : QuotientPresentation P) :
    ∀ i, Mu P i → Mu P i → Prop
  | refl {i : ι} (x : Mu P i) : Rel Q i x x
  | layer {i : ι} {x y : Obj P (Mu P) i} :
      Q.LayerRel i x y → Rel Q i (Mu.inn x) (Mu.inn y)
  | congr {i : ι} {c : P.Ctor} {p : P.Param c}
      {h : P.out c p = i}
      {child child' : (q : P.Pos c p) → Mu P (P.input p q)} :
      (∀ q, Rel Q (P.input p q) (child q) (child' q)) →
        Rel Q i (Mu.sup c p h child) (Mu.sup c p h child')
  | symm {i : ι} {x y : Mu P i} :
      Rel Q i x y → Rel Q i y x
  | trans {i : ι} {x y z : Mu P i} :
      Rel Q i x y → Rel Q i y z → Rel Q i x z

/-- The generated quotient relation bundled as an explicit setoid, so quotient
equality can be reflected back to the generated relation when proving
constructor well-definedness. -/
def setoid (Q : QuotientPresentation P) (i : ι) : Setoid (Mu P i) where
  r := Rel Q i
  iseqv := by
    refine ⟨?_, ?_, ?_⟩
    · intro x
      exact Rel.refl x
    · intro x y h
      exact Rel.symm h
    · intro x y z hxy hyz
      exact Rel.trans hxy hyz

/-- The quotient initial-algebra carrier generated from a quotient
presentation. -/
abbrev Carrier (Q : QuotientPresentation P) (i : ι) : Type u :=
  Quotient (setoid Q i)

/-- The quotient map from the polynomial initial algebra. -/
def ofMu (Q : QuotientPresentation P) {i : ι} (x : Mu P i) : Carrier Q i :=
  Quotient.mk (setoid Q i) x

theorem sound (Q : QuotientPresentation P) {i : ι} {x y : Mu P i}
    (h : Rel Q i x y) : ofMu Q x = ofMu Q y :=
  Quotient.sound h

theorem exact (Q : QuotientPresentation P) {i : ι} {x y : Mu P i}
    (h : ofMu Q x = ofMu Q y) : Rel Q i x y :=
  Quotient.exact h

/-- Introduce a raw polynomial constructor layer into the quotient carrier. -/
def innRaw (Q : QuotientPresentation P) {i : ι}
    (x : Obj P (Mu P) i) : Carrier Q i :=
  ofMu Q (Mu.inn x)

theorem innRaw_eq (Q : QuotientPresentation P) {i : ι}
    (x : Obj P (Mu P) i) :
    innRaw Q x = ofMu Q (Mu.inn x) :=
  rfl

/-- Constructor-layer quotient equations are respected by raw quotient
introduction. -/
theorem innRaw_layer_sound (Q : QuotientPresentation P) {i : ι}
    {x y : Obj P (Mu P) i} (h : Q.LayerRel i x y) :
    innRaw Q x = innRaw Q y :=
  sound Q (Rel.layer h)

/-- Recursor for quotient presentations. A fold over `Mu P` descends exactly
when it respects the generated quotient relation. -/
def recCarrier (Q : QuotientPresentation P) {A : ι → Type v}
    (alg : ∀ i, Obj P A i → A i)
    (respect :
      ∀ {i : ι} {x y : Mu P i},
        Rel Q i x y → Mu.fold alg i x = Mu.fold alg i y) :
    ∀ i, Carrier Q i → A i :=
  fun i =>
    Quotient.lift (Mu.fold alg i)
      (by
        intro x y hxy
        exact respect hxy)

@[simp]
theorem rec_ofMu (Q : QuotientPresentation P) {A : ι → Type v}
    (alg : ∀ i, Obj P A i → A i)
    (respect :
      ∀ {i : ι} {x y : Mu P i},
        Rel Q i x y → Mu.fold alg i x = Mu.fold alg i y)
    {i : ι} (x : Mu P i) :
    recCarrier Q alg respect i (ofMu Q x) = Mu.fold alg i x :=
  rfl

/-- Quotient induction for a property of the quotient carrier. -/
theorem ind (Q : QuotientPresentation P)
    {motive : ∀ i, Carrier Q i → Prop}
    (mk : ∀ i (x : Mu P i), motive i (ofMu Q x)) :
    ∀ i (x : Carrier Q i), motive i x :=
  fun i x => Quotient.inductionOn x (mk i)

/-- Transport the generated quotient relation from `Mu P` to a readable syntax
family through an isomorphism `Mu P i ≃ syntax i`. -/
def SyntaxRel (Q : QuotientPresentation P) {Syntax : ι → Type v}
    (syntaxIso : ∀ i, Mu P i ≃ᵢ Syntax i)
    (i : ι) (x y : Syntax i) : Prop :=
  Rel Q i ((syntaxIso i).invFun x) ((syntaxIso i).invFun y)

/-- The transported readable-syntax quotient relation as a setoid. -/
def syntaxSetoid (Q : QuotientPresentation P) {Syntax : ι → Type v}
    (syntaxIso : ∀ i, Mu P i ≃ᵢ Syntax i) (i : ι) : Setoid (Syntax i) where
  r := SyntaxRel Q syntaxIso i
  iseqv := by
    refine ⟨?_, ?_, ?_⟩
    · intro x
      exact Rel.refl ((syntaxIso i).invFun x)
    · intro x y hxy
      exact Rel.symm hxy
    · intro x y z hxy hyz
      exact Rel.trans hxy hyz

/-- The readable-syntax quotient generated by transporting `Q` through an
isomorphism to the polynomial initial algebra. -/
abbrev SyntaxCarrier (Q : QuotientPresentation P) {Syntax : ι → Type v}
    (syntaxIso : ∀ i, Mu P i ≃ᵢ Syntax i) (i : ι) : Type v :=
  Quotient (syntaxSetoid Q syntaxIso i)

/-- A readable-syntax quotient transported through `syntaxIso` is canonically
the quotient-polynomial carrier. -/
def syntaxCarrierIso (Q : QuotientPresentation P) {Syntax : ι → Type v}
    (syntaxIso : ∀ i, Mu P i ≃ᵢ Syntax i) (i : ι) :
    SyntaxCarrier Q syntaxIso i ≃ᵢ Carrier Q i where
  toFun :=
    Quotient.lift
      (fun (x : Syntax i) => ofMu Q ((syntaxIso i).invFun x))
      (by
        intro x y hxy
        exact sound Q hxy)
  invFun :=
    Quotient.lift
      (fun (x : Mu P i) =>
        Quotient.mk (syntaxSetoid Q syntaxIso i) ((syntaxIso i).toFun x))
      (by
        intro x y hxy
        apply Quotient.sound
        change Rel Q i
          ((syntaxIso i).invFun ((syntaxIso i).toFun x))
          ((syntaxIso i).invFun ((syntaxIso i).toFun y))
        rw [(syntaxIso i).left_inv x, (syntaxIso i).left_inv y]
        exact hxy)
  left_inv := by
    intro q
    exact Quotient.ind (s := syntaxSetoid Q syntaxIso i)
      (motive := fun q => Quotient.lift
        (fun (x : Mu P i) =>
          Quotient.mk (syntaxSetoid Q syntaxIso i) ((syntaxIso i).toFun x))
        (by
          intro x y hxy
          apply Quotient.sound
          change Rel Q i
            ((syntaxIso i).invFun ((syntaxIso i).toFun x))
            ((syntaxIso i).invFun ((syntaxIso i).toFun y))
          rw [(syntaxIso i).left_inv x, (syntaxIso i).left_inv y]
          exact hxy)
        (Quotient.lift
          (fun (x : Syntax i) => ofMu Q ((syntaxIso i).invFun x))
          (by
            intro x y hxy
            exact sound Q hxy)
          q) = q)
      (fun x => by
        simp
        change Quotient.mk (syntaxSetoid Q syntaxIso i)
            ((syntaxIso i).toFun ((syntaxIso i).invFun x))
          = Quotient.mk (syntaxSetoid Q syntaxIso i) x
        rw [(syntaxIso i).right_inv x])
      q
  right_inv := by
    intro q
    exact Quotient.ind (s := setoid Q i)
      (motive := fun q => Quotient.lift
        (fun (x : Syntax i) => ofMu Q ((syntaxIso i).invFun x))
        (by
          intro x y hxy
          exact sound Q hxy)
        (Quotient.lift
          (fun (x : Mu P i) =>
            Quotient.mk (syntaxSetoid Q syntaxIso i) ((syntaxIso i).toFun x))
          (by
            intro x y hxy
            apply Quotient.sound
            change Rel Q i
              ((syntaxIso i).invFun ((syntaxIso i).toFun x))
              ((syntaxIso i).invFun ((syntaxIso i).toFun y))
            rw [(syntaxIso i).left_inv x, (syntaxIso i).left_inv y]
            exact hxy)
          q) = q)
      (fun x => by
        change ofMu Q ((syntaxIso i).invFun ((syntaxIso i).toFun x)) =
          ofMu Q x
        rw [(syntaxIso i).left_inv x])
      q

/-- The code-side relation obtained by transporting a quotient relation across
an existing well-founded coding of the prequotient initial algebra. -/
def CodeRel (Q : QuotientPresentation P) {Code : ι → Type v}
    (C : WellFoundedCode P Code) (i : ι) (a b : Code i) : Prop :=
  Rel Q i (C.decode i a) (C.decode i b)

/-- The transported code relation bundled as an explicit setoid. -/
def codeSetoid (Q : QuotientPresentation P) {Code : ι → Type v}
    (C : WellFoundedCode P Code) (i : ι) : Setoid (Code i) where
  r := CodeRel Q C i
  iseqv := by
    refine ⟨?_, ?_, ?_⟩
    · intro x
      exact Rel.refl (C.decode i x)
    · intro x y h
      exact Rel.symm h
    · intro x y z hxy hyz
      exact Rel.trans hxy hyz

/-- The canonical code carrier for a quotient datatype: quotient the generated
prequotient code by the transported quotient relation. -/
abbrev CodeCarrier (Q : QuotientPresentation P) {Code : ι → Type v}
    (C : WellFoundedCode P Code) (i : ι) : Type v :=
  Quotient (codeSetoid Q C i)

/-- Encode a quotient datatype into the quotient of an existing generated code
family. -/
def encodeCodeCarrier (Q : QuotientPresentation P) {Code : ι → Type v}
    (C : WellFoundedCode P Code) (i : ι) :
    Carrier Q i → CodeCarrier Q C i :=
  Quotient.lift
    (fun x => Quotient.mk (codeSetoid Q C i) (C.encode i x))
    (by
      intro x y hxy
      apply Quotient.sound
      change Rel Q i (C.decode i (C.encode i x))
        (C.decode i (C.encode i y))
      rw [WellFoundedCode.decode_encode C i x,
        WellFoundedCode.decode_encode C i y]
      exact hxy)

/-- Decode a quotient of an existing generated code family into the quotient
datatype. -/
def decodeCodeCarrier (Q : QuotientPresentation P) {Code : ι → Type v}
    (C : WellFoundedCode P Code) (i : ι) :
    CodeCarrier Q C i → Carrier Q i :=
  Quotient.lift
    (fun z => ofMu Q (C.decode i z))
    (by
      intro a b hab
      exact sound Q hab)

/--
Any well-founded coding of the prequotient initial algebra induces a canonical
bijection between the quotient datatype and the quotient of the generated code
family by the transported relation.
-/
def codeIso (Q : QuotientPresentation P) {Code : ι → Type v}
    (C : WellFoundedCode P Code) (i : ι) :
    Carrier Q i ≃ᵢ CodeCarrier Q C i where
  toFun := encodeCodeCarrier Q C i
  invFun := decodeCodeCarrier Q C i
  left_inv := by
    intro q
    exact Quotient.ind (s := setoid Q i)
      (motive := fun q => decodeCodeCarrier Q C i (encodeCodeCarrier Q C i q) = q)
      (fun x => by
        change Quotient.mk (setoid Q i) (C.decode i (C.encode i x)) =
          Quotient.mk (setoid Q i) x
        rw [WellFoundedCode.decode_encode C i x])
      q
  right_inv := by
    intro q
    exact Quotient.ind (s := codeSetoid Q C i)
      (motive := fun q => encodeCodeCarrier Q C i (decodeCodeCarrier Q C i q) = q)
      (fun z => by
        change Quotient.mk (codeSetoid Q C i) (C.encode i (C.decode i z)) =
          Quotient.mk (codeSetoid Q C i) z
        rw [WellFoundedCode.encode_decode C i z])
      q

/--
Criterion for replacing the quotient of a generated code family by a concrete
carrier.  The candidate encoder must respect the transported quotient
relation, and its decoder must be inverse up to that relation.
-/
structure DescendedCode (Q : QuotientPresentation P) {Code : ι → Type v}
    (C : WellFoundedCode P Code) (Out : ι → Type w) where
  encode : ∀ i, Code i → Out i
  decode : ∀ i, Out i → Code i
  encode_respects :
    ∀ {i : ι} {a b : Code i}, CodeRel Q C i a b → encode i a = encode i b
  decode_encode_rel :
    ∀ i (a : Code i), CodeRel Q C i (decode i (encode i a)) a
  encode_decode :
    ∀ i (z : Out i), encode i (decode i z) = z

namespace DescendedCode

variable {Q : QuotientPresentation P} {Code : ι → Type v}
variable {C : WellFoundedCode P Code} {Out : ι → Type w}

/-- A descended code criterion gives a bijection from the quotient code carrier
to the concrete carrier. -/
def codeCarrierIso (D : DescendedCode Q C Out) (i : ι) :
    CodeCarrier Q C i ≃ᵢ Out i where
  toFun :=
    Quotient.lift (D.encode i)
      (by
        intro a b hab
        exact D.encode_respects hab)
  invFun := fun z => Quotient.mk (codeSetoid Q C i) (D.decode i z)
  left_inv := by
    intro q
    exact Quotient.ind (s := codeSetoid Q C i)
      (motive := fun q =>
        Quotient.mk (codeSetoid Q C i)
            (D.decode i (Quotient.lift (D.encode i)
              (by
                intro a b hab
                exact D.encode_respects hab) q)) = q)
      (fun a => by
        apply Quotient.sound
        change CodeRel Q C i (D.decode i (D.encode i a)) a
        exact D.decode_encode_rel i a)
      q
  right_inv := by
    intro z
    exact D.encode_decode i z

/-- A descended code criterion gives a concrete coding of the quotient
datatype. -/
def carrierIso (D : DescendedCode Q C Out) (i : ι) :
    Carrier Q i ≃ᵢ Out i :=
  Iso.trans (codeIso Q C i) (codeCarrierIso D i)

end DescendedCode

end QuotientPresentation

end DepPoly
end BijForm
