import BijForm.DependentPolynomial

namespace BijForm
namespace DepPoly

universe u v

variable {ι : Type u}

namespace Obj

/-- Functorial action on one dependent-polynomial layer. -/
def map {P : DepPoly ι} {X Y : ι → Type v}
    (f : ∀ i, X i → Y i) {i : ι} (x : Obj P X i) : Obj P Y i where
  ctor := x.ctor
  param := x.param
  out_eq := x.out_eq
  child := fun q => f (P.input x.param q) (x.child q)

@[simp]
theorem map_ctor {P : DepPoly ι} {X Y : ι → Type v}
    (f : ∀ i, X i → Y i) {i : ι} (x : Obj P X i) :
    (map f x).ctor = x.ctor :=
  rfl

@[simp]
theorem map_param {P : DepPoly ι} {X Y : ι → Type v}
    (f : ∀ i, X i → Y i) {i : ι} (x : Obj P X i) :
    (map f x).param = x.param :=
  rfl

@[simp]
theorem map_child {P : DepPoly ι} {X Y : ι → Type v}
    (f : ∀ i, X i → Y i) {i : ι} (x : Obj P X i)
    (q : P.Pos x.ctor x.param) :
    (map f x).child q = f (P.input x.param q) (x.child q) :=
  rfl

end Obj

/--
A project-native quotient presentation for a dependent-polynomial initial
algebra.

`LayerRel i x y` is the constructor-layer abstraction relation at index `i`.
The generated relation on `Mu P i` closes it under recursive congruence,
symmetry, and transitivity.  This is the concrete indexed analogue of the
QPF `abs` equality rule used by Avigad-Carneiro-Hudon.
-/
structure QuotientPresentation (P : DepPoly ι) where
  LayerRel : ∀ i, Obj P (Mu P) i → Obj P (Mu P) i → Prop

namespace QuotientPresentation

variable {P : DepPoly ι}

/-- The equivalence relation on the polynomial initial algebra generated by a
constructor-layer quotient presentation. -/
inductive Rel (Q : QuotientPresentation P) :
    ∀ i, Mu P i → Mu P i → Prop
  | refl {i : ι} (x : Mu P i) : Rel Q i x x
  | layer {i : ι} {x y : Obj P (Mu P) i} :
      Q.LayerRel i x y → Rel Q i (Mu.inn x) (Mu.inn y)
  | congr {i : ι} {c : P.Ctor} {p : P.Param c}
      {h : P.out c p = i}
      {child child' : (q : P.Pos c p) → Mu P (P.input p q)} :
      (∀ q, Rel Q (P.input p q) (child q) (child' q)) →
        Rel Q i (Mu.sup c p h child) (Mu.sup c p h child')
  | symm {i : ι} {x y : Mu P i} :
      Rel Q i x y → Rel Q i y x
  | trans {i : ι} {x y z : Mu P i} :
      Rel Q i x y → Rel Q i y z → Rel Q i x z

/-- The quotient initial-algebra carrier generated from a quotient
presentation. -/
abbrev Carrier (Q : QuotientPresentation P) (i : ι) : Type u :=
  Quot (Rel Q i)

/-- The quotient map from the polynomial initial algebra. -/
def ofMu (Q : QuotientPresentation P) {i : ι} (x : Mu P i) : Carrier Q i :=
  Quot.mk (Rel Q i) x

theorem sound (Q : QuotientPresentation P) {i : ι} {x y : Mu P i}
    (h : Rel Q i x y) : ofMu Q x = ofMu Q y :=
  Quot.sound h

/-- The code-side relation obtained by transporting a quotient relation across
an existing well-founded coding of the prequotient initial algebra. -/
def CodeRel (Q : QuotientPresentation P) {Code : ι → Type v}
    (C : WellFoundedCode P Code) (i : ι) (a b : Code i) : Prop :=
  Rel Q i (C.decode i a) (C.decode i b)

/-- The canonical code carrier for a quotient datatype: quotient the generated
prequotient code by the transported quotient relation. -/
abbrev CodeCarrier (Q : QuotientPresentation P) {Code : ι → Type v}
    (C : WellFoundedCode P Code) (i : ι) : Type v :=
  Quot (CodeRel Q C i)

/-- Encode a quotient datatype into the quotient of an existing generated code
family. -/
def encodeCodeCarrier (Q : QuotientPresentation P) {Code : ι → Type v}
    (C : WellFoundedCode P Code) (i : ι) :
    Carrier Q i → CodeCarrier Q C i :=
  Quot.lift
    (fun x => Quot.mk (CodeRel Q C i) (C.encode i x))
    (by
      intro x y hxy
      apply Quot.sound
      change Rel Q i (C.decode i (C.encode i x))
        (C.decode i (C.encode i y))
      rw [WellFoundedCode.decode_encode C i x,
        WellFoundedCode.decode_encode C i y]
      exact hxy)

/-- Decode a quotient of an existing generated code family into the quotient
datatype. -/
def decodeCodeCarrier (Q : QuotientPresentation P) {Code : ι → Type v}
    (C : WellFoundedCode P Code) (i : ι) :
    CodeCarrier Q C i → Carrier Q i :=
  Quot.lift
    (fun z => ofMu Q (C.decode i z))
    (by
      intro a b hab
      exact sound Q hab)

/--
Any well-founded coding of the prequotient initial algebra induces a canonical
bijection between the quotient datatype and the quotient of the generated code
family by the transported relation.
-/
def codeIso (Q : QuotientPresentation P) {Code : ι → Type v}
    (C : WellFoundedCode P Code) (i : ι) :
    Carrier Q i ≃ᵢ CodeCarrier Q C i where
  toFun := encodeCodeCarrier Q C i
  invFun := decodeCodeCarrier Q C i
  left_inv := by
    intro q
    exact Quot.ind (r := Rel Q i)
      (β := fun q => decodeCodeCarrier Q C i (encodeCodeCarrier Q C i q) = q)
      (fun x => by
        change decodeCodeCarrier Q C i
            (encodeCodeCarrier Q C i (ofMu Q x)) = ofMu Q x
        simp [encodeCodeCarrier, decodeCodeCarrier, ofMu]
        rw [WellFoundedCode.decode_encode C i x])
      q
  right_inv := by
    intro q
    exact Quot.ind (r := CodeRel Q C i)
      (β := fun q => encodeCodeCarrier Q C i (decodeCodeCarrier Q C i q) = q)
      (fun z => by
        change encodeCodeCarrier Q C i
            (decodeCodeCarrier Q C i (Quot.mk (CodeRel Q C i) z))
          = Quot.mk (CodeRel Q C i) z
        simp [encodeCodeCarrier, decodeCodeCarrier, ofMu]
        rw [WellFoundedCode.encode_decode C i z])
      q

end QuotientPresentation

end DepPoly
end BijForm
