import BijForm.InitialAlgebra
import BijForm.CodeAlgebra

namespace BijForm

macro "unordered_pair_nat_quotient_rank_descent "
    "[" defs:Lean.Parser.Tactic.simpLemma,* "]" : tactic =>
  `(tactic|
    rintro idx z ctor param out_eq child hdecode q <;>
    cases idx with
    | zero =>
        dsimp [$defs,*] at hdecode
        cases hdecode
        cases q
    | succ m =>
        dsimp [$defs,*] at hdecode
        cases hsum : CodeAlgebra.sumNat.invFun z with
        | inl label =>
            rw [hsum] at hdecode
            cases hdecode
            cases q
        | inr pairCode =>
            rw [hsum] at hdecode
            cases hdecode
            have hz := Iso.toFun_eq_of_invFun_eq CodeAlgebra.sumNat hsum
            cases q
            · exact Nat.lt_of_lt_of_eq
                (CodeAlgebra.unorderedPairNat_invFun_fst_lt_sumNat_inr pairCode)
                hz
            · exact Nat.lt_of_lt_of_eq
                (CodeAlgebra.unorderedPairNat_invFun_snd_lt_sumNat_inr pairCode)
                hz)

namespace DepPoly

universe u v w

variable {ι : Type u}

namespace Obj

/-- Functorial action on one dependent-polynomial layer. -/
def map {P : DepPoly ι} {X : ι → Type v} {Y : ι → Type w}
    (f : ∀ i, X i → Y i) {i : ι} (x : Obj P X i) : Obj P Y i where
  ctor := x.ctor
  param := x.param
  out_eq := x.out_eq
  child := fun q => f (P.input x.param q) (x.child q)

@[simp]
theorem map_ctor {P : DepPoly ι} {X : ι → Type v} {Y : ι → Type w}
    (f : ∀ i, X i → Y i) {i : ι} (x : Obj P X i) :
    (map f x).ctor = x.ctor :=
  rfl

@[simp]
theorem map_param {P : DepPoly ι} {X : ι → Type v} {Y : ι → Type w}
    (f : ∀ i, X i → Y i) {i : ι} (x : Obj P X i) :
    (map f x).param = x.param :=
  rfl

@[simp]
theorem map_child {P : DepPoly ι} {X : ι → Type v} {Y : ι → Type w}
    (f : ∀ i, X i → Y i) {i : ι} (x : Obj P X i)
    (q : P.Pos x.ctor x.param) :
    (map f x).child q = f (P.input x.param q) (x.child q) :=
  rfl

end Obj

/--
A project-native quotient presentation for a dependent-polynomial initial
algebra.

`LayerRel i x y` is the constructor-layer abstraction relation at index `i`.
The generated relation on `Mu P i` closes it under recursive congruence,
symmetry, and transitivity.  This is the concrete indexed analogue of the
QPF `abs` equality rule used by Avigad-Carneiro-Hudon.
-/
structure QuotientPresentation (P : DepPoly ι) where
  LayerRel : ∀ i, Obj P (Mu P) i → Obj P (Mu P) i → Prop

namespace QuotientPresentation

variable {P : DepPoly ι}

/-- The equivalence relation on the polynomial initial algebra generated by a
constructor-layer quotient presentation. -/
inductive Rel (Q : QuotientPresentation P) :
    ∀ i, Mu P i → Mu P i → Prop
  | refl {i : ι} (x : Mu P i) : Rel Q i x x
  | layer {i : ι} {x y : Obj P (Mu P) i} :
      Q.LayerRel i x y → Rel Q i (Mu.inn x) (Mu.inn y)
  | congr {i : ι} {c : P.Ctor} {p : P.Param c}
      {h : P.out c p = i}
      {child child' : (q : P.Pos c p) → Mu P (P.input p q)} :
      (∀ q, Rel Q (P.input p q) (child q) (child' q)) →
        Rel Q i (Mu.sup c p h child) (Mu.sup c p h child')
  | symm {i : ι} {x y : Mu P i} :
      Rel Q i x y → Rel Q i y x
  | trans {i : ι} {x y z : Mu P i} :
      Rel Q i x y → Rel Q i y z → Rel Q i x z

namespace Rel

theorem respects_of_layer_congr
    (Q : QuotientPresentation P)
    {Out : ι → Type w}
    (normalize : ∀ i, Mu P i → Out i)
    (layer_respects :
      ∀ {i : ι} {x y : Obj P (Mu P) i},
        Q.LayerRel i x y →
          normalize i (Mu.inn x) = normalize i (Mu.inn y))
    (congr_respects :
      ∀ {i : ι} {c : P.Ctor} {p : P.Param c}
        {h : P.out c p = i}
        {child child' : (q : P.Pos c p) → Mu P (P.input p q)},
        (∀ q,
          normalize (P.input p q) (child q) =
            normalize (P.input p q) (child' q)) →
          normalize i (Mu.sup c p h child) =
            normalize i (Mu.sup c p h child')) :
    ∀ {i : ι} {x y : Mu P i}, Rel Q i x y →
      normalize i x = normalize i y := by
  intro i x y hxy
  induction hxy with
  | refl x => rfl
  | layer h => exact layer_respects h
  | congr hchild ih => exact congr_respects ih
  | symm _ ih => exact ih.symm
  | trans _ _ ihxy ihyz => exact ihxy.trans ihyz

theorem unorderedPair_decode_encode_repair
    (Q : QuotientPresentation P)
    {childIndex outIndex : ι}
    (normalize : Mu P childIndex → Nat)
    (denormalize : Nat → Mu P childIndex)
    (mk : Mu P childIndex → Mu P childIndex → Mu P outIndex)
    (lhs rhs : Mu P childIndex)
    {target : Mu P outIndex}
    (hleft : Rel Q childIndex (denormalize (normalize lhs)) lhs)
    (hright : Rel Q childIndex (denormalize (normalize rhs)) rhs)
    (branch_congr :
      ∀ {a a' b b' : Mu P childIndex},
        Rel Q childIndex a a' →
        Rel Q childIndex b b' →
          Rel Q outIndex (mk a b) (mk a' b'))
    (branch_swap :
      ∀ a b : Mu P childIndex, Rel Q outIndex (mk a b) (mk b a))
    (branch_eta : Rel Q outIndex (mk lhs rhs) target) :
    Rel Q outIndex
      (mk
        (denormalize
          (CodeAlgebra.unorderedPairNat.invFun
            (CodeAlgebra.unorderedPairCode (normalize lhs) (normalize rhs))).val.1)
        (denormalize
          (CodeAlgebra.unorderedPairNat.invFun
            (CodeAlgebra.unorderedPairCode (normalize lhs) (normalize rhs))).val.2))
      target := by
  by_cases hle : normalize lhs ≤ normalize rhs
  · rw [CodeAlgebra.unorderedPairNat_inv_unorderedPairCode_of_le hle]
    exact Rel.trans (branch_congr hleft hright) branch_eta
  · rw [CodeAlgebra.unorderedPairNat_inv_unorderedPairCode_of_not_le hle]
    exact Rel.trans (branch_congr hright hleft)
      (Rel.trans (branch_swap rhs lhs) branch_eta)

theorem unorderedPair_code_decode_encode_repair
    (Q : QuotientPresentation P)
    {outIndex : ι}
    (mk : Nat → Nat → Mu P outIndex)
    (lhs rhs : Nat)
    (branch_swap :
      ∀ a b : Nat, Rel Q outIndex (mk a b) (mk b a)) :
    Rel Q outIndex
      (mk
        (CodeAlgebra.unorderedPairNat.invFun
          (CodeAlgebra.unorderedPairCode lhs rhs)).val.1
        (CodeAlgebra.unorderedPairNat.invFun
          (CodeAlgebra.unorderedPairCode lhs rhs)).val.2)
      (mk lhs rhs) := by
  by_cases hle : lhs ≤ rhs
  · rw [CodeAlgebra.unorderedPairNat_inv_unorderedPairCode_of_le hle]
    exact Rel.refl _
  · rw [CodeAlgebra.unorderedPairNat_inv_unorderedPairCode_of_not_le hle]
    exact branch_swap rhs lhs

end Rel

/-- The generated quotient relation bundled as an explicit setoid, so quotient
equality can be reflected back to the generated relation when proving
constructor well-definedness. -/
def setoid (Q : QuotientPresentation P) (i : ι) : Setoid (Mu P i) where
  r := Rel Q i
  iseqv := by
    refine ⟨?_, ?_, ?_⟩
    · intro x
      exact Rel.refl x
    · intro x y h
      exact Rel.symm h
    · intro x y z hxy hyz
      exact Rel.trans hxy hyz

/-- The quotient initial-algebra carrier generated from a quotient
presentation. -/
abbrev Carrier (Q : QuotientPresentation P) (i : ι) : Type u :=
  Quotient (setoid Q i)

/-- The quotient map from the polynomial initial algebra. -/
def ofMu (Q : QuotientPresentation P) {i : ι} (x : Mu P i) : Carrier Q i :=
  Quotient.mk (setoid Q i) x

theorem sound (Q : QuotientPresentation P) {i : ι} {x y : Mu P i}
    (h : Rel Q i x y) : ofMu Q x = ofMu Q y :=
  Quotient.sound h

theorem exact (Q : QuotientPresentation P) {i : ι} {x y : Mu P i}
    (h : ofMu Q x = ofMu Q y) : Rel Q i x y :=
  Quotient.exact h

/-- Introduce a raw polynomial constructor layer into the quotient carrier. -/
def innRaw (Q : QuotientPresentation P) {i : ι}
    (x : Obj P (Mu P) i) : Carrier Q i :=
  ofMu Q (Mu.inn x)

theorem innRaw_eq (Q : QuotientPresentation P) {i : ι}
    (x : Obj P (Mu P) i) :
    innRaw Q x = ofMu Q (Mu.inn x) :=
  rfl

/-- Constructor-layer quotient equations are respected by raw quotient
introduction. -/
theorem innRaw_layer_sound (Q : QuotientPresentation P) {i : ι}
    {x y : Obj P (Mu P) i} (h : Q.LayerRel i x y) :
    innRaw Q x = innRaw Q y :=
  sound Q (Rel.layer h)

/-- Recursor for quotient presentations. A fold over `Mu P` descends exactly
when it respects the generated quotient relation. -/
def recCarrier (Q : QuotientPresentation P) {A : ι → Type v}
    (alg : ∀ i, Obj P A i → A i)
    (respect :
      ∀ {i : ι} {x y : Mu P i},
        Rel Q i x y → Mu.fold alg i x = Mu.fold alg i y) :
    ∀ i, Carrier Q i → A i :=
  fun i =>
    Quotient.lift (Mu.fold alg i)
      (by
        intro x y hxy
        exact respect hxy)

@[simp]
theorem rec_ofMu (Q : QuotientPresentation P) {A : ι → Type v}
    (alg : ∀ i, Obj P A i → A i)
    (respect :
      ∀ {i : ι} {x y : Mu P i},
        Rel Q i x y → Mu.fold alg i x = Mu.fold alg i y)
    {i : ι} (x : Mu P i) :
    recCarrier Q alg respect i (ofMu Q x) = Mu.fold alg i x :=
  rfl

/-- Quotient induction for a property of the quotient carrier. -/
theorem ind (Q : QuotientPresentation P)
    {motive : ∀ i, Carrier Q i → Prop}
    (mk : ∀ i (x : Mu P i), motive i (ofMu Q x)) :
    ∀ i (x : Carrier Q i), motive i x :=
  fun i x => Quotient.inductionOn x (mk i)

/-- Transport the generated quotient relation from `Mu P` to a readable syntax
family through an isomorphism `Mu P i ≃ syntax i`. -/
def SyntaxRel (Q : QuotientPresentation P) {Syntax : ι → Type v}
    (syntaxIso : ∀ i, Mu P i ≃ᵢ Syntax i)
    (i : ι) (x y : Syntax i) : Prop :=
  (Iso.transportSetoid (syntaxIso i) (setoid Q i)).r x y

/-- The transported readable-syntax quotient relation as a setoid. -/
def syntaxSetoid (Q : QuotientPresentation P) {Syntax : ι → Type v}
    (syntaxIso : ∀ i, Mu P i ≃ᵢ Syntax i) (i : ι) : Setoid (Syntax i) :=
  Iso.transportSetoid (syntaxIso i) (setoid Q i)

/-- The readable-syntax quotient generated by transporting `Q` through an
isomorphism to the polynomial initial algebra. -/
abbrev SyntaxCarrier (Q : QuotientPresentation P) {Syntax : ι → Type v}
    (syntaxIso : ∀ i, Mu P i ≃ᵢ Syntax i) (i : ι) : Type v :=
  Quotient (syntaxSetoid Q syntaxIso i)

/-- A readable-syntax quotient transported through `syntaxIso` is canonically
the quotient-polynomial carrier. -/
def syntaxCarrierIso (Q : QuotientPresentation P) {Syntax : ι → Type v}
    (syntaxIso : ∀ i, Mu P i ≃ᵢ Syntax i) (i : ι) :
    SyntaxCarrier Q syntaxIso i ≃ᵢ Carrier Q i :=
  Iso.symm (Iso.quotientTransport (syntaxIso i) (setoid Q i))

/-- The code-side relation obtained by transporting a quotient relation across
an existing well-founded coding of the prequotient initial algebra. -/
def CodeRel (Q : QuotientPresentation P) {Code : ι → Type v}
    (C : WellFoundedCode P Code) (i : ι) (a b : Code i) : Prop :=
  (Iso.transportSetoid (C.iso i) (setoid Q i)).r a b

/-- The transported code relation bundled as an explicit setoid. -/
def codeSetoid (Q : QuotientPresentation P) {Code : ι → Type v}
    (C : WellFoundedCode P Code) (i : ι) : Setoid (Code i) :=
  Iso.transportSetoid (C.iso i) (setoid Q i)

/-- The canonical code carrier for a quotient datatype: quotient the generated
prequotient code by the transported quotient relation. -/
abbrev CodeCarrier (Q : QuotientPresentation P) {Code : ι → Type v}
    (C : WellFoundedCode P Code) (i : ι) : Type v :=
  Quotient (codeSetoid Q C i)

/-- The code-side relation transported across generated coding data. -/
def GeneratedCodeRel (Q : QuotientPresentation P) {Code : ι → Type v}
    (C : GeneratedCode P Code) (i : ι) (a b : Code i) : Prop :=
  CodeRel Q C.toWellFoundedCode i a b

/-- The generated-code quotient carrier, keeping generated coding data visible
at the quotient API boundary. -/
abbrev GeneratedCodeCarrier (Q : QuotientPresentation P) {Code : ι → Type v}
    (C : GeneratedCode P Code) (i : ι) : Type v :=
  CodeCarrier Q C.toWellFoundedCode i

/--
Any well-founded coding of the prequotient initial algebra induces a canonical
bijection between the quotient datatype and the quotient of the generated code
family by the transported relation.
-/
def codeIso (Q : QuotientPresentation P) {Code : ι → Type v}
    (C : WellFoundedCode P Code) (i : ι) :
    Carrier Q i ≃ᵢ CodeCarrier Q C i :=
  Iso.quotientTransport (C.iso i) (setoid Q i)

/-- Generated-code-facing form of `codeIso`. -/
def generatedCodeIso (Q : QuotientPresentation P) {Code : ι → Type v}
    (C : GeneratedCode P Code) (i : ι) :
    Carrier Q i ≃ᵢ GeneratedCodeCarrier Q C i :=
  codeIso Q C.toWellFoundedCode i

/--
Criterion for replacing the quotient of a generated code family by a concrete
carrier.  The candidate encoder must respect the transported quotient
relation, and its decoder must be inverse up to that relation.
-/
structure DescendedCode (Q : QuotientPresentation P) {Code : ι → Type v}
    (C : WellFoundedCode P Code) (Out : ι → Type w) where
  encode : ∀ i, Code i → Out i
  decode : ∀ i, Out i → Code i
  encode_respects :
    ∀ {i : ι} {a b : Code i}, CodeRel Q C i a b → encode i a = encode i b
  decode_encode_rel :
    ∀ i (a : Code i), CodeRel Q C i (decode i (encode i a)) a
  encode_decode :
    ∀ i (z : Out i), encode i (decode i z) = z

namespace DescendedCode

variable {Q : QuotientPresentation P} {Code : ι → Type v}
variable {C : WellFoundedCode P Code} {Out : ι → Type w}

def normalForm (D : DescendedCode Q C Out) (i : ι) :
    QuotientNormalForm (codeSetoid Q C i) (Out i) where
  encode := D.encode i
  decode := D.decode i
  encode_respects := by
    intro a b hab
    exact D.encode_respects hab
  decode_encode_rel := by
    intro a
    change CodeRel Q C i (D.decode i (D.encode i a)) a
    exact D.decode_encode_rel i a
  encode_decode := by
    intro z
    exact D.encode_decode i z

/-- A descended code criterion gives a bijection from the quotient code carrier
to the concrete carrier. -/
def codeCarrierIso (D : DescendedCode Q C Out) (i : ι) :
    CodeCarrier Q C i ≃ᵢ Out i :=
  (D.normalForm i).quotientIso

/-- A descended code criterion gives a concrete coding of the quotient
datatype. -/
def carrierIso (D : DescendedCode Q C Out) (i : ι) :
    Carrier Q i ≃ᵢ Out i :=
  Iso.trans (codeIso Q C i) (codeCarrierIso D i)

end DescendedCode

/-- Generated-code-facing descent criterion. -/
abbrev DescendedGeneratedCode
    (Q : QuotientPresentation P) {Code : ι → Type v}
    (C : GeneratedCode P Code) (Out : ι → Type w) : Type (max u v w) :=
  DescendedCode Q C.toWellFoundedCode Out

namespace DescendedGeneratedCode

variable {Q : QuotientPresentation P} {Code : ι → Type v}
variable {C : GeneratedCode P Code} {Out : ι → Type w}

def ofMuNormalizer
    (normalize : ∀ i, Mu P i → Out i)
    (denormalize : ∀ i, Out i → Mu P i)
    (normalize_respects :
      ∀ {i : ι} {x y : Mu P i}, Rel Q i x y →
        normalize i x = normalize i y)
    (denormalize_normalize_rel :
      ∀ i (x : Mu P i), Rel Q i (denormalize i (normalize i x)) x)
    (normalize_denormalize :
      ∀ i (z : Out i), normalize i (denormalize i z) = z) :
    DescendedGeneratedCode Q C Out where
  encode i a := normalize i (C.decode i a)
  decode i z := C.encode i (denormalize i z)
  encode_respects := by
    intro i a b hab
    exact normalize_respects hab
  decode_encode_rel := by
    intro i a
    change Rel Q i
      (C.toWellFoundedCode.decode i
      (C.encode i
        (denormalize i (normalize i (C.decode i a)))))
      (C.toWellFoundedCode.decode i a)
    rw [show
      C.toWellFoundedCode.decode i
          (C.encode i (denormalize i (normalize i (C.decode i a)))) =
        denormalize i (normalize i (C.decode i a)) by
      exact C.toWellFoundedCode.decode_encode i _]
    exact denormalize_normalize_rel i (C.decode i a)
  encode_decode := by
    intro i z
    change normalize i
      (C.decode i (C.encode i (denormalize i z))) = z
    rw [show C.decode i (C.encode i (denormalize i z)) =
        denormalize i z by
      exact GeneratedCode.decode_encode C i _]
    exact normalize_denormalize i z

def codeCarrierIso (D : DescendedGeneratedCode Q C Out) (i : ι) :
    GeneratedCodeCarrier Q C i ≃ᵢ Out i :=
  DescendedCode.codeCarrierIso D i

def carrierIso (D : DescendedGeneratedCode Q C Out) (i : ι) :
    Carrier Q i ≃ᵢ Out i :=
  Iso.trans (generatedCodeIso Q C i) (codeCarrierIso D i)

end DescendedGeneratedCode

/--
One-layer normal-form data for a quotient presentation. The framework derives
the recursive normalizer and denormalizer; callers supply only layer-local
encoding, decoding, rank, quotient-generator preservation, and layer repair.
-/
structure LayerNormalForm
    (Q : QuotientPresentation P) (Out : ι → Type w) where
  encodeLayer : ∀ i, Obj P Out i → Out i
  decodeLayer : ∀ i, Out i → Obj P Out i
  rank : ∀ i, Out i → Nat
  child_rank_lt :
    ∀ {i : ι} (z : Out i)
      {c : P.Ctor} {p : P.Param c} {h : P.out c p = i}
      {child : (q : P.Pos c p) → Out (P.input p q)},
      decodeLayer i z = ⟨c, p, h, child⟩ →
        ∀ q, rank (P.input p q) (child q) < rank i z
  encode_decode_layer :
    ∀ i (z : Out i), encodeLayer i (decodeLayer i z) = z
  layer_rel_respects :
    ∀ {i : ι} {x y : Obj P (Mu P) i}
      (encodeChild : ∀ j, Mu P j → Out j),
      Q.LayerRel i x y →
        encodeLayer i (Obj.map encodeChild x) =
          encodeLayer i (Obj.map encodeChild y)
  decode_encode_layer_rel :
    ∀ {i : ι} (realize : ∀ j, Out j → Mu P j)
      (layer : Obj P Out i),
      Rel Q i
        (Mu.inn (Obj.map realize (decodeLayer i (encodeLayer i layer))))
        (Mu.inn (Obj.map realize layer))

namespace LayerNormalForm

variable {Q : QuotientPresentation P} {Out : ι → Type w}

def normalize (L : LayerNormalForm Q Out) : ∀ i, Mu P i → Out i
  | i, Mu.sup c p h child =>
      L.encodeLayer i
        ⟨c, p, h, fun q => normalize L (P.input p q) (child q)⟩

def denormalize (L : LayerNormalForm Q Out) : ∀ i, Out i → Mu P i
  | i, z =>
      let layer := L.decodeLayer i z
      Mu.sup layer.ctor layer.param layer.out_eq
        (fun q => denormalize L (P.input layer.param q) (layer.child q))
termination_by i z => L.rank i z
decreasing_by
  exact L.child_rank_lt z rfl q

theorem normalize_denormalize (L : LayerNormalForm Q Out) :
    ∀ i (z : Out i), L.normalize i (L.denormalize i z) = z
  | i, z => by
      let layer := L.decodeLayer i z
      have ih :
          (fun q => L.normalize (P.input layer.param q)
            (L.denormalize (P.input layer.param q) (layer.child q))) =
            layer.child := by
        funext q
        exact normalize_denormalize L (P.input layer.param q) (layer.child q)
      have hstep : L.encodeLayer i layer = z :=
        L.encode_decode_layer i z
      rw [denormalize, normalize]
      change L.encodeLayer i
          ⟨layer.ctor, layer.param, layer.out_eq, fun q =>
            L.normalize (P.input layer.param q)
              (L.denormalize (P.input layer.param q) (layer.child q))⟩ = z
      rw [ih]
      exact hstep
termination_by i z => L.rank i z
decreasing_by
  exact L.child_rank_lt z rfl q

theorem denormalize_normalize_rel (L : LayerNormalForm Q Out) :
    ∀ i (x : Mu P i), Rel Q i (L.denormalize i (L.normalize i x)) x
  | i, Mu.sup c p h child => by
      let layer : Obj P Out i :=
        ⟨c, p, h, fun q => L.normalize (P.input p q) (child q)⟩
      let realize : ∀ j, Out j → Mu P j := fun j z => L.denormalize j z
      have hrepair :
          Rel Q i
            (Mu.inn (Obj.map realize
              (L.decodeLayer i (L.encodeLayer i layer))))
            (Mu.inn (Obj.map realize layer)) :=
        L.decode_encode_layer_rel realize layer
      have hchildren :
          Rel Q i (Mu.inn (Obj.map realize layer))
            (Mu.sup c p h child) := by
        apply Rel.congr
        intro q
        exact denormalize_normalize_rel L (P.input p q) (child q)
      rw [normalize, denormalize]
      change
        Rel Q i
          (Mu.inn (Obj.map realize
            (L.decodeLayer i (L.encodeLayer i layer))))
          (Mu.sup c p h child)
      exact Rel.trans hrepair hchildren

theorem normalize_respects (L : LayerNormalForm Q Out) :
    ∀ {i : ι} {x y : Mu P i}, Rel Q i x y →
      L.normalize i x = L.normalize i y :=
  Rel.respects_of_layer_congr Q L.normalize
    (by
      intro i x y hxy
      exact L.layer_rel_respects L.normalize hxy)
    (by
      intro i c p h child child' ih
      simp [normalize]
      congr
      funext q
      exact ih q)

def descendedGeneratedCode
    (L : LayerNormalForm Q Out)
    {Code : ι → Type v} (C : GeneratedCode P Code) :
    DescendedGeneratedCode Q C Out :=
  DescendedGeneratedCode.ofMuNormalizer
    (C := C)
    L.normalize
    L.denormalize
    (by
      intro i x y hxy
      exact L.normalize_respects hxy)
    L.denormalize_normalize_rel
    L.normalize_denormalize

end LayerNormalForm

end QuotientPresentation

end DepPoly
end BijForm
