import BijForm.DependentTuple
import BijForm.InitialAlgebra
import BijForm.CodeAlgebra

namespace BijForm
namespace TypedBinding

open DepPoly

/-- One recursive argument of a typed binding constructor.  The argument is
checked under the surrounding context extended by `binders`, and must construct
an object of sort `sort`.  A nonbinding recursive argument has `binders = []`. -/
structure Arg (Ty : Type) where
  binders : List Ty
  sort : Ty

/-- A typed binding signature.  The constructor set may be infinite; each
constructor still has a finite list of recursive arguments. -/
structure Signature (Ty : Type) where
  Ctor : Type
  args : Ctor → List (Arg Ty)
  ret : Ctor → Ty

namespace Signature

variable {Ty : Type} (S : Signature Ty)

def ArgPos (c : S.Ctor) : Type :=
  Fin (S.args c).length

def arg (c : S.Ctor) (q : S.ArgPos c) : Arg Ty :=
  (S.args c).get q

end Signature

/-- Typed de Bruijn variables.  A variable of type `t` is available exactly
when the current context contains a `t`. -/
inductive Var {Ty : Type} : List Ty → Ty → Type
  | here {Γ : List Ty} {t : Ty} : Var (t :: Γ) t
  | there {Γ : List Ty} {t u : Ty} : Var Γ t → Var (u :: Γ) t

namespace Var

variable {Ty : Type}

def absurd_nil {t : Ty} : Var ([] : List Ty) t → Empty
  | v => nomatch v

def count [DecidableEq Ty] (t : Ty) : List Ty → Nat
  | [] => 0
  | u :: Γ => if u = t then count t Γ + 1 else count t Γ

def toFin [DecidableEq Ty] : {Γ : List Ty} → {t : Ty} → Var Γ t → Fin (count t Γ)
  | _ :: _, _, here => ⟨0, by simp [count]⟩
  | u :: Γ, t, there v =>
      let i := toFin v
      if h : u = t then
        ⟨i.val + 1, by
          simp [count, h]⟩
      else
        ⟨i.val, by
          simp [count, h]⟩

def ofFin [DecidableEq Ty] (t : Ty) : {Γ : List Ty} → Fin (count t Γ) → Var Γ t
  | [], i => fin_zero_elim i
  | u :: Γ, i => by
      by_cases h : u = t
      · cases h
        let i' : Fin (count t Γ + 1) := ⟨i.val, by
          simpa [count] using i.isLt⟩
        exact Fin.cases here (fun j => there (ofFin t j)) i'
      · exact there (ofFin t (Γ := Γ) ⟨i.val, by
          simpa [count, h] using i.isLt⟩)

theorem ofFin_toFin [DecidableEq Ty] (t : Ty) :
    ∀ {Γ : List Ty} (i : Fin (count t Γ)), toFin (ofFin t i) = i := by
  intro Γ
  induction Γ with
  | nil =>
      intro i
      exact fin_zero_elim i
  | cons u Γ ih =>
      intro i
      by_cases h : u = t
      · cases h
        cases i with
        | mk n hn =>
          cases n with
          | zero =>
              exact fin_eq_of_val_eq (by simp [ofFin, toFin, count])
          | succ n =>
              exact fin_eq_of_val_eq (by
                simp [ofFin, toFin, count]
                exact congrArg Fin.val (ih ⟨n, by
                  simp [count] at hn
                  omega⟩))
      ·
        have hi : i.val < count t Γ := by
          simpa [count, h] using i.isLt
        exact fin_eq_of_val_eq (by
          simp [ofFin, toFin, count, h]
          exact congrArg Fin.val (ih ⟨i.val, hi⟩))

theorem toFin_ofFin [DecidableEq Ty] :
    ∀ {Γ : List Ty} {t : Ty} (v : Var Γ t), ofFin t (toFin v) = v
  | _ :: _, _, here => by
      simp [toFin, ofFin, count]
  | u :: _, t, there v => by
      by_cases h : u = t
      · cases h
        simp [toFin, ofFin, count, toFin_ofFin v]
      · simp [toFin, ofFin, count, h, toFin_ofFin v]

def finIso [DecidableEq Ty] (Γ : List Ty) (t : Ty) :
    Var Γ t ≃ᵢ Fin (count t Γ) where
  toFun := toFin
  invFun := ofFin t
  left_inv := toFin_ofFin
  right_inv := ofFin_toFin t

end Var

/-- Readable syntax generated by a typed binding signature. -/
inductive Term {Ty : Type} (S : Signature Ty) : List Ty → Ty → Type
  | var {Γ : List Ty} {t : Ty} (v : Var Γ t) : Term S Γ t
  | op {Γ : List Ty} (c : S.Ctor)
      (child :
        (q : S.ArgPos c) →
          Term S ((S.arg c q).binders ++ Γ) (S.arg c q).sort) :
      Term S Γ (S.ret c)

namespace Term

variable {Ty : Type} {S : Signature Ty}

/-- Structural rank used for the generated syntax coding. -/
def rank : {Γ : List Ty} → {t : Ty} → Term S Γ t → Nat
  | _, _, var _ => 0
  | _, _, op c child =>
      finMax (fun q : S.ArgPos c => rank (child q)) + 1

theorem child_rank_lt {Γ : List Ty} {c : S.Ctor}
    (child :
      (q : S.ArgPos c) →
        Term S ((S.arg c q).binders ++ Γ) (S.arg c q).sort)
    (q : S.ArgPos c) :
    rank (child q) < rank (Term.op (S := S) (Γ := Γ) c child) := by
  exact lt_finMax_succ (fun q : S.ArgPos c => rank (child q)) q

end Term

/-- Polynomial constructors generated from a binding signature.  Variables are
not part of the user signature; they are generated from the current context. -/
inductive PolyCtor {Ty : Type} (S : Signature Ty) where
  | var
  | op (c : S.Ctor)

namespace Poly

variable {Ty : Type} (S : Signature Ty)

abbrev Ix (_S : Signature Ty) : Type :=
  List Ty × Ty

def Param : PolyCtor S → Type
  | .var => Σ Γ : List Ty, Σ t : Ty, Var Γ t
  | .op _ => List Ty

def out : (c : PolyCtor S) → Param S c → Ix S
  | .var, p => (p.1, p.2.1)
  | .op c, Γ => (Γ, S.ret c)

def Pos : (c : PolyCtor S) → Param S c → Type
  | .var, _ => Empty
  | .op c, _ => S.ArgPos c

def input : {c : PolyCtor S} → (p : Param S c) → Pos S c p → Ix S
| .var, _, q => nomatch q
| .op c, (Γ : List Ty), q => ((S.arg c q).binders ++ Γ, (S.arg c q).sort)

/-- The dependent polynomial generated by a typed binding signature. -/
def depPoly : DepPoly (Ix S) where
  Ctor := PolyCtor S
  Param := Param S
  out := out S
  Pos := Pos S
  input := input S

end Poly

abbrev PolyOf {Ty : Type} (S : Signature Ty) : DepPoly (Poly.Ix S) :=
  Poly.depPoly S

/-- Constructor-local parameter code generated from a binding signature. -/
def FiberParamCode {Ty : Type} (S : Signature Ty) :
    PolyCtor S → Poly.Ix S → Type
  | .var, (Γ, t) => Var Γ t
  | .op c, (_Γ, t) => PLift (S.ret c = t)

namespace FiberParamCode

variable {Ty : Type} {S : Signature Ty}

def decode : {ctor : PolyCtor S} → {i : Poly.Ix S} →
    FiberParamCode S ctor i →
      { param : Poly.Param S ctor // Poly.out S ctor param = i }
  | .var, (Γ, t), v => ⟨⟨Γ, t, v⟩, rfl⟩
  | .op c, (Γ, _t), h => by
      cases h with
      | up h =>
          cases h
          exact ⟨Γ, rfl⟩

def encode : {ctor : PolyCtor S} → {i : Poly.Ix S} →
    { param : Poly.Param S ctor // Poly.out S ctor param = i } →
      FiberParamCode S ctor i
  | .var, (_Γ, _t), ⟨param, h⟩ => by
      rcases param with ⟨Γ, t, v⟩
      cases h
      exact v
  | .op _c, (_Γ, _t), ⟨Γ, h⟩ => by
      cases h
      exact PLift.up rfl

end FiberParamCode

/-- Same-fiber constructor code generated from the binding signature. -/
abbrev FiberCode {Ty : Type} (S : Signature Ty) (i : Poly.Ix S) : Type :=
  Σ ctor : PolyCtor S, FiberParamCode S ctor i

namespace FiberCode

variable {Ty : Type} {S : Signature Ty}

def var {Γ : List Ty} {t : Ty} (v : Var Γ t) : FiberCode S (Γ, t) :=
  ⟨.var, v⟩

def op {Γ : List Ty} {t : Ty} (c : S.Ctor) (h : S.ret c = t) :
    FiberCode S (Γ, t) :=
  ⟨.op c, PLift.up h⟩

end FiberCode

/-- Output-index inversion generated from the binding signature. -/
def inversion {Ty : Type} (S : Signature Ty) :
    OutputIndexInversion (PolyOf S) :=
  OutputIndexInversion.ofConstructorParamCodes
    (FiberParamCode S)
    (decodeParam := FiberParamCode.decode (S := S))
    (encodeParam := FiberParamCode.encode (S := S))
    (by
      intro ctor i param
      cases i with
      | mk Γ t =>
          cases ctor with
          | var =>
              rcases param with ⟨param, h⟩
              rcases param with ⟨Γ', t', v⟩
              cases h
              rfl
          | op c =>
              rcases param with ⟨Γ', h⟩
              cases h
              rfl)
    (by
      intro ctor i code
      cases i with
      | mk Γ t =>
          cases ctor with
          | var => rfl
          | op c =>
              cases code with
              | up h =>
                  cases h
                  rfl)

namespace SyntaxIso

variable {Ty : Type} {S : Signature Ty}

def layerToTerm (i : Poly.Ix S) :
    CodeLayer (PolyOf S) (inversion S) (fun i => Term S i.1 i.2) i →
      Term S i.1 i.2
  | ⟨⟨.var, v⟩, _child⟩ => Term.var v
  | ⟨⟨.op c, h⟩, child⟩ => by
      cases i with
      | mk Γ t =>
        cases h with
        | up h =>
            cases h
            refine Term.op (S := S) (Γ := Γ) c ?_
            intro q
            exact child q

def termToLayer : {Γ : List Ty} → {t : Ty} →
    Term S Γ t →
      CodeLayer (PolyOf S) (inversion S) (fun i => Term S i.1 i.2) (Γ, t)
  | _, _, Term.var v => ⟨FiberCode.var v, fun q => nomatch q⟩
  | _, _, Term.op c child => by
      refine ⟨FiberCode.op c rfl, ?_⟩
      intro q
      exact child q

theorem layer_right_inv (i : Poly.Ix S) :
    Function.RightInverse
      (fun t : Term S i.1 i.2 => termToLayer t)
      (layerToTerm (S := S) i) := by
  intro t
  cases i with
  | mk Γ ty =>
    cases t with
    | var v => rfl
    | op c child =>
        change
          layerToTerm (S := S) (Γ, S.ret c)
            (⟨FiberCode.op c rfl, fun q => child q⟩ :
              CodeLayer (PolyOf S) (inversion S)
                (fun i => Term S i.1 i.2) (Γ, S.ret c)) =
            Term.op c child
        rfl

def layerIso (i : Poly.Ix S) :
    CodeLayer (PolyOf S) (inversion S) (fun i => Term S i.1 i.2) i ≃ᵢ
      Term S i.1 i.2 where
  toFun := layerToTerm (S := S) i
  invFun := fun t => termToLayer t
  left_inv := by
    intro layer
    cases i with
    | mk Γ t =>
      rcases layer with ⟨code, child⟩
      cases code with
      | mk ctor paramCode =>
          cases ctor with
          | var =>
              exact CodeLayer.ext_layer rfl (heq_of_eq (by funext q; cases q))
          | op c =>
              cases paramCode with
              | up h =>
                  cases h
                  exact CodeLayer.ext_layer rfl (heq_of_eq rfl)
  right_inv := layer_right_inv (S := S) i

theorem layer_child_rank_lt :
    ∀ {i : Poly.Ix S} (z : Term S i.1 i.2)
      (q : (PolyOf S).Pos
          ((inversion S).decode i ((layerIso (S := S) i).invFun z).1).ctor
          ((inversion S).decode i ((layerIso (S := S) i).invFun z).1).param),
      Term.rank (((layerIso (S := S) i).invFun z).2 q) < Term.rank z := by
  intro i z q
  cases i with
  | mk Γ t =>
    cases z with
    | var v => cases q
    | op c child =>
        simpa [layerIso, termToLayer] using
          Term.child_rank_lt (S := S) (Γ := Γ) child q

end SyntaxIso

/-- The generated coding of the initial algebra by readable binding syntax. -/
def syntaxGeneratedCode {Ty : Type} (S : Signature Ty) :
    GeneratedCode (PolyOf S) (fun i => Term S i.1 i.2) where
  inversion := inversion S
  layer := SyntaxIso.layerIso
  rank := fun _ t => Term.rank t
  child_rank_lt := SyntaxIso.layer_child_rank_lt

/-- Readable binding syntax is isomorphic to the generated initial algebra. -/
def syntaxIso {Ty : Type} (S : Signature Ty) (Γ : List Ty) (t : Ty) :
    Mu (PolyOf S) (Γ, t) ≃ᵢ Term S Γ t :=
  (syntaxGeneratedCode S).iso (Γ, t)

/-- The constructor part of a one-step binding layer for output `(Γ, t)`.
It records a signature constructor whose return sort is `t`, together with the
recursive child codes required by that constructor under the extended contexts
specified by the signature. -/
structure CtorLayer {Ty : Type} (S : Signature Ty) (Code : Poly.Ix S → Type)
    (Γ : List Ty) (t : Ty) where
  ctor : S.Ctor
  ret_eq : S.ret ctor = t
  child :
    (q : S.ArgPos ctor) →
      Code ((S.arg ctor q).binders ++ Γ, (S.arg ctor q).sort)

/-- Product of child codes for a concrete finite constructor-argument list. -/
abbrev ArgTuple {Ty : Type} (S : Signature Ty) (Code : Poly.Ix S → Type)
    (Γ : List Ty) : List (Arg Ty) → Type :=
  ListPiTuple (fun arg => Code (arg.binders ++ Γ, arg.sort))

namespace ArgTuple

variable {Ty : Type} {S : Signature Ty} {Code : Poly.Ix S → Type}

def ofChild (Γ : List Ty) :
    {args : List (Arg Ty)} →
      ((q : Fin args.length) →
        Code (((args.get q).binders ++ Γ), (args.get q).sort)) →
      ArgTuple S Code Γ args
  | args, child =>
      ListPiTuple.ofPi
        (F := fun arg => Code (arg.binders ++ Γ, arg.sort))
        (xs := args) child

def toChild (Γ : List Ty) :
    {args : List (Arg Ty)} →
      ArgTuple S Code Γ args →
        (q : Fin args.length) →
          Code (((args.get q).binders ++ Γ), (args.get q).sort)
  | args, tuple =>
      ListPiTuple.toPi
        (F := fun arg => Code (arg.binders ++ Γ, arg.sort))
        (xs := args) tuple

theorem toChild_ofChild (Γ : List Ty) :
    {args : List (Arg Ty)} →
      (child :
        (q : Fin args.length) →
          Code (((args.get q).binders ++ Γ), (args.get q).sort)) →
      toChild Γ (ofChild Γ child) = child
  | args, child => by
      simpa [ofChild, toChild] using
        ListPiTuple.toPi_ofPi
        (F := fun arg => Code (arg.binders ++ Γ, arg.sort))
        (xs := args) child

@[simp]
theorem toChild_ofChild_apply (Γ : List Ty) {args : List (Arg Ty)}
    (child :
      (q : Fin args.length) →
        Code (((args.get q).binders ++ Γ), (args.get q).sort))
    (q : Fin args.length) :
    toChild Γ (ofChild Γ child) q = child q := by
  exact congrFun (toChild_ofChild (S := S) (Code := Code) Γ child) q

theorem ofChild_toChild (Γ : List Ty) :
    {args : List (Arg Ty)} →
      (tuple : ArgTuple S Code Γ args) →
      ofChild Γ (toChild Γ tuple) = tuple
  | args, tuple => by
      simpa [ofChild, toChild] using
        ListPiTuple.ofPi_toPi
        (F := fun arg => Code (arg.binders ++ Γ, arg.sort))
        (xs := args) tuple

def iso (Γ : List Ty) (args : List (Arg Ty)) :
    ((q : Fin args.length) →
        Code (((args.get q).binders ++ Γ), (args.get q).sort)) ≃ᵢ
      ArgTuple S Code Γ args where
  toFun := ofChild Γ
  invFun := toChild Γ
  left_inv := toChild_ofChild Γ
  right_inv := ofChild_toChild Γ

end ArgTuple

/-- Generic constructor-family carrier for a same-return typed-binding layer. -/
structure CtorFamily {Ty : Type} (S : Signature Ty) (Code : Poly.Ix S → Type)
    (Γ : List Ty) (t : Ty) where
  ctor : S.Ctor
  ret_eq : S.ret ctor = t
  args : ArgTuple S Code Γ (S.args ctor)

namespace CtorFamily

variable {Ty : Type} {S : Signature Ty} {Code : Poly.Ix S → Type}

theorem ext {Γ : List Ty} {t : Ty} {a b : CtorFamily S Code Γ t}
    (hctor : a.ctor = b.ctor) (hargs : a.args ≍ b.args) : a = b := by
  cases a with
  | mk ctor ret_eq args =>
    cases b with
    | mk ctor' ret_eq' args' =>
      dsimp at hctor hargs
      cases hctor
      cases hargs
      cases ret_eq
      cases ret_eq'
      rfl

structure Case (S : Signature Ty) (t : Ty) where
  ctor : S.Ctor
  ret_eq : S.ret ctor = t

abbrev CaseCarrier (Γ : List Ty) {t : Ty} (cases : List (Case S t)) : Type :=
  Σ q : Fin cases.length, ArgTuple S Code Γ (S.args ((cases.get q).ctor))

def caseListIso (Γ : List Ty) {t : Ty} (cases : List (Case S t))
    (indexOf : (c : S.Ctor) → S.ret c = t → Fin cases.length)
    (indexOf_spec : ∀ c h, (cases.get (indexOf c h)).ctor = c)
    (indexOf_get : ∀ q : Fin cases.length,
      indexOf (cases.get q).ctor (cases.get q).ret_eq = q) :
    CtorFamily S Code Γ t ≃ᵢ CaseCarrier (S := S) (Code := Code) Γ cases where
  toFun family := by
    cases family with
    | mk c h args =>
        let q : Fin cases.length := indexOf c h
        have hargs : ArgTuple S Code Γ (S.args c) =
            ArgTuple S Code Γ (S.args ((cases.get q).ctor)) := by
          exact congrArg (fun args => ArgTuple S Code Γ args)
            (congrArg (fun ctor => S.args ctor) (indexOf_spec c h).symm)
        exact ⟨q, cast hargs args⟩
  invFun entry :=
    ⟨(cases.get entry.1).ctor, (cases.get entry.1).ret_eq, entry.2⟩
  left_inv := by
    intro family
    cases family with
    | mk c h args =>
        dsimp
        let q : Fin cases.length := indexOf c h
        have hq : q = indexOf c h := rfl
        have hc : (cases.get q).ctor = c := by
          simpa [hq] using indexOf_spec c h
        have hargs : ArgTuple S Code Γ (S.args c) =
            ArgTuple S Code Γ (S.args ((cases.get q).ctor)) := by
          exact congrArg (fun args => ArgTuple S Code Γ args)
            (congrArg (fun ctor => S.args ctor) hc.symm)
        apply ext
        · exact hc
        · exact cast_heq hargs args
  right_inv := by
    intro entry
    cases entry with
    | mk q args =>
        dsimp
        let q' : Fin cases.length :=
          indexOf (cases.get q).ctor (cases.get q).ret_eq
        have hq' : q' =
            indexOf (cases.get q).ctor (cases.get q).ret_eq := rfl
        have hq : q' = q := by
          simpa [hq'] using indexOf_get q
        apply Sigma.ext hq
        have hc :
            (cases.get q').ctor = (cases.get q).ctor := by
          simpa [hq'] using indexOf_spec (cases.get q).ctor (cases.get q).ret_eq
        have hargs : ArgTuple S Code Γ (S.args ((cases.get q).ctor)) =
            ArgTuple S Code Γ (S.args ((cases.get q').ctor)) := by
          exact congrArg (fun args => ArgTuple S Code Γ args)
            (congrArg (fun ctor => S.args ctor) hc.symm)
        exact cast_heq hargs args

end CtorFamily

namespace CtorLayer

variable {Ty : Type} {S : Signature Ty} {Code : Poly.Ix S → Type}

def toFamily (Γ : List Ty) (t : Ty) :
    CtorLayer S Code Γ t → CtorFamily S Code Γ t
  | ⟨c, h, child⟩ =>
      ⟨c, h,
        ArgTuple.ofChild (S := S) (Code := Code) Γ
          (args := S.args c) child⟩

def ofFamily (Γ : List Ty) (t : Ty) :
    CtorFamily S Code Γ t → CtorLayer S Code Γ t
  | ⟨c, h, args⟩ =>
      ⟨c, h,
        ArgTuple.toChild (S := S) (Code := Code) Γ
          (args := S.args c) args⟩

theorem ofFamily_toFamily (Γ : List Ty) (t : Ty) :
    Function.LeftInverse (ofFamily (S := S) (Code := Code) Γ t)
      (toFamily (S := S) (Code := Code) Γ t) := by
  intro layer
  cases layer with
  | mk c h child =>
      dsimp [toFamily, ofFamily]
      rw [ArgTuple.toChild_ofChild]

theorem toFamily_ofFamily (Γ : List Ty) (t : Ty) :
    Function.RightInverse (ofFamily (S := S) (Code := Code) Γ t)
      (toFamily (S := S) (Code := Code) Γ t) := by
  intro family
  cases family with
  | mk c h args =>
      dsimp [toFamily, ofFamily]
      rw [ArgTuple.ofChild_toChild]

def familyIso (Γ : List Ty) (t : Ty) :
    CtorLayer S Code Γ t ≃ᵢ CtorFamily S Code Γ t where
  toFun := toFamily (S := S) (Code := Code) Γ t
  invFun := ofFamily (S := S) (Code := Code) Γ t
  left_inv := ofFamily_toFamily (S := S) (Code := Code) Γ t
  right_inv := toFamily_ofFamily (S := S) (Code := Code) Γ t

end CtorLayer

/-- Generic one-step layer shape for typed-binding signatures: either a
context variable of the requested type, or a same-return constructor layer. -/
abbrev LayerShape {Ty : Type} (S : Signature Ty) (Code : Poly.Ix S → Type)
    (Γ : List Ty) (t : Ty) : Type :=
  Var Γ t ⊕ CtorLayer S Code Γ t

namespace LayerShape

variable {Ty : Type} {S : Signature Ty} {Code : Poly.Ix S → Type}

def layerToShape (Γ : List Ty) (t : Ty) :
    CodeLayer (PolyOf S) (inversion S) Code (Γ, t) →
      LayerShape S Code Γ t
  | ⟨⟨.var, v⟩, _child⟩ => Sum.inl v
  | ⟨⟨.op c, h⟩, child⟩ => by
      cases h with
      | up h =>
          cases h
          exact Sum.inr ⟨c, rfl, child⟩

def shapeToLayer (Γ : List Ty) (t : Ty) :
    LayerShape S Code Γ t →
      CodeLayer (PolyOf S) (inversion S) Code (Γ, t)
  | Sum.inl v => ⟨FiberCode.var v, fun q => nomatch q⟩
  | Sum.inr ctor => by
      cases ctor with
      | mk c h child =>
        cases h
        exact ⟨FiberCode.op c rfl, child⟩

theorem layerShape_left_inv (Γ : List Ty) (t : Ty) :
    Function.LeftInverse (shapeToLayer (S := S) (Code := Code) Γ t)
      (layerToShape (S := S) (Code := Code) Γ t) := by
  intro layer
  rcases layer with ⟨code, child⟩
  cases code with
  | mk ctor paramCode =>
      cases ctor with
      | var =>
          exact CodeLayer.ext_layer rfl (heq_of_eq (by funext q; cases q))
      | op c =>
          cases paramCode with
          | up h =>
              cases h
              exact CodeLayer.ext_layer rfl (heq_of_eq rfl)

theorem layerShape_right_inv (Γ : List Ty) (t : Ty) :
    Function.RightInverse (shapeToLayer (S := S) (Code := Code) Γ t)
      (layerToShape (S := S) (Code := Code) Γ t) := by
  intro shape
  cases shape with
  | inl v => rfl
  | inr ctor =>
      cases ctor with
      | mk c h child =>
        cases h
        rfl

def iso (Γ : List Ty) (t : Ty) :
    CodeLayer (PolyOf S) (inversion S) Code (Γ, t) ≃ᵢ
      LayerShape S Code Γ t where
  toFun := layerToShape (S := S) (Code := Code) Γ t
  invFun := shapeToLayer (S := S) (Code := Code) Γ t
  left_inv := layerShape_left_inv (S := S) (Code := Code) Γ t
  right_inv := layerShape_right_inv (S := S) (Code := Code) Γ t

def familyIso (Γ : List Ty) (t : Ty) :
    LayerShape S Code Γ t ≃ᵢ (Var Γ t ⊕ CtorFamily S Code Γ t) :=
  Iso.sum (Iso.refl (Var Γ t)) (CtorLayer.familyIso (S := S) (Code := Code) Γ t)

def carrierCoding (Γ : List Ty) (t : Ty)
    {VarCode CtorCode : Type}
    (varIso : Var Γ t ≃ᵢ VarCode)
    (ctorIso : CtorFamily S Code Γ t ≃ᵢ CtorCode) :
    LayerShape S Code Γ t ≃ᵢ (VarCode ⊕ CtorCode) :=
  Iso.trans (familyIso (S := S) (Code := Code) Γ t)
    (Iso.sum varIso ctorIso)

def layerCoding {Carrier : Poly.Ix S → Type}
    (layerShape : ∀ Γ t, LayerShape S Code Γ t ≃ᵢ Carrier (Γ, t))
    (Γ : List Ty) (t : Ty) :
    CodeLayer (PolyOf S) (inversion S) Code (Γ, t) ≃ᵢ Carrier (Γ, t) :=
  Iso.trans (iso (S := S) (Code := Code) Γ t) (layerShape Γ t)

theorem layerCoding_op_toFun {Carrier : Poly.Ix S → Type}
    (layerShape : ∀ Γ t, LayerShape S Code Γ t ≃ᵢ Carrier (Γ, t))
    (Γ : List Ty) (c : S.Ctor)
    (child :
      (q : S.ArgPos c) →
        Code ((S.arg c q).binders ++ Γ, (S.arg c q).sort)) :
    (layerCoding (S := S) (Code := Code) layerShape Γ (S.ret c)).toFun
        (⟨FiberCode.op c rfl, child⟩ :
          CodeLayer (PolyOf S) (inversion S) Code (Γ, S.ret c)) =
      (layerShape Γ (S.ret c)).toFun
        (Sum.inr (⟨c, rfl, child⟩ : CtorLayer S Code Γ (S.ret c))) :=
  rfl

def layerCarrierCoding (Γ : List Ty) (t : Ty)
    {VarCode CtorCode : Type}
    (varIso : Var Γ t ≃ᵢ VarCode)
    (ctorIso : CtorFamily S Code Γ t ≃ᵢ CtorCode) :
    CodeLayer (PolyOf S) (inversion S) Code (Γ, t) ≃ᵢ (VarCode ⊕ CtorCode) :=
  Iso.trans (iso (S := S) (Code := Code) Γ t)
    (carrierCoding (S := S) (Code := Code) Γ t varIso ctorIso)

theorem layerCarrierCoding_op_toFun (Γ : List Ty)
    {VarCode CtorCode : Type}
    (c : S.Ctor)
    (varIso : Var Γ (S.ret c) ≃ᵢ VarCode)
    (ctorIso : CtorFamily S Code Γ (S.ret c) ≃ᵢ CtorCode)
    (child :
      (q : S.ArgPos c) →
        Code ((S.arg c q).binders ++ Γ, (S.arg c q).sort)) :
    (layerCarrierCoding (S := S) (Code := Code) Γ (S.ret c) varIso ctorIso).toFun
        (⟨FiberCode.op c rfl, child⟩ :
          CodeLayer (PolyOf S) (inversion S) Code (Γ, S.ret c)) =
      Sum.inr
        (ctorIso.toFun
          ⟨c, rfl,
            ArgTuple.ofChild (S := S) (Code := Code) Γ
              (args := S.args c) child⟩) :=
  rfl

@[simp]
theorem transLayerCarrierCodingOp (Γ : List Ty)
    {VarCode CtorCode Carrier : Type}
    (c : S.Ctor)
    (varIso : Var Γ (S.ret c) ≃ᵢ VarCode)
    (ctorIso : CtorFamily S Code Γ (S.ret c) ≃ᵢ CtorCode)
    (post : (VarCode ⊕ CtorCode) ≃ᵢ Carrier)
    (child :
      (q : S.ArgPos c) →
        Code ((S.arg c q).binders ++ Γ, (S.arg c q).sort)) :
    (Iso.trans
        (layerCarrierCoding (S := S) (Code := Code) Γ (S.ret c)
          varIso ctorIso)
        post).toFun
        (⟨FiberCode.op c rfl, child⟩ :
          CodeLayer (PolyOf S) (inversion S) Code (Γ, S.ret c)) =
      post.toFun
        (Sum.inr
          (ctorIso.toFun
            ⟨c, rfl,
              ArgTuple.ofChild (S := S) (Code := Code) Γ
                (args := S.args c) child⟩)) :=
  rfl

theorem carrierCoding_op_toFun (Γ : List Ty)
    {VarCode CtorCode : Type}
    (c : S.Ctor)
    (varIso : Var Γ (S.ret c) ≃ᵢ VarCode)
    (ctorIso : CtorFamily S Code Γ (S.ret c) ≃ᵢ CtorCode)
    (child :
      (q : S.ArgPos c) →
        Code ((S.arg c q).binders ++ Γ, (S.arg c q).sort)) :
    (carrierCoding (S := S) (Code := Code) Γ (S.ret c) varIso ctorIso).toFun
        ((iso (S := S) (Code := Code) Γ (S.ret c)).toFun
          (⟨FiberCode.op c rfl, child⟩ :
            CodeLayer (PolyOf S) (inversion S) Code (Γ, S.ret c))) =
      Sum.inr
        (ctorIso.toFun
          ⟨c, rfl,
            ArgTuple.ofChild (S := S) (Code := Code) Γ
              (args := S.args c) child⟩) :=
  rfl

end LayerShape

/-- Layer-local descent obligation for carrier codings built from the generated
typed-binding layer shape.  The child comes from the decoded raw layer, but the
parent code is computed by first passing that layer through the generated
`LayerShape.iso` and then through the instance's shape-to-carrier isomorphism. -/
abbrev LayerShapeRankProof {Ty : Type} (S : Signature Ty)
    (Code : Poly.Ix S → Type)
    (layerShape : ∀ Γ t, LayerShape S Code Γ t ≃ᵢ Code (Γ, t))
    (rank : ∀ i, Code i → Nat) : Prop :=
  ∀ {Γ : List Ty} {t : Ty}
    (layer : CodeLayer (PolyOf S) (inversion S) Code (Γ, t))
    (q : (PolyOf S).Pos
        ((inversion S).decode (Γ, t) layer.1).ctor
        ((inversion S).decode (Γ, t) layer.1).param),
    rank
        ((PolyOf S).input
          ((inversion S).decode (Γ, t) layer.1).param q)
        (layer.2 q) <
      rank (Γ, t)
        ((LayerShape.layerCoding (S := S) (Code := Code) layerShape Γ t).toFun
          layer)

namespace LayerShapeRankProof

variable {Ty : Type} {S : Signature Ty} {Code : Poly.Ix S → Type}
variable {layerShape : ∀ Γ t, LayerShape S Code Γ t ≃ᵢ Code (Γ, t)}
variable {rank : ∀ i, Code i → Nat}

/-- Constructor-family descent data for a generated typed-binding layer shape. -/
abbrev CtorFamilyRankBound : Prop :=
  ∀ {Γ : List Ty} {t : Ty}
    (family : CtorFamily S Code Γ t) (q : S.ArgPos family.ctor),
    rank
        ((S.arg family.ctor q).binders ++ Γ, (S.arg family.ctor q).sort)
        (ArgTuple.toChild (S := S) (Code := Code) Γ family.args q) <
      rank (Γ, t)
        ((layerShape Γ t).toFun
          (Sum.inr (CtorLayer.ofFamily (S := S) (Code := Code) Γ t family)))

theorem ofCtorFamilyRankBound (h : CtorFamilyRankBound
    (S := S) (Code := Code) (layerShape := layerShape) (rank := rank)) :
    LayerShapeRankProof S Code layerShape rank := by
  intro Γ t layer q
  rcases layer with ⟨fiberCode, child⟩
  cases fiberCode with
  | mk ctor paramCode =>
      cases ctor with
      | var =>
          cases q
      | op c =>
          cases paramCode with
          | up hret =>
              cases hret
              have hbound := h
                (Γ := Γ) (t := S.ret c)
                (⟨c, rfl,
                  ArgTuple.ofChild (S := S) (Code := Code) Γ
                    (args := S.args c) child⟩ :
                  CtorFamily S Code Γ (S.ret c)) q
              change
                rank ((S.arg c q).binders ++ Γ, (S.arg c q).sort)
                    (child q) <
                  rank (Γ, S.ret c)
                    ((LayerShape.layerCoding (S := S) (Code := Code)
                      layerShape Γ (S.ret c)).toFun
                      (⟨FiberCode.op c rfl, child⟩ :
                        CodeLayer (PolyOf S) (inversion S) Code
                          (Γ, S.ret c)))
              rw [LayerShape.layerCoding_op_toFun]
              simpa [CtorLayer.ofFamily, ArgTuple.toChild_ofChild] using hbound

end LayerShapeRankProof

/-- Coding data whose one-step layer is generated from the typed-binding
signature before being encoded into the concrete carrier.  Instances supply an
isomorphism from the generated variable/constructor shape to their carrier,
rather than an opaque raw `CodeLayer` isomorphism. -/
structure LayerShapeCodingData {Ty : Type} (S : Signature Ty) where
  Code : Poly.Ix S → Type
  layerShape : ∀ Γ t, LayerShape S Code Γ t ≃ᵢ Code (Γ, t)
  rank : ∀ i, Code i → Nat
  shape_child_rank_lt : LayerShapeRankProof S Code layerShape rank

namespace LayerShapeCodingData

variable {Ty : Type} {S : Signature Ty}

def layer (D : LayerShapeCodingData S) (i : Poly.Ix S) :
    CodeLayer (PolyOf S) (inversion S) D.Code i ≃ᵢ D.Code i := by
  cases i with
  | mk Γ t =>
      exact LayerShape.layerCoding (S := S) (Code := D.Code) D.layerShape Γ t

def toGeneratedCode (D : LayerShapeCodingData S) :
    GeneratedCode (PolyOf S) D.Code :=
  GeneratedCode.ofLayerChildRank (inversion S) D.layer D.rank
    (by
      intro i layer q
      cases i with
      | mk Γ t =>
          exact D.shape_child_rank_lt layer q)

def iso (D : LayerShapeCodingData S) (Γ : List Ty) (t : Ty) :
    Mu (PolyOf S) (Γ, t) ≃ᵢ D.Code (Γ, t) :=
  D.toGeneratedCode.iso (Γ, t)

def syntaxCodeIso (D : LayerShapeCodingData S) (Γ : List Ty) (t : Ty) :
    Term S Γ t ≃ᵢ D.Code (Γ, t) :=
  GeneratedCode.codeIso (syntaxGeneratedCode S) D.toGeneratedCode (Γ, t)

end LayerShapeCodingData

end TypedBinding
end BijForm
